### ISSUE TITLE
PmmlCompilerHelloWorldSpec test fails with permissions denied on /tmp dir

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#1013]
During the PmmlCompilerHelloWorldSpec tests, there is an attempt to generate files in the /tmp directory. This directory is a directory that has uncertain permissions and would require unnecessary manual setup. The target directory needs to be made relative to the resources directory. Either a pre-defined directory should be made in resources and referenced, or a directory within the resources directory should be created before the test and deleted afterwards. See the exception from the failed test below:

```
[info] - should compile HelloWorld kPMML model *** FAILED ***
[info]   java.io.FileNotFoundException: /tmp/HelloWorld.xml (Permission denied)
[info]   at java.io.FileOutputStream.open(Native Method)
[info]   at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
[info]   at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
[info]   at java.io.FileWriter.<init>(FileWriter.java:90)
[info]   at com.ligadata.pmml.compiler.PmmlCompiler.writeSrcFile(PmmlCompiler.scala:931)
[info]   at com.ligadata.pmml.compiler.PmmlCompiler.compile(PmmlCompiler.scala:499)
[info]   at com.ligadata.automation.unittests.pmmlcompiler.PmmlCompilerHelloWorldSpec$$anonfun$1.apply$mcV$sp(PmmlCompilerHelloWorldSpec.scala:88)
[info]   at com.ligadata.automation.unittests.pmmlcompiler.PmmlCompilerHelloWorldSpec$$anonfun$1.apply(PmmlCompilerHelloWorldSpec.scala:43)
[info]   at com.ligadata.automation.unittests.pmmlcompiler.PmmlCompilerHelloWorldSpec$$anonfun$1.apply(PmmlCompilerHelloWorldSpec.scala:43)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   ...
```

**Comment by ligadata-rich** [comment]
There is nothing **_uncertain_** about the permissions on **/tmp.**  It should always be:

drwxrwxrwt   8 root root 32768 Apr  4 20:17 tmp

The normal settings for /tmp are 1777, which ls shows as drwxrwxrwt. That is: wide open, except that only the owner of a file can remove it (that's what this extra t bit means for a directory).
See the checked (best) answer at http://unix.stackexchange.com/questions/71622/what-are-common-rights-for-tmp-i-unintentionnally-set-it-all-public-recursive for more details.

Any user should be able to read and write to the file but only the creator can remove it.

The questions are:

1) what is the permissions of /tmp on your system when you run the test?
2) if it is not "drwxrwxrwt", how come?

**Comment by ligadata-william** [comment]
The main point I was trying to make was that any directory that we use as part of a unit test should be under the project-in-question's resources directory. As far as my tmp dir, if I restart my laptop, I don't even have a /tmp directory because it has been erased. When I create any directory /* without using sudo, I get a permission denied error, which means when I sudo mkdir /tmp, it has elevated permissions by default.

**Comment by ligadata-pokuri** [comment]
For now we can keep it as P2/P3. If it is really blocking testing we can move to P1 in next release and see alternatives what should we do.
