### ISSUE TITLE
JsonChecker object test fails and has non-explanatory test name

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1016]
There is a test with Feature: JsonChecker object and Scenario: test if everything is ok. This test fails due to a FileNotFoundException. This is because the file it's looking for is a hard-coded path that does not exist on anyone else's computer. ALL files being used as part of a unit test MUST be in a resources folder so that the location is always accessible. The file ConfigParameters.json does not exist in source and is therefore not accessible to the test.

Additionally "test if everything is ok" is a bad test name. It gives no explanation whatsoever as to the nature of the test.
```
[info]   Scenario: test if everything is ok *** FAILED ***
[info]   java.io.FileNotFoundException: C:\Users\Yousef\Desktop\BotnetDetection\Jsonfile\ConfigParameters.json (No such file or directory)
[info]   at java.io.FileInputStream.open(Native Method)
[info]   at java.io.FileInputStream.<init>(FileInputStream.java:146)
[info]   at scala.io.Source$.fromFile(Source.scala:90)
[info]   at scala.io.Source$.fromFile(Source.scala:75)
[info]   at scala.io.Source$.fromFile(Source.scala:53)
[info]   at com.ligadata.jsonutility.JsonChecker.ReadFile(JsonChecker.scala:121)
[info]   at com.ligadata.jsonutility.JsonCheckerTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(JsonCheckerTest.scala:20)
[info]   at com.ligadata.jsonutility.JsonCheckerTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(JsonCheckerTest.scala:16)
[info]   at com.ligadata.jsonutility.JsonCheckerTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(JsonCheckerTest.scala:16)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   ...
[info]     Given Initiate variables
[info]     Given Call readFile function
```

**Comment by ligadata-william** [comment]
Found on 1.4.0.Test branch.

**Comment by ligadata-yousef** [comment]
Fixed

**Comment by ligadata-pokuri** [comment]
Now it is in 1.4.0.Test

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
