### ISSUE TITLE
Test "test if no data in file" fails

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1017]
This test fails due to a hard-coded path that doesn't exist on every computer. All files used in unit tests must exist inside the resources folder in source and must be referenced there in order to work across all environments. See the failed test and exception below.

```
[info]   Scenario: test if no data in file *** FAILED ***
[info]   java.io.FileNotFoundException: C:\Users\Yousef\Desktop\BotnetDetection\Jsonfile\ConfigParameterstest.json (No such file or directory)
[info]   at java.io.FileInputStream.open(Native Method)
[info]   at java.io.FileInputStream.<init>(FileInputStream.java:146)
[info]   at scala.io.Source$.fromFile(Source.scala:90)
[info]   at scala.io.Source$.fromFile(Source.scala:75)
[info]   at scala.io.Source$.fromFile(Source.scala:53)
[info]   at com.ligadata.jsonutility.JsonChecker.ReadFile(JsonChecker.scala:121)
[info]   at com.ligadata.jsonutility.JsonCheckerTest$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(JsonCheckerTest.scala:56)
[info]   at com.ligadata.jsonutility.JsonCheckerTest$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(JsonCheckerTest.scala:51)
[info]   at com.ligadata.jsonutility.JsonCheckerTest$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(JsonCheckerTest.scala:51)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   ...
[info]     Given Initiate variables
[info]     Given Call readFile function
```

**Comment by ligadata-william** [comment]
Found on 1.4.0.Test branch.

**Comment by ligadata-yousef** [comment]
Fixed

**Comment by ligadata-pokuri** [comment]
Now it is in 1.4.0.Test

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
