### ISSUE TITLE
StorageHBase fails to create tables due to guava incompatibility

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1021]
In my environment, I'm running hbase with kerberos authentication. When I attempt the command:
```
bash kamanja upload cluster config /path/to/ClusterConfig.json
```
I receive the following errors
```
ERROR [main] - Failed to create table kamanja:metadata_objects
org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:229) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:202) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:299) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:278) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:140) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:135) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:845) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:600) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:364) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:281) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:291) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at com.ligadata.keyvaluestore.HBaseAdapter.createTable(HBaseAdapter.scala:343) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.liftedTree3$1(HBaseAdapter.scala:459) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.com$ligadata$keyvaluestore$HBaseAdapter$$CreateContainer(HBaseAdapter.scala:458) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter$$anonfun$CreateMetadataContainer$1.apply(HBaseAdapter.scala:479) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter$$anonfun$CreateMetadataContainer$1.apply(HBaseAdapter.scala:477) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.ligadata.keyvaluestore.HBaseAdapter.CreateMetadataContainer(HBaseAdapter.scala:477) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.PersistenceUtils$.liftedTree1$1(PersistenceUtils.scala:790) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.PersistenceUtils$.CreateMetadataTables(PersistenceUtils.scala:786) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.CreateMetadataTables(MetadataAPIImpl.scala:1605) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:4227) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:180) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:434) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:60) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1139) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1106) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:293) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:147) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:56) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	... 23 more
ERROR [main] -
com.ligadata.Exceptions.StorageDDLException: Failed to execute create/drop operations on Database
	at com.ligadata.keyvaluestore.HBaseAdapter.CreateDDLException(HBaseAdapter.scala:88) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.createTable(HBaseAdapter.scala:372) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.liftedTree3$1(HBaseAdapter.scala:459) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.com$ligadata$keyvaluestore$HBaseAdapter$$CreateContainer(HBaseAdapter.scala:458) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter$$anonfun$CreateMetadataContainer$1.apply(HBaseAdapter.scala:479) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter$$anonfun$CreateMetadataContainer$1.apply(HBaseAdapter.scala:477) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.ligadata.keyvaluestore.HBaseAdapter.CreateMetadataContainer(HBaseAdapter.scala:477) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.PersistenceUtils$.liftedTree1$1(PersistenceUtils.scala:790) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.PersistenceUtils$.CreateMetadataTables(PersistenceUtils.scala:786) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.CreateMetadataTables(MetadataAPIImpl.scala:1605) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:4227) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:180) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
Caused by: org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:229) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:202) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:299) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:278) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:140) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:135) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:845) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:600) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:364) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:281) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:291) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at com.ligadata.keyvaluestore.HBaseAdapter.createTable(HBaseAdapter.scala:343) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	... 13 more
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:434) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:60) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1139) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1106) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:293) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:147) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:56) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:299) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:278) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:140) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:135) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:845) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:600) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:364) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:281) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:291) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at com.ligadata.keyvaluestore.HBaseAdapter.createTable(HBaseAdapter.scala:343) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	... 13 more
ERROR [main] -
com.ligadata.Exceptions.StorageDDLException: Failed to execute create/drop operations on Database
	at com.ligadata.keyvaluestore.HBaseAdapter.CreateDDLException(HBaseAdapter.scala:88) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.createTable(HBaseAdapter.scala:372) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.liftedTree3$1(HBaseAdapter.scala:459) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.com$ligadata$keyvaluestore$HBaseAdapter$$CreateContainer(HBaseAdapter.scala:458) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter$$anonfun$CreateMetadataContainer$1.apply(HBaseAdapter.scala:479) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter$$anonfun$CreateMetadataContainer$1.apply(HBaseAdapter.scala:477) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.ligadata.keyvaluestore.HBaseAdapter.CreateMetadataContainer(HBaseAdapter.scala:477) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.PersistenceUtils$.liftedTree1$1(PersistenceUtils.scala:790) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.PersistenceUtils$.CreateMetadataTables(PersistenceUtils.scala:786) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.CreateMetadataTables(MetadataAPIImpl.scala:1605) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:4227) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:180) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
Caused by: org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:229) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:202) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:299) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:278) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:140) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:135) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:845) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:600) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:364) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:281) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:291) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at com.ligadata.keyvaluestore.HBaseAdapter.createTable(HBaseAdapter.scala:343) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	... 13 more
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:434) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:60) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1139) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1106) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:293) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:147) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:56) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:299) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:278) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:140) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:135) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:845) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:600) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:364) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:281) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:291) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at com.ligadata.keyvaluestore.HBaseAdapter.createTable(HBaseAdapter.scala:343) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	... 13 more
```

**Comment by ligadata-pokuri** [comment]
Hi william, Can you verify this and close? We don't see this error in most recent days

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
