### ISSUE TITLE
"kamanja add message" does not warn the user about "reserved words" such as "type" or "case" in field names

### ISSUE THREAD

**Issue by DataBillB** [ligaDATA/Kamanja#1022]
This is a case that users could easily run into, that could be caught by a simple text search, but instead generates a "dump" of programming data.

There is a list of "reserved words" that will cause a failure if used as field names. These include words that might seem natural for users to use for names of data columns, such as "type" or "case" or "final".  The "kamanja add message" programming could check for these before attempting to add the message definition, and thus generate a user-friendly warning such as 
"The Message Definition contains one or more non-usable field names (<give field name here>).  It is a 'revered word' as listed in the Advanced Developer's Guide".

Instead it the command  fails, generating the following voluminous text:
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1/msg1.scala:83: error: illegal start of simple pattern
	var type:Int = _ ;
            ^
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1/msg1.scala:83: error: '=' expected but ';' found.
	var type:Int = _ ;
                         ^
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1/msg1.scala:84: error: illegal start of simple pattern
	var case:String = _ ;
            ^
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1/msg1.scala:84: error: '=' expected but ';' found.
	var case:String = _ ;
                            ^
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1/msg1.scala:89: error: ';' expected but 'override' found.
	override def PrimaryKeyData: Array[String] = Array[String]()
        ^
5 errors found
ERROR [main] - Compile for msg1.scala has failed...rc = 1
ERROR [main] - Command used: ArrayBuffer(sh, -c, /usr/local/Cellar/scala/2.11.6/bin/scalac -d /Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1 -cp /Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/metadata_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/basefunctions_2.11-0.1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/basetypes_2.11-0.1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/bootstrap_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/messagedef_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/exceptions_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/datadelimiters_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/guava-14.0.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/jackson-annotations-2.3.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/jackson-core-2.3.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/jackson-databind-2.3.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/joda-convert-1.6.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/joda-time-2.8.2.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/json4s-ast_2.11-3.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/json4s-core_2.11-3.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/json4s-jackson_2.11-3.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/json4s-native_2.11-3.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/jsr305-3.0.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/kamanjabase_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/kamanjautils_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/kvbase_2.11-0.1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/log4j-api-2.4.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/log4j-core-2.4.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/log4j-1.2-api-2.4.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/commons-math3-3.6.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/customudflib_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/paranamer-2.6.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmml-agent-1.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmml-evaluator-1.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmml-model-1.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmml-schema-1.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmmlcompiler_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmmlruntime_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmmludfs_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/scala-compiler-2.11.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/scala-library-2.11.7.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/scala-reflect-2.11.7.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/scalap-2.11.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/heartbeat_2.11-0.1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/metadata_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/basetypes_2.11-0.1.0.jar /Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1/msg1.scala)
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1_local/msg1_local.scala:83: error: illegal start of simple pattern
	var type:Int = _ ;
            ^
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1_local/msg1_local.scala:83: error: '=' expected but ';' found.
	var type:Int = _ ;
                         ^
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1_local/msg1_local.scala:84: error: illegal start of simple pattern
	var case:String = _ ;
            ^
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1_local/msg1_local.scala:84: error: '=' expected but ';' found.
	var case:String = _ ;
                            ^
/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1_local/msg1_local.scala:89: error: ';' expected but 'override' found.
	override def PrimaryKeyData: Array[String] = Array[String]()
        ^
5 errors found
ERROR [main] - Compile for msg1_local.scala has failed...rc = 1
ERROR [main] - Command used: ArrayBuffer(sh, -c, /usr/local/Cellar/scala/2.11.6/bin/scalac -d /Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1_local -cp /Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/metadata_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/basefunctions_2.11-0.1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/basetypes_2.11-0.1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/bootstrap_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/messagedef_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/exceptions_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/datadelimiters_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/guava-14.0.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/jackson-annotations-2.3.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/jackson-core-2.3.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/jackson-databind-2.3.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/joda-convert-1.6.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/joda-time-2.8.2.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/json4s-ast_2.11-3.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/json4s-core_2.11-3.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/json4s-jackson_2.11-3.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/json4s-native_2.11-3.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/jsr305-3.0.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/kamanjabase_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/kamanjautils_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/kvbase_2.11-0.1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/log4j-api-2.4.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/log4j-core-2.4.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/log4j-1.2-api-2.4.1.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/commons-math3-3.6.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/customudflib_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/paranamer-2.6.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmml-agent-1.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmml-evaluator-1.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmml-model-1.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmml-schema-1.2.9.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmmlcompiler_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmmlruntime_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/pmmludfs_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/scala-compiler-2.11.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/scala-library-2.11.7.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/scala-reflect-2.11.7.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/scalap-2.11.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/heartbeat_2.11-0.1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/metadata_2.11-1.0.jar:/Users/billbruns/Downloads/Kamanja-1.3.3_2.11/lib/system/basetypes_2.11-0.1.0.jar /Users/billbruns/Downloads/Kamanja-1.3.3_2.11/workingdir/msg1_local/msg1_local.scala)
ERROR [main] - Compilation of MessgeDef scala file has failed, Message is not added
ERROR [main] - Failed to compile the message definition 
com.ligadata.Exceptions.MsgCompilationFailedException: {
  "Message" : {
    "NameSpace" : "com.ligadata.kamanja.samples.messages",
    "Name" : "msg1",
    "Version" : "00.01.00",
    "Description" : "Hello World",
    "Fixed" : "true",
    "Elements" : [
      {
        "Field" : {
          "Name" : "type",
          "Type" : "System.Int"
        }
      },
      {
        "Field" : {
          "Name" : "case",
          "Type" : "System.String"
        }
      },
      {
        "Field" : {
          "Name" : "Score",
          "Type" : "System.Int"
        }
      }
    ]
  }
}

	at com.ligadata.MetadataAPI.CompilerProxy.compileMessageDef(CompilerProxy.scala:275) [MetadataAPI-1.0:1.0]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2503) [MetadataAPI-1.0:1.0]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddMessage(MetadataAPIImpl.scala:2613) [MetadataAPI-1.0:1.0]
	at com.ligadata.MetadataAPI.Utility.MessageService$$anonfun$addMessage$1.apply(MessageService.scala:59) [MetadataAPI-1.0:1.0]
	at com.ligadata.MetadataAPI.Utility.MessageService$$anonfun$addMessage$1.apply(MessageService.scala:58) [MetadataAPI-1.0:1.0]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [MetadataAPI-1.0:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [MetadataAPI-1.0:1.0]
	at com.ligadata.MetadataAPI.Utility.MessageService$.addMessage(MessageService.scala:58) [MetadataAPI-1.0:1.0]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:185) [MetadataAPI-1.0:1.0]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:149) [MetadataAPI-1.0:1.0]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [MetadataAPI-1.0:1.0]
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddContainerOrMessage",
    "Result Data" : "{\n  \"Message\" : {\n    \"NameSpace\" : \"com.ligadata.kamanja.samples.messages\",\n    \"Name\" : \"msg1\",\n    \"Version\" : \"00.01.00\",\n    \"Description\" : \"Hello World\",\n    \"Fixed\" : \"true\",\n    \"Elements\" : [\n      {\n        \"Field\" : {\n          \"Name\" : \"type\",\n          \"Type\" : \"System.Int\"\n        }\n      },\n      {\n        \"Field\" : {\n          \"Name\" : \"case\",\n          \"Type\" : \"System.String\"\n        }\n      },\n      {\n        \"Field\" : {\n          \"Name\" : \"Score\",\n          \"Type\" : \"System.Int\"\n        }\n      }\n    ]\n  }\n}\n",
    "Result Description" : "Error: com.ligadata.Exceptions.MsgCompilationFailedException: {\n  \"Message\" : {\n    \"NameSpace\" : \"com.ligadata.kamanja.samples.messages\",\n    \"Name\" : \"msg1\",\n    \"Version\" : \"00.01.00\",\n    \"Description\" : \"Hello World\",\n    \"Fixed\" : \"true\",\n    \"Elements\" : [\n      {\n        \"Field\" : {\n          \"Name\" : \"type\",\n          \"Type\" : \"System.Int\"\n        }\n      },\n      {\n        \"Field\" : {\n          \"Name\" : \"case\",\n          \"Type\" : \"System.String\"\n        }\n      },\n      {\n        \"Field\" : {\n          \"Name\" : \"Score\",\n          \"Type\" : \"System.Int\"\n        }\n      }\n    ]\n  }\n}\nFailed to add container/message"
  }
}

**Comment by ligadata-ashish** [comment]
@ligadata-alison please sync with @ligadata-william to document all reserved words that CANNOT be used in models eg. SCALA reserved words

**Comment by ligadata-alison** [comment]
we have a section:

http://kamanja.org/advanced-developers-guide-1-5/defining-messages-and-containers-1-5/input-messages-1-5/reserved-words-1-5/

with a list of all Scala reserved words. Is this ok?

**Comment by ligadata-william** [comment]
The link in documentation www.scala–lang.org/docu/files/ ScalaReference.pdf is formatted incorrectly. There is a space before ScalaReference.pdf and the hyphen '-' between the words scala and lang is actually a combined double hypen '--'. These need to be fixed. Otherwise, including the table and a link to scala's documentation ought to be fine.

**Comment by ligadata-william** [comment]
As an additional note: in an ideal world, this would also be a code fix. When we first parse the message or container definition, we should check for ourselves whether there are any reserved words in there or not and generate an error message if any are found.

**Comment by ligadata-alison** [comment]
William, would you please give me the actual link to scala's documentation
so I can reformat correctly?

**Comment by ligadata-alison** [comment]
I got it - http://www.scala-lang.org/docu/files/ScalaReference.pdf
