### ISSUE TITLE
Kamanja Manager fails to start when loading storage adapters

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1028]
Found in branch 1.4.0.Test, after adding cluster configuration, the engine fails to start with the errors:
```
ERROR [main] - Failed to instantiate output/status adapter object:com.ligadata.OutputAdapters.KafkaProducer$
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 10000 ms.
ERROR [main] - Failed to get output adapter for (teststatus_1,com.ligadata.kamanja.metadata.AdapterInfo@714febc4)
scala.runtime.NonLocalReturnControl$mcZ$sp
 WARN [shutdownHook1] - Got Shutdown request
```

When executed programmatically, an exception was found:
```
ERROR [Thread-12] - Failed to get output adapter for (storage_1,com.ligadata.kamanja.metadata.AdapterInfo@14ea1322)
java.lang.NullPointerException
	at com.ligadata.KamanjaManager.KamanjaManager$.incrAdapterChangedCntr(KamanjaManager.scala:1006) ~[classes/:?]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$LoadStorageAdapsForCfg$1.apply(KamanjaMdCfg.scala:478) [classes/:?]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$LoadStorageAdapsForCfg$1.apply(KamanjaMdCfg.scala:472) [classes/:?]
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadStorageAdapsForCfg(KamanjaMdCfg.scala:472) [classes/:?]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadAdapters(KamanjaMdCfg.scala:416) [classes/:?]
	at com.ligadata.KamanjaManager.KamanjaManager.initialize(KamanjaManager.scala:512) [classes/:?]
	at com.ligadata.KamanjaManager.KamanjaManager.run(KamanjaManager.scala:640) [classes/:?]
	at com.ligadata.automation.kamanjamanager.EmbeddedKamanjaManager$$anon$1.run(EmbeddedKamanja.scala:41) [classes/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
```

**Comment by ligadata-william** [comment]
I've determined the exception seen is due to an uninitialized variable caused when I instantiate my own KamanjaManager in the automation code. I have switched it to call the object KamanjaManager.main(args: Array[String]) method to start. However, I still get the error:
```
ERROR [main] - Failed to instantiate output/status adapter object:com.ligadata.OutputAdapters.KafkaProducer$
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 10000 ms.
ERROR [main] - Failed to get output adapter for (teststatus_1,com.ligadata.kamanja.metadata.AdapterInfo@714febc4)
scala.runtime.NonLocalReturnControl$mcZ$sp
 WARN [shutdownHook1] - Got Shutdown request
```
when I try to start after a fresh install.

**Comment by ligadata-rich** [comment]
AS IT TURNS OUT, THIS IS NOT A BUG.  It was a misunderstanding on my part on how the code detected and managed Array[Msg] and Map[String,Msg] when Msg did not exist

**Comment by ligadataruchan** [comment]
Can you please be more clear? What message did not exist?
