### ISSUE TITLE
kamanja remove container

### ISSUE THREAD

**Issue by ligadata-yousef** [LigaData/Kamanja#1040]
when you trying to remove container the below error raised but the container deleted successfully:

ERROR [main] - Failed to Update the object(com.ligadata.kamanja.samples.containers.coughcodes.000000000001000000)
java.lang.Exception: serializeObjectToJson doesn't support the objects of type com.ligadata.kamanja.metadata.StructTypeDef yet.
        at com.ligadata.MetadataAPI.MetadataAPISerialization$.serializeObjectToJson(MetadataAPISerialization.scala:633) ~[KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.UpdateObjectInDB(MetadataAPIImpl.scala:1037) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.ModifyObject(MetadataAPIImpl.scala:1487) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.DeleteObject(MetadataAPIImpl.scala:1516) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.TypeUtils$.RemoveType(TypeUtils.scala:191) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$RemoveContainer$1.apply(MessageAndContainerUtils.scala:613) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$RemoveContainer$1.apply(MessageAndContainerUtils.scala:611) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.10-1.4.0.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108) [ExtDependencyLibs2_2.10-1.4.0.jar:1.0]
        at com.ligadata.MetadataAPI.MessageAndContainerUtils$.RemoveContainer(MessageAndContainerUtils.scala:611) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.RemoveContainer(MetadataAPIImpl.scala:2083) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.Utility.ContainerService$.removeContainer(ContainerService.scala:242) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:425) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:239) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveContainer",
    "Result Data" : null,
    "Result Description" : "Deleted Container Successfully:com.ligadata.kamanja.samples.containers.coughcodes.000000000001000000"
  }
}

**Comment by ligadata-pokuri** [comment]
dhaval,

can you take a look at it?

**Comment by ligadata-dhaval** [comment]
Resolved StructTypeDef & MappedMsgTypeDef message serialization. @ligadata-yousef Could you check now?

**Comment by ligadata-yousef** [comment]
fixed
