### ISSUE TITLE
Unable to start MetadataAPI Service

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1045]
When I run
```
kamanja start webservice
```
I get the following error:
```
akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger]
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:116)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:115)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:115)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:110)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:110)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:26)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:622)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:619)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:616)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:616)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:633)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
	at com.ligadata.metadataapiservice.APIService.<init>(APIService.scala:43)
	at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:191)
	at com.ligadata.metadataapiservice.APIService.main(APIService.scala)
Caused by: java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:67)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:66)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(DynamicAccess.scala:66)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:113)
	... 19 more
Exception in thread "main" akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger]]
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:144)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:26)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:622)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:619)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:616)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:616)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:633)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
	at com.ligadata.metadataapiservice.APIService.<init>(APIService.scala:43)
	at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:191)
	at com.ligadata.metadataapiservice.APIService.main(APIService.scala)
```
Typically, logger errors are simply printed and processes move on. So if there is an underlying cause to the service not starting, it is not being properly written.

**Comment by ligadata-dan** [comment]
@ligadata-william 

Ok, fixed

**Comment by ligadata-dhaval** [comment]
I am getting the below zk error when trying to start the ws:

3796 [ERROR] CuratorFrameworkImpl: Background exception was not retry-able
or retry gave up
java.lang.IllegalStateException: instance must be started before calling
this method
at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:347)
[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.curator.framework.recipes.leader.LeaderLatch.setNode(LeaderLatch.java:661)
~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.curator.framework.recipes.leader.LeaderLatch.access$300(LeaderLatch.java:63)
~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.curator.framework.recipes.leader.LeaderLatch$4.processResult(LeaderLatch.java:490)
~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:728)
[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:505)
[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.curator.framework.imps.CreateBuilderImpl.sendBackgroundResponse(CreateBuilderImpl.java:541)
[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.curator.framework.imps.CreateBuilderImpl.access$700(CreateBuilderImpl.java:44)
[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.curator.framework.imps.CreateBuilderImpl$6.processResult(CreateBuilderImpl.java:500)
[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at
org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:599)
[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]


Best Regards,
Dhaval Kolapkar
Platform Engineer Intern | LigaDATA

**Comment by ligadata-dhaval** [comment]
Is anyone else facing the above issue?

**Comment by ligadata-dan** [comment]
@ligadata-dhaval @ligadata-william 

Dhaval, the issue is this

ava.io.IOException: Could not open /Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/config/keystore.jks as a file, class path resource, or URL.

This is caused by the default in the MetadataAPIConfig.properties 
**SSL_CERTIFICATE=/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/config/keystore.jks**

also, can you change these DEBUGS into ERRORs

      Thread.sleep(365*24*60*60*1000L)
    } catch {
      case e: InterruptedException => {
        logger.debug("Unexpected Interrupt")
      }
      case e: Exception => {
              logger.debug("", e)
      }

**Comment by ligadata-pokuri** [comment]
Hi Dan, Can you make those exceptions are errors instead of debug. Even in interrupted exception  print the stack trace even though it is debug

**Comment by ligadata-dhaval** [comment]
Hi Dan,

I just found out that the jks file is correct but the default MetadataAPIConfig.properties is missing the 
SSL_PASSWD=password
which is why it was failing.
