### ISSUE TITLE
./ContainersUtility.sh throws a NullPointerException

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1057]
./ContainersUtility.sh --containername System.TestContainer --config ~/kamanja13/Kamanja-1.4.0_2.11/config/MetadataAPIConfig.properties --operation truncate

causes	

Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at scala.io.Source$.fromFile(Source.scala:54)
	at com.ligadata.tools.containersutility.ContainersUtility$.main(ContainersUtility.scala:105)
	at com.ligadata.tools.containersutility.ContainersUtility.main(ContainersUtility.scala)

this is caused by not checking for NULL for an optional parameter

    val filter = if(options.contains('filter)) options.apply('filter) else null // include keyid and timeranges
    val filterFile = scala.io.Source.fromFile(filter).mkString // read filter file config (JSON file)

**Comment by ligadata-yousef** [comment]
@ligadata-dan  fixed please verify

**Comment by ligadata-dan** [comment]
ok, looks good
