### ISSUE TITLE
getHealthCheckNodesOnly failing and reason not valid 

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1076]
Command: https://localhost:8081/api/heartbeat/nodesonly
Body: [Node1]
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "GetHealthCheck",
    "Result Data" : "No data available",
    "Result Description" : "Get Heartbeats Failed Error: Unknown - see Kamanja Logs"
  }
}

The command is failing and the result desc should give the error instead of check logs.

**Comment by ligadata-dhaval** [comment]
Similar error for others such as the https://localhost:8081/api/heartbeat/componentnames

**Comment by ligadata-dhaval** [comment]
My cluster config is:

"Nodes": [
        {
          "NodeId": "1",
          "NodePort": 6541,
          "NodeIpAddr": "localhost",
          "JarPaths": [
            "/Users/dhavalkolapkar/Documents/dynamicloading/Kamanja-1.4.0_2.11/lib/system",
            "/Users/dhavalkolapkar/Documents/dynamicloading/Kamanja-1.4.0_2.11/lib/application"
          ],
          "Scala_home": "/usr/local/Cellar/scala/2.11.7",
          "Java_home": "/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home",
          "Roles": [
            "RestAPI",
            "ProcessingEngine"
          ],
          "Classpath": ".:/Users/dhavalkolapkar/Documents/dynamicloading/Kamanja-1.4.0_2.11/lib/system/ExtDependencyLibs_2.11-1.4.0.jar:/Users/dhavalkolapkar/Documents/dynamicloading/Kamanja-1.4.0_2.11/lib/system/KamanjaInternalDeps_2.11-1.4.0.jar:/Users/dhavalkolapkar/Documents/dynamicloading/Kamanja-1.4.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.4.0.jar"
        }
      ]

**Comment by ligadata-dhaval** [comment]
Engine error:
2733785 [ERROR] MetadataAPIGlobalLogger$: Failure processing GET_HEALTH_CHECK(Nodes Only) - unknown
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Node1': was expecting 'null', 'true', 'false' or NaN
 at [Source: [Node1]; line: 1, column: 7]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2462) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2439) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2291) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1598) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:26) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at org.json4s.jackson.JsonMethods$class.parse(JsonMethods.scala:19) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:44) ~[ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.getHealthCheckNodesOnly(MetadataAPIImpl.scala:190) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.metadataapiservice.GetHeartbeatService.process(GetHeartbeatService.scala:68) [metadataapiservice_2.11-1.4.0.jar:1.4.0]
	at com.ligadata.metadataapiservice.GetHeartbeatService$$anonfun$receive$1.applyOrElse(GetHeartbeatService.scala:48) [metadataapiservice_2.11-1.4.0.jar:1.4.0]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at com.ligadata.metadataapiservice.GetHeartbeatService.aroundReceive(GetHeartbeatService.scala:38) [metadataapiservice_2.11-1.4.0.jar:1.4.0]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) [ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [ExtDependencyLibs_2.11-1.4.0.jar:1.0]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]

**Comment by ligadata-yasser** [comment]
@ligadata-dhaval 
i see you used Body: [Node1]. there are two problems: 
- the body is parsed as json, so you need to put node name in double quotes 
- you should pass the node id as is in the cluster config 

**So body should look like this: ["1"]**

@ligadata-dan 
 I see the docs asking to use  format “Node” + “_id_of_desired_node”. but according to the code i don't see why we should do this. code would handle node names as is. 
should the docs be changed that to use (id of desired node as in cluster config)?

**Comment by ligadata-pokuri** [comment]
Hi dan, Can you provide some sample curl command here how should it look like? I think you are already doing this for getHealthCheck.

**Comment by ligadata-dan** [comment]
@ligadata-dhaval 

Can you make sure with the "" in the body?  I think our doc is missing it, and we'll mention it to Alison to document it.  I think we took it out last release

**Comment by ligadata-dan** [comment]
@ligadata-yasser 
By the way, the way to call it is here

http://kamanja.org/administration-monitoring-1-4/monitoring-kamanja-1-4/gethealthcheck-1-4/

**Comment by ligadata-dhaval** [comment]
verified the functionality. Documentation needs to be updated. It needs to be ["1"] instead of ["Node1"]

**Comment by ligadata-alison** [comment]
Hi Dhaval,
     So where I see:

"Name": "Node3",
    "Version": "1.3.0.0",
"UniqueId":19,
"LastSeen": "2015-08-0418: 26: 12",
"StartTime": "2015-08-0418: 24: 42",


I should change that to

"Name":"3"?

**Comment by ligadata-yasser** [comment]
h @ligadata-alison 

i think you should replace all occurences of (The BODY of the POST should contain a JSON array of node values in the format “Node” + “_id_of_desired_node”.)
with (The BODY of the POST should contain a JSON array of node names)

**Comment by ligadata-alison** [comment]
ok i did that but are the examples up-to-date?

http://kamanja.org/administration-monitoring-1-4/monitoring-kamanja-1-4/gethealthcheck-1-4/

**Comment by ligadata-yasser** [comment]
I think we don't need to. Nodes names are strings. so if node name in cluster config is "1", it should appear  just as is in the json result. same if node name is "Node1", it should appear as is.
So in the samples we can just assume that our nodes are ("Node1", "Node2", ....)

**Comment by ligadata-alison** [comment]
ok please verify that the documentation is correct:

http://kamanja.org/administration-monitoring-1-4/monitoring-kamanja-1-4/gethealthcheck-1-4/

**Comment by ligadata-alison** [comment]
Doc up-to-date

**Comment by ligadata-dhaval** [comment]
Yes but the documentation asks to add "Node"+"<id>" which I think should be
"<NodeId>". Our default cluster config has Nodes as 1,2. Due to this I
mistook it while testing.

Best Regards,
Dhaval Kolapkar
Platform Engineer Intern | LigaDATA

**Comment by ligadata-alison** [comment]
I replaced all occurrences to "The BODY of the POST should contain a JSON
array of node names". Is this sufficient Dhaval or is there more?
