### ISSUE TITLE
Update scala model fails with false error "version should be higher" 

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1077]
When I attempt to update a scala model, after increasing the version from 0.0.1 to 0.0.2 or 0.0.3, I attempt to update with the command
```
bash kamanja update model scala /tmp/SimpleMathDAG/Step3/DAGDivision.scala DEPENDSON DAGDivision TENANTID tenant1
```

However, despite having updated the version, I get the error
```
ERROR [main] - Failed to compile the model definition
com.ligadata.Exceptions.AlreadyExistsException: Model com.ligadata.automation.test.dag.DAGDivision version should be higher than existing Models.
	at com.ligadata.kamanja.metadata.MdMgr.MakeModelDef(mdmgr.scala:2229) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.generateModelDef(CompilerProxy.scala:778) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.compileModelFromSource(CompilerProxy.scala:92) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.UpdateCustomModel(ModelUtils.scala:1386) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.UpdateModel(ModelUtils.scala:1137) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UpdateModel(MetadataAPIImpl.scala:2330) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.ModelService$$anonfun$updateModelscala$1.apply(ModelService.scala:828) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.ModelService$$anonfun$updateModelscala$1.apply(ModelService.scala:825) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.ligadata.MetadataAPI.Utility.ModelService$.updateModelscala(ModelService.scala:825) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:424) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:268) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
ERROR [main] - COMPILER_PROXY: unable to determine model metadata information during AddModel.
com.ligadata.Exceptions.AlreadyExistsException: Model com.ligadata.automation.test.dag.DAGDivision version should be higher than existing Models.
	at com.ligadata.kamanja.metadata.MdMgr.MakeModelDef(mdmgr.scala:2229) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.generateModelDef(CompilerProxy.scala:778) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.compileModelFromSource(CompilerProxy.scala:92) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.UpdateCustomModel(ModelUtils.scala:1386) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.UpdateModel(ModelUtils.scala:1137) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UpdateModel(MetadataAPIImpl.scala:2330) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.ModelService$$anonfun$updateModelscala$1.apply(ModelService.scala:828) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.ModelService$$anonfun$updateModelscala$1.apply(ModelService.scala:825) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.ligadata.MetadataAPI.Utility.ModelService$.updateModelscala(ModelService.scala:825) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:424) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:268) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "\"UpdateModel(type = scala)\"",
    "Result Data" : null,
    "Result Description" : "Error :com.ligadata.Exceptions.AlreadyExistsException: Model com.ligadata.automation.test.dag.DAGDivision version should be higher than existing Models.Failed to Update Model"
  }
}
```

**Comment by ligadata-william** [comment]
I just ran this with "kamanja add" as well and the same error occurred.

**Comment by ligadata-william** [comment]
This is likewise occurring with messages.

**Comment by ligadata-william** [comment]
This isn't an issue. I had the wrong directory open in my editor and was updating different files.
