### ISSUE TITLE
kamanja engine is not sending input or output to kafaka

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1082]
Hi , 
   kamanja engine is not sending input or output to kafaka am seeing this exception  in kafka logs  , 
java.io.EOFException
	at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:83)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:71)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:160)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:141)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:286)
	at kafka.network.Processor.run(SocketServer.scala:413)
	at java.lang.Thread.run(Thread.java:745)

Thanks
Saleh

**Comment by ligadata-pokuri** [comment]
Can you investigate a bit more on your setup why engine is not able to connect to kafka?

**Comment by ligadata-saleh** [comment]
returning the /etc/hosts to default , i change that after installing Karberus , things get missed up after restarting the VM . 

Thanks 
Saleh
