### ISSUE TITLE
Recompile model fails when updating a message

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1091]
ERROR [main] - COMPILER_PROXY: Unable to find at least one message in the Metadata for this model
ERROR [main] - COMPILER_PROXY: unable to determine model metadata information during recompile.
com.ligadata.Exceptions.MsgCompilationFailedException: tempCode
	at com.ligadata.MetadataAPI.CompilerProxy.parseSourceForMetadata(CompilerProxy.scala:890) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.recompileModelFromSource(CompilerProxy.scala:114) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.RecompileModel(ModelUtils.scala:977) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.RecompileModel(MetadataAPIImpl.scala:2290) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:475) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:473) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$.UpdateMessage(MessageAndContainerUtils.scala:473) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UpdateMessage(MetadataAPIImpl.scala:2029) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.MessageService$.updateMessage(MessageService.scala:165) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:336) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:268) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
ERROR [main] - COMPILER_PROXY: Unable to find at least one message in the Metadata for this model
ERROR [main] - COMPILER_PROXY: unable to determine model metadata information during recompile.
com.ligadata.Exceptions.MsgCompilationFailedException: tempCode
	at com.ligadata.MetadataAPI.CompilerProxy.parseSourceForMetadata(CompilerProxy.scala:890) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.recompileModelFromSource(CompilerProxy.scala:114) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.RecompileModel(ModelUtils.scala:977) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.RecompileModel(MetadataAPIImpl.scala:2290) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:475) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:473) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$.UpdateMessage(MessageAndContainerUtils.scala:473) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UpdateMessage(MetadataAPIImpl.scala:2029) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.MessageService$.updateMessage(MessageService.scala:165) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:336) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:268) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.automation.test.tenant.tenant2message.000000000002000000"
  }
}{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "RecompileModel",
    "Result Data" : null,
    "Result Description" : "Error :com.ligadata.Exceptions.MsgCompilationFailedException: tempCodeFailed to Add Model"
  }
}{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "RecompileModel",
    "Result Data" : null,
    "Result Description" : "Error :com.ligadata.Exceptions.MsgCompilationFailedException: tempCodeFailed to Add Model"
  }
}

**Comment by ligadata-dan** [comment]
@ligadata-william @ligadata-pokuri 

Pokuri, as per our discussion... assigning to you

**Comment by ligadata-pokuri** [comment]
Dan, I am getting this

 [main] - Not Notifying the engine about this operation because The property NOTIFY_ENGINE is not set to YES
ERROR [main] - COMPILER_PROXY: unable to determine model metadata information during recompile.
java.lang.StringIndexOutOfBoundsException: String index out of range: 100
	at java.lang.String.substring(String.java:1907) ~[?:1.7.0_79]
	at java.lang.String.subSequence(String.java:1946) ~[?:1.7.0_79]
	at com.ligadata.MetadataAPI.CompilerProxy.extractPackageNameFromSource(CompilerProxy.scala:1574) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.parseSourceForMetadata(CompilerProxy.scala:871) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.recompileModelFromSource(CompilerProxy.scala:118) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.RecompileModel(ModelUtils.scala:976) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.RecompileModel(MetadataAPIImpl.scala:2290) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:475) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:473) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$.UpdateMessage(MessageAndContainerUtils.scala:473) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UpdateMessage(MetadataAPIImpl.scala:2029) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.MessageService$.updateMessage(MessageService.scala:165) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:336) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:268) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
Result: {

**Comment by ligadata-pokuri** [comment]
Take latest sources and see what is going on there.

**Comment by ligadata-pokuri** [comment]
That I got for Helloworld java model.

**Comment by ligadata-dan** [comment]
@ligadata-pokuri 

There were a few errors in there, I have checked in a few fixes..  Willie, as an originator, can verify this.  The update works for me

Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.kamanja.samples.messages.msg1.000000000001000011"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.helloworldmodel.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000001"
  }
}

**Comment by ligadata-dan** [comment]
@ligadata-william 

Please verify

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
