### ISSUE TITLE
after upgrading from 1.4.0 to 1.4.1 : kamanja operations throw errors about 1.4.0 jars

### ISSUE THREAD

**Issue by ligadata-haitham** [LigaData/Kamanja#1182]
to reproduce : 
1) add models using kamanja-1.4.0 .
2) set up kamanja-1.4.1 , and have $KAMANJA_HOME point to it.
3) do " kamanja get all models"
4) it will throw some errors, but the results will show correctly at the end.

here are the errors:
============================================
.
.
.
ERROR [main] - Node Undefined not found in metadata
ERROR [main] - Failed to download the Jar of the object(com.ligadata.kamanja.samples.models.helloworldmodel111.000000000000000001's dep jar ExtDependencyLibs2_2.11-1.4.0.jar)
com.ligadata.Exceptions.ObjectNotFoundException: Object ExtDependencyLibs2_2.11-1.4.0.jar not found in container jar_store
        at com.ligadata.MetadataAPI.PersistenceUtils$.GetObject(PersistenceUtils.scala:121) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetObject(MetadataAPIImpl.scala:716) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1298) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1290) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.DownloadJarFromDB(MetadataAPIImpl.scala:1290) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.com$ligadata$MetadataAPI$MetadataAPIImpl$$DeserializeAndAddObject(MetadataAPIImpl.scala:2815) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1$$anonfun$apply$4.apply(MetadataAPIImpl.scala:2903) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1$$anonfun$apply$4.apply(MetadataAPIImpl.scala:2896) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.StorageBase.DataStoreOperations$$anonfun$8.apply(StorageAdapterBase.scala:135) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.StorageBase.DataStoreOperations$$anonfun$8.apply(StorageAdapterBase.scala:128) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.keyvaluestore.HBaseAdapter.com$ligadata$keyvaluestore$HBaseAdapter$$processRow(HBaseAdapter.scala:968) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:1027) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.StorageBase.DataStoreOperations$class.get(StorageAdapterBase.scala:139) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:60) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1.apply(MetadataAPIImpl.scala:2896) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1.apply(MetadataAPIImpl.scala:2864) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:2864) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:4235) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:286) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
ERROR [main] - Failed to download the Jar of the object(com.ligadata.kamanja.samples.models.helloworldmodel111.000000000000000001's dep jar KamanjaInternalDeps_2.11-1.4.0.jar)
com.ligadata.Exceptions.ObjectNotFoundException: Object KamanjaInternalDeps_2.11-1.4.0.jar not found in container jar_store
        at com.ligadata.MetadataAPI.PersistenceUtils$.GetObject(PersistenceUtils.scala:121) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetObject(MetadataAPIImpl.scala:716) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1298) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1290) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.DownloadJarFromDB(MetadataAPIImpl.scala:1290) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.com$ligadata$MetadataAPI$MetadataAPIImpl$$DeserializeAndAddObject(MetadataAPIImpl.scala:2815) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1$$anonfun$apply$4.apply(MetadataAPIImpl.scala:2903) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1$$anonfun$apply$4.apply(MetadataAPIImpl.scala:2896) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.StorageBase.DataStoreOperations$$anonfun$8.apply(StorageAdapterBase.scala:135) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.StorageBase.DataStoreOperations$$anonfun$8.apply(StorageAdapterBase.scala:128) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.keyvaluestore.HBaseAdapter.com$ligadata$keyvaluestore$HBaseAdapter$$processRow(HBaseAdapter.scala:968) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:1027) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.StorageBase.DataStoreOperations$class.get(StorageAdapterBase.scala:139) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:60) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1.apply(MetadataAPIImpl.scala:2896) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1.apply(MetadataAPIImpl.scala:2864) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:2864) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:4235) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:286) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
ERROR [main] - Failed to download the Jar of the object(com.ligadata.kamanja.samples.models.helloworldmodel111.000000000000000001's dep jar ExtDependencyLibs_2.11-1.4.0.jar)
com.ligadata.Exceptions.ObjectNotFoundException: Object ExtDependencyLibs_2.11-1.4.0.jar not found in container jar_store
        at com.ligadata.MetadataAPI.PersistenceUtils$.GetObject(PersistenceUtils.scala:121) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetObject(MetadataAPIImpl.scala:716) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1298) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1290) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.DownloadJarFromDB(MetadataAPIImpl.scala:1290) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.com$ligadata$MetadataAPI$MetadataAPIImpl$$DeserializeAndAddObject(MetadataAPIImpl.scala:2815) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1$$anonfun$apply$4.apply(MetadataAPIImpl.scala:2903) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1$$anonfun$apply$4.apply(MetadataAPIImpl.scala:2896) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.StorageBase.DataStoreOperations$$anonfun$8.apply(StorageAdapterBase.scala:135) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.StorageBase.DataStoreOperations$$anonfun$8.apply(StorageAdapterBase.scala:128) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.keyvaluestore.HBaseAdapter.com$ligadata$keyvaluestore$HBaseAdapter$$processRow(HBaseAdapter.scala:968) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:1027) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.StorageBase.DataStoreOperations$class.get(StorageAdapterBase.scala:139) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:60) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1.apply(MetadataAPIImpl.scala:2896) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1.apply(MetadataAPIImpl.scala:2864) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:2864) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:4235) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:286) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]

.
.
.

**Comment by ligadata-pokuri** [comment]
Ramana, can you mark it as fixed and also list in which version it is fixed

**Comment by ligadata-ramana** [comment]
It was fixed in 1.4.1.

**Comment by ligadata-william** [comment]
@ligadata-haitham have you verified whether this is working or not?

**Comment by ligadata-haitham** [comment]
i installed 1.4.0 binaries, ran the medical app and got results, and when i try to upgrade i get the following error : 
INFO [main] - Jar Absolute Path:/opt/Kamanja-1.4.1/ClusterInstall/ClusterInstallerDriver-1.4.1, ClusterInstallerDriversLocation:/opt/Kamanja-1.4.1/ClusterInstall
Jar Absolute Path:/opt/Kamanja-1.4.1/ClusterInstall/ClusterInstallerDriver-1.4.1, ClusterInstallerDriversLocation:/opt/Kamanja-1.4.1/ClusterInstall
 INFO [main] - Jar Absolute Path:/opt/Kamanja-1.4.1/ClusterInstall/InstallDriver-1.4.1, InstallerDriversLocation:/opt/Kamanja-1.4.1/ClusterInstall
Jar Absolute Path:/opt/Kamanja-1.4.1/ClusterInstall/InstallDriver-1.4.1, InstallerDriversLocation:/opt/Kamanja-1.4.1/ClusterInstall
DEBUG [main] - The installation log file can be found in /tmp/InstallDriver.20160630_170339.log
DEBUG [main] - Given Arguments:Upgrading with clusterId:null, apiConfigPath:/opt/Kamanja-1.4.1/ClusterInstall/ClusterCfgMetadataAPIConfig.properties, nodeConfigPath:/opt/Kamanja-1.4.1/ClusterInstall/ClusterConfig.json, tarballPath:/opt/Kamanja-1.4.1_2.11.tar.gz, fromKamanja:1.4, fromScala:2.11, toScala:2.11, workingDir:/tmp, migrateTemplate:null, logDir:/tmp, toKamanja:1.4, skipPrerequisites:null, preRequisitesCheckOnly:false
ERROR [main] - One or more arguments for your upgrade are not set or have bad values...
One or more arguments for your upgrade are not set or have bad values...
ERROR [main] - 	--fromKamanja <the prior installation version being upgraded... either '1.1' or '1.2'>
	--fromKamanja <the prior installation version being upgraded... either '1.1' or '1.2'>


the COMMAND used : 
java -Dlog4j.configurationFile=file:/opt/Kamanja-1.4.1/ClusterInstall/log4j2.xml -jar /opt/Kamanja-1.4.1/ClusterInstall/ClusterInstallerDriver-1.4.1 --upgrade --apiConfig /opt/Kamanja-1.4.1/ClusterInstall/ClusterCfgMetadataAPIConfig.properties --clusterConfig /opt/Kamanja-1.4.1/ClusterInstall/ClusterConfig.json --tarballPath /opt/Kamanja-1.4.1_2.11.tar.gz --toScala 2.11 --tenantId tenant1 --fromKamanja 1.4 --fromScala 2.11 --adapterMessageBindings ./AdapterBindings.json

**Comment by ligadata-pokuri** [comment]
This is fixed only in 1.5.0. Only migration from 1.4/1.3/1.2 to 1.5 works without any issues. 1.4.0 to 1.4.1 we are not removing the dependency fat jars, which are added to dependency jars in 1.4.0.

**Comment by ligadata-haitham** [comment]
according to ramana , the migration fix for 1.4.0 to 1.4.1 is done in branch (1.4.1.migration) , but was never merged into 1.4.0 .
i can verify that and close this issue soon.

**Comment by ligadata-william** [comment]
Is the change in 1.4.1.migration only or has this been merged into 1.4.1?

**Comment by ligadata-pokuri** [comment]
William, that is not merged to 1.4.1 or 1.4.2. if we give another hot fix
in 1.4.x we merge this. These changes are already in 1.5.0.test. we are not
going to do on this anything in 1.4.x at this moment

**Comment by ligadata-william** [comment]
@ligadata-pokuri is this something we're planning on dealing with? We can either leave it open without a verify label or just close it as will-not-fix.

**Comment by ligadata-ramana** [comment]
When we upgrade at the same patch level, we don't need make any changes to metadata objects(models, containers, messages) or data persisted for containers or messages while data is  flowing through the engine. However, cluster config need to be updated because we rename the fat jars based on kamanja version with each kamanja release.  This issue is addressed in 1.6.0 as part of #1174.  I am closing this issue for now.
