### ISSUE TITLE
KafkaProducer is throwing an exception when setting "Security.protocol" to "SASL_PLAINTEXT" 

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1226]
KafkaProducer is throwing this exception when setting "Security.protocol" to "SASL_PLAINTEXT" 

===> KafkaProducer starting  with sec of SASL_PLAINTEXT...
===> with SASL_PLAINTEXT
ERROR [main] - Failed to instantiate output/status adapter object:com.ligadata.OutputAdapters.KafkaProducer$
java.lang.NullPointerException
	at com.ligadata.OutputAdapters.KafkaProducer.<init>(KafkaProducer.scala:121) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
	at com.ligadata.OutputAdapters.KafkaProducer$.CreateOutputAdapter(KafkaProducer.scala:40) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$.com$ligadata$KamanjaManager$KamanjaMdCfg$$CreateOutputAdapterFromConfig(KamanjaMdCfg.scala:572) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$LoadOutputAdapsForCfg$1.apply(KamanjaMdCfg.scala:614) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$LoadOutputAdapsForCfg$1.apply(KamanjaMdCfg.scala:594) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadOutputAdapsForCfg(KamanjaMdCfg.scala:594) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadAdapters(KamanjaMdCfg.scala:451) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
	at com.ligadata.KamanjaManager.KamanjaManager.initialize(KamanjaManager.scala:588) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
	at com.ligadata.KamanjaManager.KamanjaManager.com$ligadata$KamanjaManager$KamanjaManager$$run(KamanjaManager.scala:716) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
	at com.ligadata.KamanjaManager.KamanjaManager$.main(KamanjaManager.scala:1103) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
	at com.ligadata.KamanjaManager.KamanjaManager.main(KamanjaManager.scala) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
ERROR [main] - Failed to get output adapter for (testfailedevents_1,com.ligadata.kamanja.metadata.AdapterInfo@52172cf3)

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

I need to make sure that the value is not null for this CONFIG option,

By the way

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

ssl.mechanism must be set I believe...

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Hi Saleh.. sorry, I got confused again... I see the SASL.MECHANISM is defalvtable in the PRODUCER client code.. but I didn't check for null...

Its fixed, now

**Comment by ligadata-saleh** [comment]
verified
