### ISSUE TITLE
Failed to instantiate output/status adapter object:com.ligadata.OutputAdapters.KafkaProducer

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1229]
Hi , 

    am getting the error below when i add "Security.protocol": "SASL_PLAINTEXT" and "SASL.KERBEROS.SERVICE.NAME": "kafka" to the adapter json , ca u please take a look .

ERROR [main] - Failed to instantiate output/status adapter object:com.ligadata.OutputAdapters.KafkaProducer$
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:321) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:181) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at com.ligadata.OutputAdapters.KafkaProducer.<init>(KafkaProducer.scala:197) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.OutputAdapters.KafkaProducer$.CreateOutputAdapter(KafkaProducer.scala:40) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$.com$ligadata$KamanjaManager$KamanjaMdCfg$$CreateOutputAdapterFromConfig(KamanjaMdCfg.scala:572) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$LoadOutputAdapsForCfg$1.apply(KamanjaMdCfg.scala:614) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$LoadOutputAdapsForCfg$1.apply(KamanjaMdCfg.scala:594) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadOutputAdapsForCfg(KamanjaMdCfg.scala:594) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadAdapters(KamanjaMdCfg.scala:451) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaManager.initialize(KamanjaManager.scala:588) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaManager.com$ligadata$KamanjaManager$KamanjaManager$$run(KamanjaManager.scala:716) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaManager$.main(KamanjaManager.scala:1103) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaManager.main(KamanjaManager.scala) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
Caused by: org.apache.kafka.common.KafkaException: java.lang.SecurityException: Configuration Error:
        Line 0: expected [{], found [libdefaults]
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:74) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        ... 17 more
Caused by: java.lang.SecurityException: Configuration Error:
        Line 0: expected [{], found [libdefaults]
        at com.sun.security.auth.login.ConfigFile.<init>(ConfigFile.java:110) ~[?:1.7.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_101]
        at java.lang.Class.newInstance(Class.java:383) ~[?:1.7.0_101]
        at javax.security.auth.login.Configuration$2.run(Configuration.java:258) ~[?:1.7.0_101]
        at javax.security.auth.login.Configuration$2.run(Configuration.java:250) ~[?:1.7.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_101]
        at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:249) ~[?:1.7.0_101]
        at org.apache.kafka.common.security.kerberos.Login.login(Login.java:291) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        ... 17 more
Caused by: java.io.IOException: Configuration Error:
        Line 0: expected [{], found [libdefaults]
        at com.sun.security.auth.login.ConfigFile.match(ConfigFile.java:511) ~[?:1.7.0_101]
        at com.sun.security.auth.login.ConfigFile.parseLoginEntry(ConfigFile.java:405) ~[?:1.7.0_101]
        at com.sun.security.auth.login.ConfigFile.readConfig(ConfigFile.java:383) ~[?:1.7.0_101]
        at com.sun.security.auth.login.ConfigFile.init(ConfigFile.java:283) ~[?:1.7.0_101]
        at com.sun.security.auth.login.ConfigFile.init(ConfigFile.java:219) ~[?:1.7.0_101]
        at com.sun.security.auth.login.ConfigFile.<init>(ConfigFile.java:108) ~[?:1.7.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_101]
        at java.lang.Class.newInstance(Class.java:383) ~[?:1.7.0_101]
        at javax.security.auth.login.Configuration$2.run(Configuration.java:258) ~[?:1.7.0_101]
        at javax.security.auth.login.Configuration$2.run(Configuration.java:250) ~[?:1.7.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_101]
        at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:249) ~[?:1.7.0_101]
        at org.apache.kafka.common.security.kerberos.Login.login(Login.java:291) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[ExtDependencyLibs_2.11-1.4.1.jar:1.0]
        ... 17 more
ERROR [main] - Failed to get output adapter for (testfailedevents_1,com.ligadata.kamanja.metadata.AdapterInfo@7b33f19f)

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Investigating.

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Hi Saleh, can you paste the JAAS_FILES that you are using?

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Also, the ClusterConfig
