### ISSUE TITLE
 model for message update  fails 

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1245]
This model exists for this message com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000001 but still can not compile model

kamanja update message ../metadata/message/Message_Definition_HelloWorld.json TENANTID tenant1 PropertiesFile ../../../config/HelloProp.json 
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
 WARN [main] - getting pfile PropertiesFile
Using default configuration /Users/hariramasamy/mykamanja/Kamanja-1.5.0_2.11/config/MetadataAPIConfig.properties
 WARN [main] - ../../../config/HelloProp.json name of propertty file contents {    "description" : "Hello There Howdy \n Hello There Howdy\n Hello There Howdy.",    "comment" : "this is comment",    "tag" : "1n343434",    "a" : "Hello",    "b" : "There"}
 WARN [main] - DATABASE_SCHEMA remains unset
 WARN [main] - DATABASE_LOCATION remains unset
 WARN [main] - DATABASE_HOST remains unset
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main] - DATABASE remains unset
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/hariramasamy/mykamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/hariramasamy/mykamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
ERROR [main] - Node Undefined not found in metadata
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
warning: there were two deprecation warnings; re-run with -deprecation for details
one warning found
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
added manifest
adding: com/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/messages/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/messages/V1000001/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/messages/V1000001/msg1$$anonfun$1.class(in = 1615) (out= 673)(deflated 58%)
adding: com/ligadata/kamanja/samples/messages/V1000001/msg1$$anonfun$getAttributeType$1.class(in = 2002) (out= 932)(deflated 53%)
adding: com/ligadata/kamanja/samples/messages/V1000001/msg1$$typecreator1$1.class(in = 1786) (out= 762)(deflated 57%)
adding: com/ligadata/kamanja/samples/messages/V1000001/msg1$.class(in = 8984) (out= 2975)(deflated 66%)
adding: com/ligadata/kamanja/samples/messages/V1000001/msg1.class(in = 24715) (out= 10110)(deflated 59%)
adding: com/ligadata/kamanja/samples/messages/V1000001/msg1Factory.class(in = 792) (out= 394)(deflated 50%)
adding: msg1.scala(in = 12841) (out= 3069)(deflated 76%)
adding: msg1Factory.java(in = 443) (out= 211)(deflated 52%)
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
warning: there were two deprecation warnings; re-run with -deprecation for details
one warning found
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
added manifest
adding: com/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/messages/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/messages/msg1$$anonfun$1.class(in = 1576) (out= 672)(deflated 57%)
adding: com/ligadata/kamanja/samples/messages/msg1$$anonfun$getAttributeType$1.class(in = 1963) (out= 928)(deflated 52%)
adding: com/ligadata/kamanja/samples/messages/msg1$$typecreator1$1.class(in = 1738) (out= 755)(deflated 56%)
adding: com/ligadata/kamanja/samples/messages/msg1$.class(in = 8873) (out= 2974)(deflated 66%)
adding: com/ligadata/kamanja/samples/messages/msg1.class(in = 24420) (out= 10036)(deflated 58%)
adding: com/ligadata/kamanja/samples/messages/msg1Factory.class(in = 756) (out= 385)(deflated 49%)
adding: msg1_local.scala(in = 12769) (out= 3066)(deflated 75%)
adding: msg1Factory.java(in = 434) (out= 207)(deflated 52%)
 WARN [main] - The model com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000001 is  dependent on the message com.ligadata.kamanja.samples.messages.msg1
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
added manifest
adding: com/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V0/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V0/HelloWorldModel$HelloWorldModelFactory.class(in = 873) (out= 435)(deflated 50%)
adding: com/ligadata/kamanja/samples/models/V0/HelloWorldModel.class(in = 1219) (out= 615)(deflated 49%)
adding: HelloWorldModel.java(in = 2818) (out= 991)(deflated 64%)
adding: tempCode.JAVA(in = 2818) (out= 991)(deflated 64%)
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
added manifest
adding: com/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V1/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V1/HelloWorldModel$HelloWorldModelFactory.class(in = 873) (out= 435)(deflated 50%)
adding: com/ligadata/kamanja/samples/models/V1/HelloWorldModel.class(in = 1219) (out= 614)(deflated 49%)
adding: HelloWorldModel.java(in = 2818) (out= 991)(deflated 64%)
adding: tempCode.JAVA(in = 2818) (out= 991)(deflated 64%)
ERROR [main] - Failed to compile the model definition
java.lang.NullPointerException
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$.getModelMessagesContainers(MessageAndContainerUtils.scala:1868) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$.getContainersFromModelConfig(MessageAndContainerUtils.scala:1607) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.generateModelDef(CompilerProxy.scala:821) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.recompileModelFromSource(CompilerProxy.scala:138) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.RecompileModel(ModelUtils.scala:1031) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.RecompileModel(MetadataAPIImpl.scala:2322) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:503) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:501) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$.UpdateMessage(MessageAndContainerUtils.scala:501) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UpdateMessage(MetadataAPIImpl.scala:2058) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.MessageService$.updateMessage(MessageService.scala:169) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:452) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:349) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
ERROR [main] - COMPILER_PROXY: unable to determine model metadata information during recompile.
com.ligadata.Exceptions.ModelCompilationFailedException
	at com.ligadata.MetadataAPI.CompilerProxy.generateModelDef(CompilerProxy.scala:836) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.recompileModelFromSource(CompilerProxy.scala:138) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.RecompileModel(ModelUtils.scala:1031) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.RecompileModel(MetadataAPIImpl.scala:2322) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:503) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$$anonfun$UpdateMessage$2.apply(MessageAndContainerUtils.scala:501) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$.UpdateMessage(MessageAndContainerUtils.scala:501) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UpdateMessage(MetadataAPIImpl.scala:2058) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.MessageService$.updateMessage(MessageService.scala:169) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:452) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:349) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
Caused by: java.lang.NullPointerException
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$.getModelMessagesContainers(MessageAndContainerUtils.scala:1868) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MessageAndContainerUtils$.getContainersFromModelConfig(MessageAndContainerUtils.scala:1607) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.CompilerProxy.generateModelDef(CompilerProxy.scala:821) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	... 13 more
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.kamanja.samples.messages.msg1.000000000001000001"
  }
}{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "\nRecompileModel",
    "Result Data" : null,
    "Result Description" : "Error in producing scala file or Jar file..Failed to Add Model"
  }
}

**Comment by ligadata-pokuri** [comment]
Hi Hari,

It is not H2DB issue. Looks like it is your issue. Looks to me it is in function getModelMessagesContainers.

**Comment by ligadata-ramana** [comment]
Please verify the fix in 1.5.0.Test
