### ISSUE TITLE
KVInit unable to connect to store when using H2DB

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1246]
When I run InitKVStores_*.sh I get the below error. This was found on branch 1.5.0.646.
```
ERROR [main] - Failed to connect to Datastore.
java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at com.ligadata.kamanja.samples.containers.V1000000.DyspnoeaCodes.<init>(DyspnoeaCodes.scala:118) ~[?:?]
	at com.ligadata.kamanja.samples.containers.V1000000.DyspnoeaCodes.<init>(DyspnoeaCodes.scala:341) ~[?:?]
	at com.ligadata.kamanja.samples.containers.V1000000.DyspnoeaCodes$.createInstance(DyspnoeaCodes.scala:26) ~[?:?]
	at com.ligadata.kamanja.samples.containers.V1000000.DyspnoeaCodes$.createInstance(DyspnoeaCodes.scala:16) ~[?:?]
	at com.ligadata.tools.kvinit.KVInit.getInstance(KVInit.scala:584) ~[kvinit_2.10-1.5.0.jar:1.5.0]
	at com.ligadata.kamanja.serializer.CsvSerDeser.deserialize(CsvSerDeser.scala:366) ~[KamanjaInternalDeps_2.10-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.tools.kvinit.KVInit$$anonfun$com$ligadata$tools$kvinit$KVInit$$buildContainerOrMessage$1$$anonfun$apply$9.apply(KVInit.scala:872) ~[kvinit_2.10-1.5.0.jar:1.5.0]
	at com.ligadata.tools.kvinit.KVInit$$anonfun$com$ligadata$tools$kvinit$KVInit$$buildContainerOrMessage$1$$anonfun$apply$9.apply(KVInit.scala:867) ~[kvinit_2.10-1.5.0.jar:1.5.0]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[ExtDependencyLibs2_2.10-1.5.0.jar:1.0]
	at com.ligadata.tools.kvinit.KVInit$$anonfun$com$ligadata$tools$kvinit$KVInit$$buildContainerOrMessage$1.apply(KVInit.scala:867) ~[kvinit_2.10-1.5.0.jar:1.5.0]
	at com.ligadata.tools.kvinit.KVInit$$anonfun$com$ligadata$tools$kvinit$KVInit$$buildContainerOrMessage$1.apply(KVInit.scala:860) ~[kvinit_2.10-1.5.0.jar:1.5.0]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[ExtDependencyLibs2_2.10-1.5.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108) ~[ExtDependencyLibs2_2.10-1.5.0.jar:1.0]
	at com.ligadata.tools.kvinit.KVInit.com$ligadata$tools$kvinit$KVInit$$buildContainerOrMessage(KVInit.scala:860) ~[kvinit_2.10-1.5.0.jar:1.5.0]
	at com.ligadata.tools.kvinit.KVInit$.main(KVInit.scala:243) [kvinit_2.10-1.5.0.jar:1.5.0]
	at com.ligadata.tools.kvinit.KVInit.main(KVInit.scala) [kvinit_2.10-1.5.0.jar:1.5.0]
```

**Comment by ligadata-pokuri** [comment]
William.

99.99% you are using 2.10 version of binaries and 2.11 version of scala to compile messages (which is in MetadataAPIConfig.Properties file). Can you check that and let us know?

**Comment by ligadata-william** [comment]
I’ll check.

**Comment by ligadata-william** [comment]
This was, as @ligadata-pokuri said, due to the fact that kamanja was compiled in 2.10 but I had 2.11 installed in my system when I compiled metadata. After switching scala to 2.10, everything worked fine. Closing.
