### ISSUE TITLE
kafka kerberos new pull throwing null pointer exception 

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1250]
===> KafkaConsumer starting 
ERROR [main] - Failed to instantiate input adapter object:com.ligadata.InputAdapters.KamanjaKafkaConsumer$
java.lang.NullPointerException
        at com.ligadata.InputAdapters.KamanjaKafkaConsumer.<init>(KamanjaKafkaConsumer.scala:97) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.InputAdapters.KamanjaKafkaConsumer$.CreateInputAdapter(KamanjaKafkaConsumer.scala:37) ~[KamanjaInternalDeps_2.11-1.4.1.jar:0.1-SNAPSHOT]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$.com$ligadata$KamanjaManager$KamanjaMdCfg$$CreateInputAdapterFromConfig(KamanjaMdCfg.scala:687) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$PrepInputAdapsForCfg$1.apply(KamanjaMdCfg.scala:734) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$PrepInputAdapsForCfg$1.apply(KamanjaMdCfg.scala:713) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.4.1.jar:1.0]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$.PrepInputAdapsForCfg(KamanjaMdCfg.scala:713) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadInputAdapsForCfg(KamanjaMdCfg.scala:750) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadAdapters(KamanjaMdCfg.scala:462) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaManager.initialize(KamanjaManager.scala:588) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaManager.com$ligadata$KamanjaManager$KamanjaManager$$run(KamanjaManager.scala:716) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaManager$.main(KamanjaManager.scala:1103) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
        at com.ligadata.KamanjaManager.KamanjaManager.main(KamanjaManager.scala) [kamanjamanager_2.11-1.4.1.jar:1.4.1]
 WARN [kafka-kerberos-refresh-thread] - TGT renewal thread has been interrupted and will exit.

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Hi, please verify

**Comment by ligadata-saleh** [comment]
verified
