### ISSUE TITLE
SSL H2DB Error

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1258]
When using SSL, upload cluster config gave the following error

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/hariramasamy/mykamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/hariramasamy/mykamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
ERROR [main] - Message:Cannot create PoolableConnectionFactory (Connection is broken: "javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?: localhost:9100" [90067-192])
java.sql.SQLException: Cannot create PoolableConnectionFactory (Connection is broken: "javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?: localhost:9100" [90067-192])
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2291) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2038) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at com.ligadata.keyvaluestore.H2dbAdapter.getConnection(H2dbAdapter.scala:353) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.H2dbAdapter.IsSchemaExists(H2dbAdapter.scala:370) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.H2dbAdapter.<init>(H2dbAdapter.scala:324) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.H2dbAdapter$.CreateStorageAdapter(H2dbAdapter.scala:1706) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.KeyValueManager$.Get(KeyValueManager.scala:77) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.PersistenceUtils$.GetDataStoreHandle(PersistenceUtils.scala:779) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.PersistenceUtils$.OpenDbStore(PersistenceUtils.scala:797) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1627) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:4270) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:339) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?: localhost:9100" [90067-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at org.h2.message.DbException.get(DbException.java:168) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:452) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:329) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]

**Comment by ligadatahari** [comment]
The problem happened since the h2db server was not started in ssl mode
We need a script to start H2 db server in either ssl or tcp mode

**Comment by ligadata-haitham** [comment]
StartH2dbServer.sh was updated to enable starting the server in two modes : SSL and TCP.
