### ISSUE TITLE
PushSampleDataToKafka_XXXXXXX script is not working fine 

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1259]
[root@node01 bin]#  ../input/SampleApplications/bin/PushSampleDataToKafka_HelloWorld.sh node01.internal:9092
Using java.security.auth.login.config=/var/run/cloudera-scm-agent/process/101-kafka-KAFKA_BROKER/jaas-client.conf
Using java.security.krb5.confg=/etc/krb5.conf
Using security client = KAMANJA_SECURITY_CLIENT
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/kamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/kamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "pool-1-thread-1" org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:321)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:181)
        at com.ligadata.tools.SimpleKafkaProducer$$anonfun$main$7$$anon$2.run(SimpleKafkaProducer.scala:636)
        at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060)
        at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode.
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:74)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode.
        at org.apache.kafka.common.security.kerberos.Login.login(Login.java:289)
        at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104)
        at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44)
        at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55)
        ... 8 more
Done. ElapsedTime:313.17ms

============================

**- but it works fine when i put the env variables manually**  

java -Djava.security.krb5.confg=/etc/krb5.conf -Djava.security.auth.login.config=/var/run/cloudera-scm-agent/process/101-kafka-KAFKA_BROKER/jaas-client.conf  -cp $KAMANJA_HOME/lib/system/ExtDependencyLibs2_2.11-1.5.0.jar:$KAMANJA_HOME/lib/system/ExtDependencyLibs_2.11-1.5.0.jar:$KAMANJA_HOME/lib/system/KamanjaInternalDeps_2.11-1.5.0.jar:$KAMANJA_HOME/lib/system/simplekafkaproducer_2.11-1.5.0.jar com.ligadata.tools.SimpleKafkaProducer --gz true --topics "helloworldinput" --threads 1 --topicpartitions 8 --brokerlist "node01.internal:9092" --files "$KAMANJA_HOME/input/SampleApplications/data/Input_Data_HelloWorld.csv.gz" --partitionkeyidxs "0" --format CSV --secprops $KAMANJA_SECURITY_CLIENT

**Comment by ligadata-saleh** [comment]
a quick clarification i echo the java command and the "java.security.auth.login.config" is not added at all  

java -Djava.security.krb5.confg=/etc/krb5.conf -cp /opt/kamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.5.0.jar:/opt/kamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs_2.11-1.5.0.jar:/opt/kamanja/Kamanja-1.5.0_2.11/lib/system/KamanjaInternalDeps_2.11-1.5.0.jar:/opt/kamanja/Kamanja-1.5.0_2.11/lib/system/simplekafkaproducer_2.11-1.5.0.jar com.ligadata.tools.SimpleKafkaProducer --gz true --topics helloworldinput --threads 1 --topicpartitions 8 --brokerlist node01.internal:9092 --files /opt/kamanja/Kamanja-1.5.0_2.11/input/SampleApplications/data/Input_Data_HelloWorld.csv.gz --partitionkeyidxs 0 --format CSV --secprops /var/run/cloudera-scm-agent/process/101-kafka-KAFKA_BROKER/producer.properties

**Comment by ligadata-dan** [comment]
@ligadata-saleh 
Hi saleh,

Are you trying to connect to broker v0.9 or v0.8?

**Comment by ligadata-saleh** [comment]
the script is not adding the $KERBEROS_CONFIG_OPT to the java command , i print the command its always empty

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Hi saleh, I fixed  it. please verify

**Comment by ligadata-saleh** [comment]
verified
