### ISSUE TITLE
bin/ApplicationMetadata.sh exits when Enter key pressed. Only exit when 'Exit' option selected.

### ISSUE THREAD

**Issue by edifecs-pradeep** [LigaData/Kamanja#126]
Enter your choice:   
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.parseInt(Integer.java:527)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
	at scala.Console$.readInt(Console.scala:351)
	at scala.Predef$.readInt(Predef.scala:296)
	at com.ligadata.MetadataAPI.TestMetadataAPI$.StartTest(TestMetadataAPI.scala:1821)
	at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:1881)
	at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)

**Comment by ligadata-william** [comment]
No longer valid. Menu interface will no longer be supported. Closing.
