### ISSUE TITLE
Failed to start MetadataAPIservice  akka.actor.InvalidActorNameException: actor name [metadata-api-service] is not unique!

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1272]
Failed to start MetadataAPIservice in 1.5.0.Test branch 

> ERROR [main] - Exception:
akka.actor.InvalidActorNameException: actor name [metadata-api-service] is not unique!
        at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:130) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
        at akka.actor.dungeon.Children$class.reserveChild(Children.scala:76) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
        at akka.actor.ActorCell.reserveChild(ActorCell.scala:369) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
        at akka.actor.dungeon.Children$class.makeChild(Children.scala:201) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
        at akka.actor.dungeon.Children$class.attachChild(Children.scala:41) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
        at akka.actor.ActorCell.attachChild(ActorCell.scala:369) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
        at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:553) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
        at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:230) [metadataapiservice_2.11-1.5.0.jar:1.5.0]
        at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:288) [metadataapiservice_2.11-1.5.0.jar:1.5.0]
        at com.ligadata.metadataapiservice.APIService.main(APIService.scala) [metadataapiservice_2.11-1.5.0.jar:1.5.0]
 WARN [main] - Shutting down
DEBUG [main] - Closing datastore
 INFO [main] - close the connection pool
DEBUG [main] - main datastore closed
DEBUG [main] - Closing datastore
DEBUG [main] - Closing zookeeper session ..
DEBUG [metadata-api-service-akka.actor.default-dispatcher-6] - Initialize Leader Latch
DEBUG [main] - Closed zookeeper session ..

**Comment by ligadatahari** [comment]
Fixed the issue 
Ahmed, please verify it.

THanks

**Comment by ligadata-william** [comment]
I've verified this. Closing.
