### ISSUE TITLE
Engine always processing from beginning of kafka topic when ever we restarted

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#1273]
Engine always processing from beginning of kafka topic when ever we restarted

**Comment by ligadata-dan** [comment]
@ligadata-pokuri 

Fixed.

**Comment by ligadata-william** [comment]
@ligadata-dan is this is 1.5.0.Test already or another branch?

**Comment by ligadata-william** [comment]
This still occurs in 1.5.0.Test

**Comment by ligadata-william** [comment]
Clarification of my earlier statement. If a message is properly executed, it is not executed when the engine restarts, however, if a message causes the below exception, restarting the engine causes it to re-process those messages.
```
ERROR [pool-17-thread-1] - Failed to Deserialize/Execute. MessageName: at UK:{"Version":1,"Type":"Kafka","Name":"testin_1","TopicName":"testin_1","PartitionId":0}, UV:{"Version":1,"Offset":599}
com.ligadata.Exceptions.KamanjaException: Not found any bindings to deserialize (including default serializer)
	at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:584) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.InputAdapters.KamanjaKafkaConsumer.deserialize(KamanjaKafkaConsumer.scala:48) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:309) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:41) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
	at com.ligadata.InputAdapters.KamanjaKafkaConsumer$$anonfun$StartProcessing$4$$anon$1.run(KamanjaKafkaConsumer.scala:364) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.5.0.jar:1.0]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.5.0.jar:1.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by ligadata-william** [comment]
Opened #1278 regarding my previous comment and closing this issue as verified.
