### ISSUE TITLE
kafka kerberos sasl_ssl unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1276]
Hi , 
we need to add "-Djavax.net.ssl.trustStore=/etc/security/tls/kafka.server.truststore.jks" to the all java commands that connect to kafka using sasl_ssl listener otherwise am getting this error : 

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:1.8.0_91]
 at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:1.8.0_91]
 at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[?:1.8.0_91]
 at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[?:1.8.0_91]
 at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[?:1.8.0_91]
 at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_91]
 at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_91]
 at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) ~[?:1.8.0_91]
 at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:1.8.0_91]
 at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496) ~[?:1.8.0_91]
 at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_91]
 at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_91]
 at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[?:1.8.0_91]
 at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[?:1.8.0_91]
 at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
 at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[?:1.8.0_91]
 at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:335) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
 at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:413) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
 at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:269) ~[ExtDependencyLibs_2.11-1.5.0.jar:1.0]
 ... 6 more
DEBUG [kafka-producer-network-thread | testfailedevents_1_253613492] - Node -1 disconnected.

**Comment by ligadata-pokuri** [comment]
Hi Saleh,

I Added KAMANJA_KEYSTORE, KAMANJA_KEYSTORE_PASS, KAMANJA_TRUSTSTORE & KAMANJA_TRUSTSTORE_PASS options to scripts to pass Keystore, Keystore password, Truststore & Trust store Password. 

Can you use them and try once?

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Documentation has been updated

**Comment by ligadata-saleh** [comment]
verified , works fine now
