### ISSUE TITLE
If a message causes an exception in Kamanja, upon restart, it will get processed again

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1278]
As the title states, when a message is processed by Kamanja and the below exception is thrown, upon restarting Kamanja, it will reprocess the same offsets in Kafka.
```
ERROR [pool-17-thread-1] - Failed to Deserialize/Execute. MessageName: at UK:{"Version":1,"Type":"Kafka","Name":"testin_1","TopicName":"testin_1","PartitionId":0}, UV:{"Version":1,"Offset":599}
com.ligadata.Exceptions.KamanjaException: Not found any bindings to deserialize (including default serializer)
    at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:584) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
    at com.ligadata.InputAdapters.KamanjaKafkaConsumer.deserialize(KamanjaKafkaConsumer.scala:48) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
    at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:309) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
    at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:41) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
    at com.ligadata.InputAdapters.KamanjaKafkaConsumer$$anonfun$StartProcessing$4$$anon$1.run(KamanjaKafkaConsumer.scala:364) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
    at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.5.0.jar:1.0]
    at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.5.0.jar:1.0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by ligadata-dan** [comment]
@ligadata-pokuri 
As per our discussion

**Comment by ligadata-pokuri** [comment]
We will fix this in next version. This will reprocess the messages which are failed to deserialize. I think it can move to P2
