### ISSUE TITLE
Kamanja unable to instantiate Storage output adapter when using hbase

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1282]
When I start Kamanja, I receive the following exception:
```
ERROR [main] - Failed to get output adapter for (storage_1,com.ligadata.kamanja.metadata.AdapterInfo@5887af38)
java.lang.NullPointerException
	at com.ligadata.StorageBase.DataStore$class.externalizeExceptionEvent(StorageAdapterBase.scala:274) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.externalizeExceptionEvent(HBaseAdapter.scala:60) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.CreateNameSpace(HBaseAdapter.scala:168) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter.<init>(HBaseAdapter.scala:258) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.HBaseAdapter$.CreateStorageAdapter(HBaseAdapter.scala:2036) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.keyvaluestore.KeyValueManager$.Get(KeyValueManager.scala:68) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$.com$ligadata$KamanjaManager$KamanjaMdCfg$$CreateStorageAdapterFromConfig(KamanjaMdCfg.scala:489) ~[kamanjamanager_2.11-1.5.0.jar:1.5.0]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$LoadStorageAdapsForCfg$1.apply(KamanjaMdCfg.scala:496) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$LoadStorageAdapsForCfg$1.apply(KamanjaMdCfg.scala:494) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadStorageAdapsForCfg(KamanjaMdCfg.scala:494) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadAdapters(KamanjaMdCfg.scala:442) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
	at com.ligadata.KamanjaManager.KamanjaManager.initialize(KamanjaManager.scala:620) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
	at com.ligadata.KamanjaManager.KamanjaManager.com$ligadata$KamanjaManager$KamanjaManager$$run(KamanjaManager.scala:753) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
	at com.ligadata.KamanjaManager.KamanjaManager$.main(KamanjaManager.scala:1183) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
	at com.ligadata.KamanjaManager.KamanjaManager.main(KamanjaManager.scala) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
```
I am using the following adapter configuration:
```
"Adapters": [
	{
          "Name": "Storage_1",
          "TypeString": "Storage",
          "TenantId": "tenant1",
          "StoreType": "hbase",
          "SchemaName": "tenant1_storage_1",
          "Location": "node01"
        },
...
```

**Comment by ligadata-dan** [comment]
Ok, I fixed it, please verify.

The issue is we can get an expected exception prior to KamanjaExceptionEvent being loaded. The NPE is actually trying to get an instance of that object.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
