### ISSUE TITLE
RESTAPI throws Exception without sending any result to the caller

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1298]
I am getting the following exception when running this command :

curl -X DELETE -k https://localhost:8081/api/config/ligadata1

and never got any result on the caller side . 

DEBUG [metadata-api-service-akka.actor.default-dispatcher-4] - DELETE reqeust : api/config/ligadata1
[ERROR] [07/06/2016 02:02:57.592] [metadata-api-service-akka.actor.default-dispatcher-4] [akka://metadata-api-service/user/metadata-api-service/$a] Unrecognized token 'ligadata1': was expecting ('true', 'false' or 'null')
 at [Source: ligadata1; line: 1, column: 19]
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'ligadata1': was expecting ('true', 'false' or 'null')
 at [Source: ligadata1; line: 1, column: 19]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2462)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1621)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
        at org.json4s.jackson.JsonMethods$class.parse(JsonMethods.scala:19)
        at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:44)
        at com.ligadata.metadataapiservice.RemoveEngineConfigService.process(RemoveEngineConfigService.scala:59)
        at com.ligadata.metadataapiservice.RemoveEngineConfigService$$anonfun$receive$1.applyOrElse(RemoveEngineConfigService.scala:50)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at com.ligadata.metadataapiservice.RemoveEngineConfigService.aroundReceive(RemoveEngineConfigService.scala:36)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ligadata-william** [comment]
This is still an issue on branch 1.5.0.Test. Please indicate the branch you've checked in the fix for.

**Comment by ligadatahari** [comment]
I am catching exception, meaningful can be deferred later

**Comment by ligadata-william** [comment]
I've verified that a Result is being returned to the client. Closing.
