### ISSUE TITLE
Null pointer exception when removing ClusterConfig through RESTAPI

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1301]
Steps to reproduce :

1. start MetadataAPI Services
2. run the folling command 
curl -X PUT --data-binary  @"ClusterConfig.json"  -k  https://localhost:8081/api/RemoveConfig

DEBUG [metadata-api-service-akka.actor.default-dispatcher-15] - PUT reqeust : api/RemoveConfig
[ERROR] [07/06/2016 19:12:08.462] [metadata-api-service-akka.actor.default-dispatcher-15] [akka://metadata-api-service/user/metadata-api-service/$d] null
java.lang.NullPointerException
        at com.ligadata.metadataapiservice.RemoveEngineConfigService.process(RemoveEngineConfigService.scala:61)
        at com.ligadata.metadataapiservice.RemoveEngineConfigService$$anonfun$receive$1.applyOrElse(RemoveEngineConfigService.scala:50)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at com.ligadata.metadataapiservice.RemoveEngineConfigService.aroundReceive(RemoveEngineConfigService.scala:36)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ligadata-william** [comment]
This is still an issue in 1.5.0.Test. Please indicate which branch you checked the fix into.

**Comment by ligadata-william** [comment]
I was on the wrong branch before. However, there are a couple issues still that should be seen to here. The APIResult returns as:
```
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "RemoveEngineConfigService",
    "Result Data" : null,
    "Result Description" : "java.lang.NullPointerException"
  }
}
```
Which leaves the user confused as to why this isn't working, we need a more detailed Result Description.

The other issue is that there is no logging of the error on the service side, so if an issue occurs, an administrator can't investigate what's going on.

**Comment by ligadata-william** [comment]
I'm closing this as the lack of an APIResult has been resolved. However, what I would consider a much more pressing issue, #1311, needs to be addressed. Cluster Config removal is still failing and the user is left without a reason why.
