### ISSUE TITLE
remove engine config fails if I pass the clusterConfig.json

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1302]
command $KAMANJA_HOME/bin/kamanja remove engine config $KAMANJA_HOME/config/ClusterConfig.json

it failed with this exception :
java.lang.ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to scala.collection.immutable.Map
        at com.ligadata.MetadataAPI.ConfigUtils$$anonfun$UploadModelsConfig$1.apply(ConfigUtils.scala:630) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.ConfigUtils$$anonfun$UploadModelsConfig$1.apply(ConfigUtils.scala:628) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at com.ligadata.MetadataAPI.ConfigUtils$.UploadModelsConfig(ConfigUtils.scala:628) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.UploadModelsConfig(MetadataAPIImpl.scala:3973) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.Utility.ConfigService$.removeEngineConfig(ConfigService.scala:173) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:665) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:354) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "UploadModelsConfig",
    "Result Data" : null,
    "Result Description" : "Error :java.lang.ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to scala.collection.immutable.MapFailed to upload config:{\n

**Comment by ligadata-william** [comment]
I've verified this is fixed. Closing.
