### ISSUE TITLE
Failure to Add Model + Null Pointer Exception when loading PMML models into Kamanja 1.5

### ISSUE THREAD

**Issue by ligadata-shilpa** [LigaData/Kamanja#1323]
I was running Kamanja 1.5 (latest version from the website) and ran into the following error while uploading the model:

**Stack Trace attched below:**

.
.
.
DEBUG [main] - Trying to load class:scala.runtime.package, resolve:false
DEBUG [main] - Metadata synching is now available.
DEBUG [main] - We may create a default output message depending on whether they are supplied in ModelConfig object ..
DEBUG [main] -
java.lang.NullPointerException
	at com.ligadata.MetadataAPI.JpmmlSupport$$anonfun$9.apply(JpmmlSupport.scala:170) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.JpmmlSupport$$anonfun$9.apply(JpmmlSupport.scala:169) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at com.ligadata.MetadataAPI.JpmmlSupport.CreateModel(JpmmlSupport.scala:169) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.AddPMMLModel(ModelUtils.scala:605) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.ModelUtils$.AddModel(ModelUtils.scala:518) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddModel(MetadataAPIImpl.scala:2308) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.Utility.ModelService$.addModelPmml(ModelService.scala:308) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:490) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:354) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Error : java.lang.NullPointerException + Failed to Add Model"
  }
}
DEBUG [main] - Closing datastore
 INFO [main] - close the connection pool
DEBUG [main] - main datastore closed

**Metadata Files:**
[HMEQ_Files.zip](https://github.com/LigaData/Kamanja/files/362537/HMEQ_Files.zip)

On checking the source code, it was observed that the code is failing at the part where it's trying to extract the list of DataFields and convert them to an Array. 
Source code link:
https://github.com/LigaData/Kamanja/blob/dev/trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/JpmmlSupport.scala 

Code Snippet:

` /** get the concrete data fields for either 'target' or 'predicted' ... type info found there. */`
`
                                    val targetDataFields: scala.Array[DataField] = {`
                                      `  targetFieldNames.asScala.map(nm => {`
                                           ` modelEvaluator.getDataField(nm)`
                                       ` })`
                                  `  }.toArray`

**Comment by ligadata-greg** [comment]
Hari,

I checked the PMML specification for the XML definition for the OutputField.  See the link and section of text below.
http://dmg.org/pmml/v4-2-1/Output.html

<xs:element name="OutputField">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Extension" minOccurs="0" maxOccurs="unbounded"/>
      <xs:sequence minOccurs="0" maxOccurs="1">
        <xs:element ref="Decisions" minOccurs="0" maxOccurs="1"/>
        <xs:group ref="EXPRESSION" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:sequence>
    <xs:attribute name="name" type="FIELD-NAME" use="required"/>
    <xs:attribute name="displayName" type="xs:string"/>
    <xs:attribute name="optype" type="OPTYPE"/>
    <xs:attribute name="dataType" type="DATATYPE"/>
    <xs:attribute name="targetField" type="FIELD-NAME"/>
    <xs:attribute name="feature" type="RESULT-FEATURE" default="predictedValue"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="ruleFeature" type="RULE-FEATURE" default="consequent"/>
    <xs:attribute name="algorithm" default="exclusiveRecommendation">

In the OutputField element, the "dataType" is not listed as required (the way the "name" field is required), and it is not listed with a default value, the way there are default values for "feature" or "ruleFeature" have default values.  We basically have a whole in the spec, which I will report.  

RECOMMENDED FIX:
* treat "dataType" as <not required> (Kamanja should NOT through an error)
* give a default value if dataType is missing to "xs:string"  (basically, the string data type for this OS).  Why choose this default?  This is the most frequent and general output type used for output fields.

**Comment by ligadata-pokuri** [comment]
Hi Greg & Shilpa,

That is mistake from our usage. We are just Logging the Key & Type for all output & target fields. We are not checking whether type exists or not before we do operations on that field. That is simple fix and you will get that fix in 1.5.1.

**Comment by ligadata-shilpa** [comment]
Pulled and verified branch 1.5.1.1323. Models got uploaded and output was obtained successfully.
Sample output file attached. Sample Model used was Linear Regression.
[HMEQ_Kscored_R_RegrLin.json.zip](https://github.com/LigaData/Kamanja/files/370294/HMEQ_Kscored_R_RegrLin.json.zip)
