### ISSUE TITLE
OrientDB connection failure

### ISSUE THREAD

**Issue by ligadata-yousef** [LigaData/Kamanja#1324]
Hi Pokuri,

i tried with Saleh to run QueryGenerator tool but each time we faced same error:

Jul 17, 2016 11:31:06 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=857MB (heap=928MB os=3,833MB disk=34,843MB)
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.core.Orient
  at com.orientechnologies.orient.core.config.OGlobalConfiguration$1.change(OGlobalConfiguration.java:103)
    at com.orientechnologies.orient.core.config.OGlobalConfiguration.setValue(OGlobalConfiguration.java:835)
    at com.orientechnologies.orient.core.config.OGlobalConfiguration.autoConfigDiskCacheSize(OGlobalConfiguration.java:795)
    at com.orientechnologies.orient.core.config.OGlobalConfiguration.autoConfig(OGlobalConfiguration.java:760)
    at com.orientechnologies.orient.core.config.OGlobalConfiguration.<clinit>(OGlobalConfiguration.java:663)
    at com.orientechnologies.orient.jdbc.OrientJdbcConnection.<init>(OrientJdbcConnection.java:72)
    at com.orientechnologies.orient.jdbc.OrientJdbcDriver.connect(OrientJdbcDriver.java:59)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:208)
    at com.ligadata.queryutility.QueryBuilder.getDBConnection(QueryBuilder.scala:75)
    at com.ligadata.queryutility.QueryGenerator$.main(QueryGenerator.scala:139)
    at com.ligadata.queryutility.QueryGenerator.main(QueryGenerator.scala)

note: we try with more than one jar for orient JDBC.

**Comment by ligadata-pokuri** [comment]
Hi @ligadata-yousef , 

it is saying it does not find the class. Looks like you are missing jar file in the path. We can take a look at it tomorrow morning or your time.

**Comment by ligadata-yousef** [comment]
Hi @ligadata-pokuri we use those JAR:

1- Orientdb-jdbc-2.1.19-all.jar
2- Orientdb-jdbc-2.2.3-all.jar
3- Orientdb-client-2.1.19.jar && Orientdb-core-2.1.19.jar.

**Comment by ligadata-yousef** [comment]
verified.
