### ISSUE TITLE
NullPointerException when running StartKamanjaCluster.sh script 

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1325]
Exception in thread "main" java.lang.NullPointerException
        at com.ligadata.installer.NodeInfoExtract$.writeNodeIdConfigs(NodeInfoExtract.scala:209)
        at com.ligadata.installer.NodeInfoExtract$.main(NodeInfoExtract.scala:169)
        at com.ligadata.installer.NodeInfoExtract.main(NodeInfoExtract.scala)

Problem: Invalid arguments supplied to the NodeInfoExtract-1.0 application... unable to obtain node configuration... exiting.

**Comment by ligadata-ahmad** [comment]
closing this as verified
