### ISSUE TITLE
SmartFileAdapter Failed to connect to HDFS with hadoop High availability enabled

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1326]
exception while connecting to HDFS :

To solve the issue we need to pass more parameter like : 
dfs.nameservices
dfs.ha.namenodes.EXAMPLENAMESERVICE
dfs.namenode.rpc-address
hadoop.rpc.protection
dfs.client.failover.proxy.provider

```
java.lang.IllegalArgumentException: java.net.UnknownHostException: <MyHostName>
  at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:2675) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:418) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:426) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at com.ligadata.InputAdapters.hdfs.HdfsFileHandler.<init>(HdfsChangesMonitor.scala:52) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.InputAdapters.SmartFileHandlerFactory$.createSmartFileHandler(MonitorUtils.scala:102) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.InputAdapters.MonitorController$$anonfun$checkConfigDirsAccessibility$1.apply(MonitorController.scala:49) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.InputAdapters.MonitorController$$anonfun$checkConfigDirsAccessibility$1.apply(MonitorController.scala:48) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at com.ligadata.InputAdapters.MonitorController.checkConfigDirsAccessibility(MonitorController.scala:48) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.InputAdapters.SmartFileConsumer.initializeNode(SmartFileConsumer.scala:203) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.InputAdapters.SmartFileConsumer.StartProcessing(SmartFileConsumer.scala:1255) ~[KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.KamanjaManager.KamanjaLeader$$anonfun$StartNodeKeysMap$1.apply(KamanjaLeader.scala:585) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
        at com.ligadata.KamanjaManager.KamanjaLeader$$anonfun$StartNodeKeysMap$1.apply(KamanjaLeader.scala:554) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at com.ligadata.KamanjaManager.KamanjaLeader$.StartNodeKeysMap(KamanjaLeader.scala:554) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
        at com.ligadata.KamanjaManager.KamanjaLeader$.liftedTree3$1(KamanjaLeader.scala:821) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
        at com.ligadata.KamanjaManager.KamanjaLeader$.ActionOnAdaptersDistImpl(KamanjaLeader.scala:672) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
        at com.ligadata.KamanjaManager.KamanjaLeader$.com$ligadata$KamanjaManager$KamanjaLeader$$ActionOnAdaptersDistribution(KamanjaLeader.scala:871) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
        at com.ligadata.KamanjaManager.KamanjaLeader$$anonfun$Init$2.apply(KamanjaLeader.scala:1294) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
        at com.ligadata.KamanjaManager.KamanjaLeader$$anonfun$Init$2.apply(KamanjaLeader.scala:1294) [kamanjamanager_2.11-1.5.0.jar:1.5.0]
        at com.ligadata.ZooKeeper.ZooKeeperListener.com$ligadata$ZooKeeper$ZooKeeperListener$$ProcessData(ZooKeeperListener.scala:54) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at com.ligadata.ZooKeeper.ZooKeeperListener$$anon$1.nodeChanged(ZooKeeperListener.scala:72) [KamanjaInternalDeps_2.11-1.5.0.jar:0.1-SNAPSHOT]
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:294) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:288) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:92) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:286) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:253) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:54) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:112) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:728) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:505) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:254) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:561) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) [ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
Caused by: java.net.UnknownHostException: <MyHostName>
```

**Comment by ligadata-ahmad** [comment]
Hi Yasser the fix is in this branch https://github.com/LigaData/Kamanja/tree/SmartFileAdapterToSupportHAHadoop

**Comment by ligadata-yasser** [comment]
Made tests to make sure functionality is still working with old configs.
everything looks fine

**Comment by ligadata-ahmad** [comment]
closing this as verified by Yasser and my self
