### ISSUE TITLE
When pushing HelloWorld data in JSON format using SimpleKafkaProducer, get NullPointerException if incorrect casing for field given

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1331]
This is was observed on branch 1.4.3

I attempted to push data into kafka 0.8.2.2 with SimpleKafkaProducer using the following command:
```
java -cp $KAMANJA_HOME/lib/system/ExtDependencyLibs2_2.11-1.4.3.jar:$KAMANJA_HOME/lib/system/ExtDependencyLibs_2.11-1.4.3.jar:$KAMANJA_HOME/lib/system/KamanjaInternalDeps_2.11-1.4.3.jar:$KAMANJA_HOME/lib/system/simplekafkaproducer_2.11-1.4.3.jar com.ligadata.tools.SimpleKafkaProducer --gz false --topics "helloworldinput" --threads 1 --topicpartitions 8 --brokerlist "localhost:9092" --files "$KAMANJA_HOME/input/SampleApplications/data/Input_Data_HelloWorld_tagged.json" --partitionkeyidxs "com.ligadata.kamanja.samples.messages.msg1:id" --format JSON
```
If I change 'id' to 'Id' (Note the capitalized 'I'), it works as expected. If I replace it with a non-existent field (such as 'blah'), it also manages to push the data (albeit in a non-partitioned way). See error below as well as attached Adapter bindings configuration and data:
```
840 [WARN] AppInfo$: Can't read Kafka version from MANIFEST.MF. Possible cause: java.lang.NullPointerException
951 [ERROR] SimpleKafkaProducer$: Error reading from a file
java.lang.ClassCastException: scala.math.BigInt cannot be cast to java.lang.String
	at com.ligadata.tools.SimpleKafkaProducer$$anonfun$processJsonDoc$2.apply(SimpleKafkaProducer.scala:382) ~[simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.tools.SimpleKafkaProducer$$anonfun$processJsonDoc$2.apply(SimpleKafkaProducer.scala:381) ~[simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at com.ligadata.tools.SimpleKafkaProducer$.processJsonDoc(SimpleKafkaProducer.scala:381) ~[simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.tools.SimpleKafkaProducer$.processJsonFile(SimpleKafkaProducer.scala:319) ~[simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.tools.SimpleKafkaProducer$.ProcessFile(SimpleKafkaProducer.scala:175) [simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.tools.SimpleKafkaProducer$$anonfun$main$7$$anon$2$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(SimpleKafkaProducer.scala:611) [simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.tools.SimpleKafkaProducer$$anonfun$main$7$$anon$2$$anonfun$run$1$$anonfun$apply$1.apply(SimpleKafkaProducer.scala:611) [simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.tools.SimpleKafkaProducer$$anonfun$main$7$$anon$2$$anonfun$run$1$$anonfun$apply$1.apply(SimpleKafkaProducer.scala:611) [simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.tools.SimpleKafkaProducer$.com$ligadata$tools$SimpleKafkaProducer$$elapsed(SimpleKafkaProducer.scala:406) [simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.tools.SimpleKafkaProducer$$anonfun$main$7$$anon$2$$anonfun$run$1.apply(SimpleKafkaProducer.scala:611) [simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.tools.SimpleKafkaProducer$$anonfun$main$7$$anon$2$$anonfun$run$1.apply(SimpleKafkaProducer.scala:607) [simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at com.ligadata.tools.SimpleKafkaProducer$$anonfun$main$7$$anon$2.run(SimpleKafkaProducer.scala:607) [simplekafkaproducer_2.11-1.4.3.jar:1.4.3]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.4.3.jar:1.0]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.4.3.jar:1.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
00. File:/private/tmp/Kamanja/Kamanja-1.4.3_2.11/input/SampleApplications/data/Input_Data_HelloWorld_tagged.json ElapsedTime:114.47ms
Done. ElapsedTime:191.35ms
```

[Input_Data_HelloWorld_Tagged.json.txt](https://github.com/LigaData/Kamanja/files/370429/Input_Data_HelloWorld_Tagged.json.txt)

[HelloWorld_Adapter_Binding.json.txt](https://github.com/LigaData/Kamanja/files/370430/HelloWorld_Adapter_Binding.json.txt)

**Comment by ligadata-dan** [comment]
@ligadata-william 

So looks like we default to NULL if we don't find and "id" (which then produces a non-partitioned output). So, everything but the "id" actually works... But then we specify the correct id, we are passing an BigInt in the file looks like.

{"com.ligadata.kamanja.samples.messages.msg1" : {"id":13,"name":"Palestine","score":2}}

Looks like we expect Strings only in the key values, so we attempt to cast the 13 into a string. ("13" will probably work)...

**Comment by ligadata-pokuri** [comment]
Dan,

At any cost we should never get any NULL pointer exceptions. And in this case "id":13, if you make .toString in scala most of the base types will return string values. Please take a look at the Null pointer exception.

**Comment by ligadata-dan** [comment]
@ligadata-william 

Do we need to add a new parameter to the Took API to take in the Key Type?

What is the story for this?  Do we want to fix it in 1.6 or 1.7?  I assume we don't want to push it into 1.5.1.

**Comment by ligadata-dan** [comment]
@ligadata-pokuri 

Do you mean this:
840 [WARN] AppInfo$: Can't read Kafka version from MANIFEST.MF. Possible cause: java.lang.NullPointerException

**Comment by ligadata-dan** [comment]
@ligadata-pokuri 

What causes an outage here is a ClassCastException.

**Comment by ligadata-pokuri** [comment]
@ligadata-william , is it null pointer exception or casting exception?

**Comment by ligadata-william** [comment]
Looks like it's actually a casting exception. The NullPointerException is just a warning that seems to occur whether the push is successful or not.

**Comment by ligadata-dan** [comment]
https://github.com/LigaData/Kamanja/pull/1341

Please verify

**Comment by ligadata-william** [comment]
Verified and closing.
