### ISSUE TITLE
Json Ser/deser doesn't properly convert data passed in as an integer to its expected type, double

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1339]
I get the below error when pushing in data in JSON format with 0 passed in for a data field that is of type Double.

```
Caused by: com.ligadata.Exceptions.KamanjaException: Failed to deserialize JSON:{"com.ligadata.kamanja.samples.messages.Beneficiary":{"Desynpuf_Id":"000002F7E0A96C32","Bene_Birth_Dt":19440701,"Bene_Death_Dt":0,"Bene_Sex_Ident_Cd":2,"Bene_Race_Cd":2,"Bene_Esrd_Ind":0,"Sp_State_Code":5,"Bene_County_Cd":400,"Bene_Hi_Cvrage_Tot_Mons":0,"Bene_Smi_Cvrage_Tot_Mons":0,"Bene_Hmo_Cvrage_Tot_Mons":0,"Plan_Cvrg_Mos_Num":0,"Sp_Alzhdmta":2,"Sp_Chf":2,"Sp_Chrnkidn":2,"Sp_Cncr":2,"Sp_Copd":2,"Sp_Depressn":2,"Sp_Diabetes":2,"Sp_Ischmcht":2,"Sp_Osteoprs":2,"Sp_Ra_Oa":2,"Sp_Strketia":2,"Medreimb_Ip":0,"Benres_Ip":0,"Pppymt_Ip":0,"Medreimb_Op":0,"Benres_Op":0,"Pppymt_Op":0,"Medreimb_Car":0,"Benres_Car":0.0,"Pppymt_Car":0}}
	at com.ligadata.kamanja.serializer.JSONSerDes.deserialize(JsonSerDeser.scala:427) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:596) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	... 15 more
Caused by: java.lang.Exception: Value is the not the correct type for field pppymt_op in message Beneficiary
	at com.ligadata.kamanja.samples.messages.V1000000.Beneficiary.set(Beneficiary.scala:573) ~[?:?]
	at com.ligadata.kamanja.samples.messages.V1000000.Beneficiary.set(Beneficiary.scala:414) ~[?:?]
	at com.ligadata.kamanja.serializer.JSONSerDes$$anonfun$com$ligadata$kamanja$serializer$JSONSerDes$$deserializeContainerFromJsonMap$1.apply(JsonSerDeser.scala:489) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.kamanja.serializer.JSONSerDes$$anonfun$com$ligadata$kamanja$serializer$JSONSerDes$$deserializeContainerFromJsonMap$1.apply(JsonSerDeser.scala:459) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221) ~[ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428) ~[ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at com.ligadata.kamanja.serializer.JSONSerDes.com$ligadata$kamanja$serializer$JSONSerDes$$deserializeContainerFromJsonMap(JsonSerDeser.scala:459) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.kamanja.serializer.JSONSerDes.deserialize(JsonSerDeser.scala:411) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:596) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	... 15 more
```

**Comment by ligadata-pokuri** [comment]
@ligadata-tulasi , we need to accept the following, if scala is accepting. Need to see whether we can fix it for 1.5.1 or later.

int, long, float => double. 
int, long => float
int => long

**Comment by ligadata-pokuri** [comment]
Fixed in branch 1.5.1.HierarichalMigrateIssue and merged into 1.5.1

**Comment by ligadata-pokuri** [comment]
@ligadata-william , can you verify this?

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
