### ISSUE TITLE
When pushing data in JSON format, Strings not passed in with quotation marks (") cause exception

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1340]
See error below when I send data in for a field defined as string but not encapsulated in quotation marks. These should be handled and converted to strings. This was observed in 1.4.3.
```
ERROR [pool-24-thread-1] - Failed to Deserialize/Execute. MessageName: at UK:{"Version":1,"Type":"Kafka","Name":"medicalinput","TopicName":"medicalinput","PartitionId":0}, UV:{"Version":1,"Offset":129}
com.ligadata.Exceptions.KamanjaException: Failed to Deserialize
	at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:602) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.InputAdapters.KafkaSimpleConsumer.deserialize(KafkaSimpleConsumer.scala:60) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:304) [KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:41) [kamanjamanager_2.11-1.4.3.jar:1.4.3]
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(KafkaSimpleConsumer.scala:408) [KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at scala.util.control.Breaks.breakable(Breaks.scala:38) [ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:382) [KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:378) [KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) [ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:32) [ExtDependencyLibs_2.11-1.4.3.jar:1.0]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) [ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at kafka.message.MessageSet.foreach(MessageSet.scala:67) [ExtDependencyLibs_2.11-1.4.3.jar:1.0]
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1.run(KafkaSimpleConsumer.scala:378) [KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.4.3.jar:1.0]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.4.3.jar:1.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: com.ligadata.Exceptions.KamanjaException: Failed to deserialize JSON:{"com.ligadata.kamanja.samples.messages.HL7":{"Desynpuf_Id":"000002F7E0A96C32","Clm_Id":737133358637027,"Clm_From_Dt":20150308,"Clm_Thru_Dt":20150308,"Bene_Birth_Dt":19230901,"Bene_Death_Dt":0,"Bene_Sex_Ident_Cd":2,"Bene_Race_Cd":2,"Bene_Esrd_Ind":0,"Sp_State_Code":10,"Bene_County_Cd":260,"Bene_Hi_Cvrage_Tot_Mons":12,"Bene_Smi_Cvrage_Tot_Mons":12,"Bene_Hmo_Cvrage_Tot_Mons":0,"Plan_Cvrg_Mos_Num":0,"Sp_Alzhdmta":1,"Sp_Chf":1,"Sp_Chrnkidn":1,"Sp_Cncr":1,"Sp_Copd":2,"Sp_Depressn":1,"Sp_Diabetes":1,"Sp_Ischmcht":1,"Sp_Osteoprs":1,"Sp_Ra_Oa":2,"Sp_Strketia":1,"Age":86,"Infectious_Parasitic_Diseases":7,"Neoplasms":4,"Endocrine_Nutritional_Metabolic_Diseases_Immunity_Disorders":19,"Diseases_Blood_Blood_Forming_Organs":12,"Mental_Disorders":11,"Diseases_Nervous_System_Sense_Organs":9,"Diseases_Circulatory_System":63,"Diseases_Respiratory_System":14,"Diseases_Digestive_System":11,"Diseases_Genitourinary_System":17,"Complications_Of_Pregnancy_Childbirth_The_Puerperium":0,"Diseases_Skin_Subcutaneous_Tissue":10,"Diseases_Musculoskeletal_System_Connective_Tissue":23,"Congenital_Anomalies":1,"Certain_Conditions_Originating_In_The_Perinatal_Period":0,"Symptoms_Signs_Ill_Defined_Conditions":34,"Injury_Poisoning":10,"Factors_Influencing_Health_Status_Contact_With_Health_Services":31,"External_Causes_Of_Injury_Poisoning":1,"Hypothyroidism":1,"Infarction":0,"Alzheimer":0,"Alzheimer_Related":4,"Anemia":0,"Asthma":0,"Atrial_Fibrillation":0,"Hyperplasia":2,"Cataract":2,"Kidney_Disease":8,"Pulmonary_Disease":0,"Depression":3,"Diabetes":9,"Glaucoma":0,"Heart_Failure":13,"Hip_Pelvic_Fracture":1,"Hyperlipidemia":5,"Hypertension":16,"Ischemic_Heart_Disease":18,"Osteoporosis":2,"Ra_Oa":2,"Stroke":4,"Breast_Cancer":1,"Colorectal_Cancer":0,"Prostate_Cancer":0,"Lung_Cancer":0,"Endometrial_Cancer":0,"Tobacco":0,"Height":173,"Weight":75.7,"Systolic":159.6,"Diastolic":57.6,"Totalcholesterol":172.3,"Ldl":161.7,"Triglycerides":153.2,"Shortnessofbreath":0,"Chestpain":0,"AATDeficiency":1,"ChronicCough":0,"ChronicSputum":0}}
	at com.ligadata.kamanja.serializer.JSONSerDes.deserialize(JsonSerDeser.scala:427) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:596) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	... 15 more
Caused by: java.lang.Exception: Value is the not the correct type for field chestpain in message HL7
	at com.ligadata.kamanja.samples.messages.V1000000.HL7.set(HL7.scala:1060) ~[com.ligadata.kamanja.samples.messages_HL7_1000000_1468890148885.jar:?]
	at com.ligadata.kamanja.samples.messages.V1000000.HL7.set(HL7.scala:631) ~[com.ligadata.kamanja.samples.messages_HL7_1000000_1468890148885.jar:?]
	at com.ligadata.kamanja.serializer.JSONSerDes$$anonfun$com$ligadata$kamanja$serializer$JSONSerDes$$deserializeContainerFromJsonMap$1.apply(JsonSerDeser.scala:489) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.kamanja.serializer.JSONSerDes$$anonfun$com$ligadata$kamanja$serializer$JSONSerDes$$deserializeContainerFromJsonMap$1.apply(JsonSerDeser.scala:459) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221) ~[ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428) ~[ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428) ~[ExtDependencyLibs2_2.11-1.4.3.jar:1.0]
	at com.ligadata.kamanja.serializer.JSONSerDes.com$ligadata$kamanja$serializer$JSONSerDes$$deserializeContainerFromJsonMap(JsonSerDeser.scala:459) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.kamanja.serializer.JSONSerDes.deserialize(JsonSerDeser.scala:411) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:596) ~[KamanjaInternalDeps_2.11-1.4.3.jar:0.1-SNAPSHOT]
	... 15 more
```

**Comment by ligadata-tulasi** [comment]
The issue is fixed in 1.5.2 release. If the input field data is numeric for type String then there is no need for quotes,  if it is alpha numeric then the value should be in quotes.

**Comment by ligadata-tulasi** [comment]
Please Verify

**Comment by ligadata-william** [comment]
verified as fixed.
