### ISSUE TITLE
Exception is thrown (com.jcraft.jsch.SftpException: No such file ) after starting the engine immediately.

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1385]
Exception is thrown (com.jcraft.jsch.SftpException: No such file ) after starting the engine immediately.

Even that the file was already processed by the engine earlier successfully  

process to reproduce : 

1. start the engine with inputadapter configured to read form sftp server 
2. copy a file into input dir
3. stop the engine after it complete processing  the file
4. start the engine again 
 
> ERROR [main-EventThread] - Error while getting file attrs for file /incoming/kamanjadev/in/20160718.abc_abc_abc.899
> com.jcraft.jsch.SftpException: No such file
>         at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2846) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at com.jcraft.jsch.ChannelSftp._lstat(ChannelSftp.java:2309) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at com.jcraft.jsch.ChannelSftp.lstat(ChannelSftp.java:2285) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.InputAdapters.sftp.SftpFileHandler.getRemoteFileAttrs(SftpChangesMonitor.scala:371) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.InputAdapters.sftp.SftpFileHandler.exists(SftpChangesMonitor.scala:327) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.InputAdapters.SmartFileConsumer$$anonfun$handleStartInfo$2$$anonfun$apply$1.apply(SmartFileConsumer.scala:355) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.InputAdapters.SmartFileConsumer$$anonfun$handleStartInfo$2$$anonfun$apply$1.apply(SmartFileConsumer.scala:349) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at scala.collection.immutable.List.foreach(List.scala:381) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.InputAdapters.SmartFileConsumer$$anonfun$handleStartInfo$2.apply(SmartFileConsumer.scala:349) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.InputAdapters.SmartFileConsumer$$anonfun$handleStartInfo$2.apply(SmartFileConsumer.scala:349) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at scala.collection.mutable.HashMap.foreach(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.InputAdapters.SmartFileConsumer.handleStartInfo(SmartFileConsumer.scala:349) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.InputAdapters.SmartFileConsumer.StartProcessing(SmartFileConsumer.scala:1506) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.KamanjaManager.KamanjaLeader$$anonfun$StartNodeKeysMap$1.apply(KamanjaLeader.scala:585) [kamanjamanager_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.KamanjaManager.KamanjaLeader$$anonfun$StartNodeKeysMap$1.apply(KamanjaLeader.scala:554) [kamanjamanager_2.11-1.5.2.jar:1.5.2]
>         at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.KamanjaManager.KamanjaLeader$.StartNodeKeysMap(KamanjaLeader.scala:554) [kamanjamanager_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.KamanjaManager.KamanjaLeader$.liftedTree3$1(KamanjaLeader.scala:821) [kamanjamanager_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.KamanjaManager.KamanjaLeader$.ActionOnAdaptersDistImpl(KamanjaLeader.scala:672) [kamanjamanager_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.KamanjaManager.KamanjaLeader$.com$ligadata$KamanjaManager$KamanjaLeader$$ActionOnAdaptersDistribution(KamanjaLeader.scala:871) [kamanjamanager_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.KamanjaManager.KamanjaLeader$$anonfun$Init$2.apply(KamanjaLeader.scala:1294) [kamanjamanager_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.KamanjaManager.KamanjaLeader$$anonfun$Init$2.apply(KamanjaLeader.scala:1294) [kamanjamanager_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.ZooKeeper.ZooKeeperListener.com$ligadata$ZooKeeper$ZooKeeperListener$$ProcessData(ZooKeeperListener.scala:54) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at com.ligadata.ZooKeeper.ZooKeeperListener$$anon$1.nodeChanged(ZooKeeperListener.scala:72) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:294) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:288) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:92) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:286) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:253) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:54) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:112) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:728) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:505) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:254) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:561) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>         at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) [ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
>

**Comment by ligadata-pokuri** [comment]
Ahmed, did it process anything after that or just stopped?

**Comment by ligadata-ahmad** [comment]
It processed the next file normally .

**Comment by ligadata-yasser** [comment]
This is the same issue caused by engine sending last processed file from previous engine running.
