### ISSUE TITLE
JTM model fails to compile with %{COMMONAPACHELOG} grok match

### ISSUE THREAD

**Issue by ligadata-sridhar** [LigaData/Kamanja#1417]
This is happening in flareJTMFixes branch.

JTM has the transformation defined as below:

  "transformations": {
    "archiveprocessing": {
      "dependsOn": [ ["m1"] ],
      "computes": {  
      },
      "grok match": {
        "m1.data": "%{COMMONAPACHELOG}"
      },
      "outputs": {
        "o1": {
          "where":"$clientip != null && !$clientip.equals(\"testip\")",
          "mapping": {
            "data": "${m1.data}"
          }
        }       
      }        
    }

ERROR [main] - Failed to compile the jtm model definition
java.lang.Exception: Where condition not evaluated. transformation: archiveprocessing@o1
	at com.ligadata.jtm.Compiler.Generate(Compiler.scala:938) ~[KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.jtm.Compiler$$anonfun$Execute$10$$anonfun$apply$16$$anonfun$61.apply(Compiler.scala:1181) ~[KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.jtm.Compiler$$anonfun$Execute$10$$anonfun$apply$16$$anonfun$61.apply(Compiler.scala:1165) ~[KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.jtm.Compiler$$anonfun$Execute$10$$anonfun$apply$16.apply(Compiler.scala:1165) ~[KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.jtm.Compiler$$anonfun$Execute$10$$anonfun$apply$16.apply(Compiler.scala:1099) ~[KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.jtm.Compiler$$anonfun$Execute$10.apply(Compiler.scala:1099) ~[KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.jtm.Compiler$$anonfun$Execute$10.apply(Compiler.scala:1094) ~[KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116) ~[ExtDependencyLibs2_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.jtm.Compiler.Execute(Compiler.scala:1094) ~[KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.MetadataAPI.CompilerProxy.compileJTM(CompilerProxy.scala:265) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.MetadataAPI.ModelUtils$.AddJTMModel(ModelUtils.scala:1102) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.MetadataAPI.ModelUtils$.AddModel(ModelUtils.scala:501) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddModel(MetadataAPIImpl.scala:2312) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.MetadataAPI.Utility.ModelService$.addModelJTM(ModelService.scala:456) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:492) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:364) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.5.2.jar:1.5.2]

**Comment by ligadata-joerg** [comment]
Please provide the complete JTM. JTM compiler is right - clientip is not provided in the snipped.
