### ISSUE TITLE
No info and handling for tenantid as user choice

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1419]
1. There is no information about what we are selecting when no command line tenant id given.
2. If choice is out of bound, it is not handled. It gives an exception and APIResult is not related to the error.

[1]System

Enter your choice(If more than 1 choice, please use commas to seperate them):
2
 WARN [main] -
java.lang.ArrayIndexOutOfBoundsException: 1
       	at com.ligadata.MetadataAPI.Utility.MessageService$.getUserInputFromMainMenu(MessageService.scala:324) ~[KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.Utility.MessageService$.getTenantId(MessageService.scala:313) ~[KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.Utility.MessageService$.updateMessage(MessageService.scala:132) ~[KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:460) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:354) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "StartMetadataAPI/route",
    "Result Data" : null,
    "Result Description" : "Unexpected action! action = updatemessage"
  }
}

**Comment by ligadata-dhaval** [comment]
Solution will be a part of the branch github1036

**Comment by ligadata-dhaval** [comment]
This is for all metadata taking user input for tenantid

**Comment by ligadata-dhaval** [comment]
Created a pull request #1423

**Comment by ligadata-william** [comment]
This is fixed but I won't close it until #1036 is fixed since they share a pull request.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
