### ISSUE TITLE
Jar upload missing location gives unhandled exception before the APIresult

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1420]
ERROR [main] - Failed to download the Jar of the object(com.ligadata.kamanja.samples.messages.msg1.000000000001000000's dep jar )
java.lang.NullPointerException
       	at java.io.File.<init>(File.java:277) ~[?:1.7.0_79]
       	at com.ligadata.MetadataAPI.MetadataAPIImpl$.DownloadJarFromDB(MetadataAPIImpl.scala:1310) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.MetadataAPIImpl$.com$ligadata$MetadataAPI$MetadataAPIImpl$$DeserializeAndAddObject(MetadataAPIImpl.scala:2851) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1$$anonfun$apply$4.apply(MetadataAPIImpl.scala:2939) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1$$anonfun$apply$4.apply(MetadataAPIImpl.scala:2932) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.StorageBase.DataStoreOperations$$anonfun$8.apply(StorageAdapterBase.scala:132) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.StorageBase.DataStoreOperations$$anonfun$8.apply(StorageAdapterBase.scala:125) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.keyvaluestore.H2dbAdapter.com$ligadata$keyvaluestore$H2dbAdapter$$getData(H2dbAdapter.scala:980) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.keyvaluestore.H2dbAdapter.get(H2dbAdapter.scala:1005) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.StorageBase.DataStoreOperations$class.get(StorageAdapterBase.scala:136) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.keyvaluestore.H2dbAdapter.get(H2dbAdapter.scala:59) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1.apply(MetadataAPIImpl.scala:2932) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$1.apply(MetadataAPIImpl.scala:2900) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
       	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:2900) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:4272) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:344) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
       	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "uploadJar",
    "Result Data" : null,
    "Result Description" : "JAR_TARGET_DIR property missing in the metadata API configuration"
  }
}

**Comment by ligadata-dhaval** [comment]
Change will be a part of branch github1036
