### ISSUE TITLE
Cluster installed Kamanja fails to run due to missing Python config

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1449]
Python config is not added in the Cluster configs. Due to this the nodes on the cluster do not have it. Due to this the messages are not getting added in the datastore due to a null pointer exception:
com.ligadata.MetadataAPI.MetadataAPIGlobalLogger$ [main] - DEBUG -
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:459) ~[?:1.8.0_101]
        at java.util.Properties.setProperty(Properties.java:166) ~[?:1.8.0_101]
        at com.ligadata.MetadataAPI.ConfigUtils$.RefreshApiConfigForGivenNode(ConfigUtils.scala:1408) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:2888) [KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:4299) [KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:349) [KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
        at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]

**Comment by ligadatahari** [comment]
Fixed

**Comment by ligadata-dhaval** [comment]
Verified for a single instance of Kamanja. Need to verify for Cluster Install.

**Comment by ligadata-dhaval** [comment]
Verifed with cluster install as well.
