### ISSUE TITLE
Kamanja Engine fails to start due to classpath error related to loaninput

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1456]
Kamanja engine fails to start due to classpath issue:
  ERROR [main] - Failed to load Validate/Input Adapter loaninput with class com.ligadata.InputAdapters.KamanjaKafkaConsumer$
java.lang.ClassNotFoundException: com.ligadata.InputAdapters.KamanjaKafkaConsumer$
              at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
              at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
              at com.ligadata.Utils.KamanjaClassLoader.loadClass(ClassLoaderInfo.scala:55) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
              at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
              at com.ligadata.Utils.KamanjaClassLoader.loadClass(ClassLoaderInfo.scala:49) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
              at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
              at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
              at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_101]
              at com.ligadata.KamanjaManager.KamanjaMdCfg$.com$ligadata$KamanjaManager$KamanjaMdCfg$$CreateInputAdapterFromConfig(KamanjaMdCfg.scala:656) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
              at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$PrepInputAdapsForCfg$1.apply(KamanjaMdCfg.scala:735) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
              at com.ligadata.KamanjaManager.KamanjaMdCfg$$anonfun$PrepInputAdapsForCfg$1.apply(KamanjaMdCfg.scala:714) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
              at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
              at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
              at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230) [ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
              at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) [ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
              at scala.collection.mutable.HashMap.foreach(HashMap.scala:99) [ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
              at com.ligadata.KamanjaManager.KamanjaMdCfg$.PrepInputAdapsForCfg(KamanjaMdCfg.scala:714) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
              at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadInputAdapsForCfg(KamanjaMdCfg.scala:751) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
              at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadAdapters(KamanjaMdCfg.scala:463) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
              at com.ligadata.KamanjaManager.KamanjaManager.initialize(KamanjaManager.scala:760) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
              at com.ligadata.KamanjaManager.KamanjaManager.com$ligadata$KamanjaManager$KamanjaManager$$run(KamanjaManager.scala:895) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
              at com.ligadata.KamanjaManager.KamanjaManager$.main(KamanjaManager.scala:1325) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
              at com.ligadata.KamanjaManager.KamanjaManager.main(KamanjaManager.scala) [kamanjamanager_2.11-1.6.0.jar:1.6.0]

**Comment by ligadatahari** [comment]
fixed

**Comment by ligadata-dhaval** [comment]
Verified and closing.
