### ISSUE TITLE
Python not found condition not handled

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1458]
Kamanja is looking for Python at a default location and when not found it gives the error:
ERROR [pool-19-thread-8] - Failed to execute message
java.io.IOException: Cannot run program "/usr/local/bin/python": error=2, No such file or directory
       	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_101]
       	at com.ligadata.python.PyProcess.run(PyProcess.scala:98) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.python.PyProcess.initPyProcess(PyProcess.scala:137) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.python.PyServerConnection.startServer(PyServerConnection.scala:188) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.python.PyServerConnection.initialize(PyServerConnection.scala:100) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.python.PythonAdapter.createConnection(PythonFactoryOfModelInstanceFactory.scala:650) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.python.PythonAdapter.getServerConnection(PythonFactoryOfModelInstanceFactory.scala:292) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.python.PythonAdapter.init(PythonFactoryOfModelInstanceFactory.scala:227) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.KamanjaManager.LearningEngine.execute(LearningEngine.scala:121) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.KamanjaManager.ExecContextImpl.executeMessage(ExecContext.scala:174) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:283) [KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:42) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:328) [KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:42) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
       	at com.ligadata.kafkaInputOutputAdapters_v10.KamanjaKafkaConsumer$$anonfun$StartProcessing$4$$anon$1.run(KamanjaKafkaConsumer.scala:380) [kamanjakafkaadapters_0_10_2.11-1.6.0.jar:1.6.0]
       	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.6.0.jar:1.6.0]
       	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.6.0.jar:1.6.0]
       	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.io.IOException: error=2, No such file or directory
       	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_101]
       	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) ~[?:1.8.0_101]
       	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_101]
       	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_101]
       	... 17 more

**Comment by ligadatahari** [comment]
fixed
