### ISSUE TITLE
Running a GET query for /Connection causes an error

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1464]
If I run a simple get on the server such as:
```
curl http://localhost:8080
```
returns expected results
```
{
  "Endpoints":[
    "ArchiveFile",
    "AuditLog",
    "Connection",
    "Filter",
    "Parser",
    "Pipeline",
    "Policy",
    "Schedule",
    "Status",
    "Tag",
    "TagAssociation",
    "TaggedData"
  ]
}
```

However, when I attempt to run
```
curl http://localhost:8080/Connection
```
The client get a simple, non-specific error:
```
There was an internal server error.
```
while on the server there is the following exception:
```
[ERROR] [10/01/2016 11:38:18.679] [datamgt-actor-system-akka.actor.default-dispatcher-23] [akka://datamgt-actor-system/user/datamgt-http-service] Error during processing of request HttpRequest(GET,http://localhost:8080/Connection,List(Host: localhost:8080, User-Agent: curl/7.47.1),Empty,HTTP/1.1)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror2.jinvokeraw(JavaMirrors.scala:383)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jinvoke(JavaMirrors.scala:339)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror.apply(JavaMirrors.scala:355)
	at com.enterprise.datamanagement.api.RestApiService$$anonfun$5$$anonfun$apply$4$$anonfun$apply$5.apply(RestApi.scala:73)
	at com.enterprise.datamanagement.api.RestApiService$$anonfun$5$$anonfun$apply$4$$anonfun$apply$5.apply(RestApi.scala:72)
	at spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:49)
	at spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:48)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
	at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
	at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	at spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
	at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	at spray.routing.RequestContext.reject(RequestContext.scala:202)
	at spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:35)
	at spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:34)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
	at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
	at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	at spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
	at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	at spray.routing.RequestContext.reject(RequestContext.scala:202)
	at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63)
	at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
	at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
	at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	at spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
	at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	at spray.routing.RequestContext.reject(RequestContext.scala:202)
	at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63)
	at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
	at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
	at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	at spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
	at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	at spray.routing.RequestContext.reject(RequestContext.scala:202)
	at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63)
	at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:35)
	at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:33)
	at spray.routing.HttpServiceBase$class.runSealedRoute$1(HttpService.scala:36)
	at spray.routing.HttpServiceBase$$anonfun$runRoute$1.applyOrElse(HttpService.scala:46)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at com.enterprise.datamanagement.api.RestApiServiceActor.aroundReceive(RestApi.scala:28)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.100.0.56}{node01/10.100.0.56:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:582)
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$$anonfun$apply$1.apply(SearchDsl.scala:41)
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$$anonfun$apply$1.apply(SearchDsl.scala:41)
	at com.sksamuel.elastic4s.Executable$class.injectFutureAndMap(Executable.scala:21)
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$.injectFutureAndMap(SearchDsl.scala:38)
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$.apply(SearchDsl.scala:41)
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$.apply(SearchDsl.scala:38)
	at com.sksamuel.elastic4s.ElasticClient.execute(ElasticClient.scala:24)
	at com.enterprise.datamanagement.storage.ElasticsearchStorage.count(ElasticsearchStorage.scala:52)
	at com.enterprise.datamanagement.entities.CRUD$class.count(CRUD.scala:43)
	at com.enterprise.datamanagement.entities.Connection$.count(Connection.scala:8)
	... 124 more
```

The root error appears to be a NoNodeException regarding elasticsearch.

**Comment by ligadata-william** [comment]
This is on the wrong repository. I'm going to close this and re-open on the correct repository.
