### ISSUE TITLE
Kamanja start ehcache.EhcacheInit services found warning.

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1470]
I am getting this warning while running the engine. This is not affecting my output but is it that we are not caching the data?

WARN [main] -
net.sf.ehcache.CacheException: java.lang.AssertionError: No net.sf.ehcache.EhcacheInit services found
	at net.sf.ehcache.LibraryInit.init(LibraryInit.java:55) ~[ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
	at net.sf.ehcache.CacheManager.init(CacheManager.java:366) ~[ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
	at net.sf.ehcache.CacheManager.<init>(CacheManager.java:259) ~[ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
	at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:1037) ~[ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
	at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:1013) ~[ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
	at net.sf.ehcache.CacheManager.create(CacheManager.java:998) ~[ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
	at com.ligadata.cache.MemoryDataCacheImp.init(MemoryDataCacheImp.scala:26) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.CreateCacheListener(SimpleEnvContextImpl.scala:1819) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.startCache(SimpleEnvContextImpl.scala:2138) ~[KamanjaInternalDeps_2.11-1.6.0.jar:1.6.0]
	at com.ligadata.KamanjaManager.KamanjaMdCfg$.LoadEnvCtxt(KamanjaMdCfg.scala:274) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
	at com.ligadata.KamanjaManager.KamanjaManager.initialize(KamanjaManager.scala:731) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
	at com.ligadata.KamanjaManager.KamanjaManager.com$ligadata$KamanjaManager$KamanjaManager$$run(KamanjaManager.scala:895) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
	at com.ligadata.KamanjaManager.KamanjaManager$.main(KamanjaManager.scala:1325) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
	at com.ligadata.KamanjaManager.KamanjaManager.main(KamanjaManager.scala) [kamanjamanager_2.11-1.6.0.jar:1.6.0]
Caused by: java.lang.AssertionError: No net.sf.ehcache.EhcacheInit services found
	at net.sf.ehcache.LibraryInit.initService(LibraryInit.java:78) ~[ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
	at net.sf.ehcache.LibraryInit.init(LibraryInit.java:50) ~[ExtDependencyLibs2_2.11-1.6.0.jar:1.6.0]
	... 13 more

**Comment by ligadata-william** [comment]
I looked into this last night and this morning. I noticed when assembling the fat jar, ehcache-core-2.6.11.jar was getting resolved, which probably has a different interface. I believe adding a dependencyOverride for 2.6.5 will fix this issue but I don't know what component is referencing ehcache-core-2.6.11.jar or how it will affect things.

I'll add a dependencyOverride and see what happens.

**Comment by ligadata-william** [comment]
Adding the dependencyOverride didn't change anything. Inspection of assembly logs shows the following line:
```
[warn] Merging 'META-INF/services/net.sf.ehcache.EhcacheInit' with strategy 'discard'
```
This may be an issue.

**Comment by ligadata-william** [comment]
At the bottom of ExtDependencyLibs2 there was a second, smaller, assemblyMergeStrategy defined:
```
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}
```
This was causing anything under a META-INF to be discarded out of hand. This is completely unnecessary as a merge strategy is already defined in this build.sbt. After removing, EHCache starts properly.

**Comment by ligadata-william** [comment]
Pull request #1471 has been created to resolve this issue.

**Comment by ligadata-william** [comment]
@ligadata-dhaval @ligadata-pokuri Please verify this fix in branch Issue1470.

**Comment by ligadata-dhaval** [comment]
I am not getting any error while running kamanja. But now I am not getting any output. Reverifying this behaviour on a VM.

**Comment by ligadata-dhaval** [comment]
Its working. It was the kafka version issue. Verified and working.

**Comment by ligadata-dhaval** [comment]
Closing this issue.
