### ISSUE TITLE
Elasticsearch Output Adapter can't connect to clusters when clusterName != elasticsearch

### ISSUE THREAD

**Issue by ligadata-mjalajel** [LigaData/Kamanja#1478]
[Affected Branch: `Berkley_1.5.3-adapterChanges` | Latest Commit: `48b39b6c` ]

Elasticsearch Output Adapter can't connect to clusters when clusterName != elasticsearch

In ElasticsearchOutputAdapter (class com.ligadata.ElasticsearchInputOutputAdapters.ElasticsearchProducer$), option `Adapters.AdapterSpecificCfg.clusterName` is not respected. Setting it to any value other than `elasticsearch` is currently ignored and the output adapter can't connect

When connecting to a cluster named other than `elasticsearch`, the following error is logged:

    
    INFO [pool-16-thread-1] - [Peepers] modules [], plugins [], sites []
    WARN [pool-16-thread-1] - [Peepers] node {#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
    ERROR [pool-16-thread-1] - Failed to save an object in the table myindex:
    org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]

**Comment by ligadata-haitham** [comment]
issue is fixed in branch Berkley_1.5.3-adapterChanges .
i tested on my local machine and its working now.

**Comment by ligadata-mjalajel** [comment]
Verified.. closing.
