### ISSUE TITLE
If MetadataAPIService has DaaS configuration, kamanja start webservice fails

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1556]
If you add a line to MetadataAPIConfig.properties like this:
```
DaasConfig={"requestTopic": {"kafkaHost": "localhost:9092", "topicName": "testin_1"}, "responseTopic": {"kafkaHost": "localhost:9092", "topicName": "testout_1", "numberOfThreads": "1"}, "inputTopic": {"kafkaHost": "localhost:9092", "topicName": "inputtopic"}}
```
It will fail to start with the following error:
```
WARN [main] - Error connecting to kafka:
java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/KafkaProducer
	at com.ligadata.dataaccessapi.KafkaRequestSender.connect(KafkaRequestSender.scala:59) ~[metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaRequestSender.liftedTree1$1(KafkaRequestSender.scala:33) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaRequestSender.start(KafkaRequestSender.scala:32) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaDataAccessAdapter.start(KafkaDataAccessAdapter.scala:56) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaDataAccessAdapter$.Init(KafkaDataAccessAdapter.scala:18) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:207) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:279) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.metadataapiservice.APIService.main(APIService.scala) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.KafkaProducer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	... 8 more
ERROR [main] - Throwable:
java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/KafkaProducer
	at com.ligadata.dataaccessapi.KafkaRequestSender.connect(KafkaRequestSender.scala:59) ~[metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaRequestSender.liftedTree1$1(KafkaRequestSender.scala:33) ~[metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaRequestSender.start(KafkaRequestSender.scala:32) ~[metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaDataAccessAdapter.start(KafkaDataAccessAdapter.scala:56) ~[metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaDataAccessAdapter$.Init(KafkaDataAccessAdapter.scala:18) ~[metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:207) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:279) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.metadataapiservice.APIService.main(APIService.scala) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.KafkaProducer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	... 8 more
 WARN [main] - Shutting down
```

The workaround for this is to manually edit $KAMANJA_HOME/bin/kamanja and add kafka-clients-0.9.0.1.jar to the command that starts the APIService. To make it easy, replace line 83 with:
```
java -Dlog4j.configurationFile=file:$KAMANJA_HOME/config/log4j2.xml -cp $KAMANJA_HOME/lib/system/ExtDependencyLibs2_2.11-1.5.3.jar:$KAMANJA_HOME/lib/system/ExtDependencyLibs_2.11-1.5.3.jar:$KAMANJA_HOME/lib/system/KamanjaInternalDeps_2.11-1.5.3.jar:$KAMANJA_HOME/lib/system/metadataapiservice_2.11-1.5.3.jar:$KAMANJA_HOME/lib/system/kafka-clients-0.9.0.1.jar com.ligadata.metadataapiservice.APIService
```

**Comment by ligadata-yousef** [comment]
@ligadata-william 

Check the Kafka version in your machine because Daas just work with kafka v9. if you use kafka v8 or v10 you should see this error.

**Comment by ligadata-william** [comment]
@ligadata-yousef I had kafka v9 installed. This error occurs because the kamanja script doesn't have kafka-clients-0.9.0.1.jar in the startup command. See the section in the original description labeled **WORKAROUND**.
