### ISSUE TITLE
DaaS: Querying container causes exception on KamanjaManager

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1564]
This was reproduced running the medical sample application
When I run the following command:
```
curl -k https://localhost:8081/data/coughcodes/?icd9code=0330
```
The client hangs until timeout and KamanjaManager throws the following ERROR:
```
ERROR [pool-23-thread-1] - Failed to Deserialize/Execute. MessageName: at UK:{"Version":1,"Type":"Kafka","Name":"request","TopicName":"requesttopic","PartitionId":0}, UV:{"Version":1,"Offset":1}
com.ligadata.Exceptions.KamanjaException: Not found any bindings to deserialize (including default serializer)
	at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:584) ~[KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.kafkaInputOutputAdapters_v9.KamanjaKafkaConsumer.deserialize(KamanjaKafkaConsumer.scala:49) ~[?:?]
	at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:321) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:42) [kamanjamanager_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.kafkaInputOutputAdapters_v9.KamanjaKafkaConsumer$$anonfun$StartProcessing$4$$anon$1.run(KamanjaKafkaConsumer.scala:435) [kamanjakafkaadapters_0_9_2.11-1.5.3.jar:1.5.3]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by ligadata-william** [comment]
This is user error. Closing.
