### ISSUE TITLE
DaaS: Querying data causes a JsonParsingException on MetadataAPIService

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1566]
When running the command:
```
curl -k https://localhost:8081/data/com.ligadata.kamanja.samples.containers.coughcodes/?icd9code=0330
```
Kamanja properly populates the ResponseTopic, however, upon returning it to the API Service, the api service throws an exception when attempting to parse:
```
MESSAGE-> at @partition 0 @offset 8 {\"id\":\"7bbdaf85-9223-4766-8cb8-cd89a6836edd\",\"status\":\"success\",\"statusCode\":\"1000\",\"statusDescription\":\"\",\"resultCount\":1,\"result\":[{\"icd9code\":\"0330\",\"icd9description\":\"\\\"0330 - Whooping cough due to bordetella pertussis [B. pertussis]\\\"\"}]}
 WARN [pool-2-thread-1] - Error processing response: expected field or array
Near: 9description":""0330
org.json4s.ParserUtil$ParseException: expected field or array
Near: 9description":""0330
	at org.json4s.native.JsonParser$Parser.fail(JsonParser.scala:207) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at org.json4s.native.JsonParser$$anonfun$1.newValue$1(JsonParser.scala:155) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:165) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:117) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at org.json4s.native.JsonParser$.parse(JsonParser.scala:105) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at org.json4s.native.JsonParser$.parse(JsonParser.scala:53) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at org.json4s.native.JsonMethods$class.parse(JsonMethods.scala:11) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at org.json4s.native.JsonMethods$.parse(JsonMethods.scala:61) ~[ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaDataAccessAdapter.recieveResponse(KafkaDataAccessAdapter.scala:98) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaDataAccessAdapter$$anonfun$start$1.apply(KafkaDataAccessAdapter.scala:62) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaDataAccessAdapter$$anonfun$start$1.apply(KafkaDataAccessAdapter.scala:62) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.dataaccessapi.KafkaResponseReader$$anonfun$start$1$$anon$1.run(KafkaResponseReader.scala:136) [metadataapiservice_2.11-1.5.3.jar:1.5.3]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
^C WARN [shutdownHook1] - ShutdownHook called
```

**Comment by ligadata-william** [comment]
**UPDATE**
This is caused by quotes already existing in the message or container data. This causes malformed JSON in our system. Any containers or messages without quotes in the data are parsed and returned correctly.
