### ISSUE TITLE
SmartFileConsumer fails with NumberFormatException on 1.6.3

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1616]
When attempting to process files, SmartFileConsumer fails with a NumberFormatException:
```
ERROR [pool-56-thread-2] - Smart File Monitor - Error
java.lang.NumberFormatException: For input string: "NodeId-1-UUID-33c5ad7e-567f-4d46-a091-bf2bd4d4db72"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272) ~[ExtDependencyLibs2_2.11-1.6.3.jar:1.6.3]
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:30) ~[ExtDependencyLibs2_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.SmartFileConsumer.com$ligadata$InputAdapters$SmartFileConsumer$$assignFileProcessingIfPossible(SmartFileConsumer.scala:1244) ~[KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.SmartFileConsumer.com$ligadata$InputAdapters$SmartFileConsumer$$newFileDetectedCallback(SmartFileConsumer.scala:814) ~[KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.SmartFileConsumer$$anonfun$initializeNode$1.apply$mcV$sp(SmartFileConsumer.scala:437) ~[KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.MonitorController.com$ligadata$InputAdapters$MonitorController$$monitorBufferingFiles(MonitorController.scala:728) ~[KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.MonitorController$$anonfun$monitor$2$$anon$3.run(MonitorController.scala:284) [KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.6.3.jar:1.6.3]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.6.3.jar:1.6.3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
ERROR [pool-56-thread-1] - Smart File Monitor - Error
java.lang.NumberFormatException: For input string: "NodeId-1-UUID-33c5ad7e-567f-4d46-a091-bf2bd4d4db72"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272) ~[ExtDependencyLibs2_2.11-1.6.3.jar:1.6.3]
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:30) ~[ExtDependencyLibs2_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.SmartFileConsumer.com$ligadata$InputAdapters$SmartFileConsumer$$assignFileProcessingIfPossible(SmartFileConsumer.scala:1244) ~[KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.SmartFileConsumer.com$ligadata$InputAdapters$SmartFileConsumer$$newFileDetectedCallback(SmartFileConsumer.scala:814) ~[KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.SmartFileConsumer$$anonfun$initializeNode$1.apply$mcV$sp(SmartFileConsumer.scala:437) ~[KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.MonitorController.com$ligadata$InputAdapters$MonitorController$$monitorBufferingFiles(MonitorController.scala:728) ~[KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.MonitorController$$anonfun$monitor$2$$anon$3.run(MonitorController.scala:284) [KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.6.3.jar:1.6.3]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.6.3.jar:1.6.3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
ERROR [pool-31-thread-2] - Smart File Consumer - unkown exception
java.lang.NumberFormatException: For input string: "NodeId-1-UUID-33c5ad7e-567f-4d46-a091-bf2bd4d4db72"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272) ~[ExtDependencyLibs2_2.11-1.6.3.jar:1.6.3]
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:30) ~[ExtDependencyLibs2_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.SmartFileConsumer.com$ligadata$InputAdapters$SmartFileConsumer$$assignFileProcessingIfPossible(SmartFileConsumer.scala:1244) ~[KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at com.ligadata.InputAdapters.SmartFileConsumer$$anon$3.run(SmartFileConsumer.scala:686) [KamanjaInternalDeps_2.11-1.6.3.jar:1.6.3]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.6.3.jar:1.6.3]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.6.3.jar:1.6.3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by ligadata-william** [comment]
This was found through the course of testing https://ligadata.atlassian.net/projects/FLR/issues/FLR-529.

**Comment by ligadata-william** [comment]
The offender appears to begin at line 1244 where the nodeId is being passed in as an integer:
```
val newProcessingItem = createProcessingItemJsonFromGroup(requestingNodeId.toInt, requestingThreadId.toInt, groupToProcess)
```
Perhaps changing the defs called from there to accept String will be enough. Haven't looked hard enough to be sure though.

**Comment by ligadata-mkhalawi** [comment]
I have did the required changes to fix the NumberFormatException bug, as the Node id was received as Integer previously, and now since 1.6.3, it's received as String.
