### ISSUE TITLE
 'GetMsgContainerElseNew' fails when "typename" is the Message definition name. Work around suggested by Rich is to use the DerivedField name works.

### ISSUE THREAD

**Issue by edifecs-pradeep** [LigaData/Kamanja#207]
ERROR [main] - Exception detected in Apply function 'GetMsgContainerElseNew' found in DerivedField 'assertions'
``` 
java.util.NoSuchElementException: next on empty iterator
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
        at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:64)
        at scala.collection.IterableLike$class.head(IterableLike.scala:91)
        at scala.collection.mutable.ArrayOps$ofRef.scala$collection$IndexedSeqOptimized$$super$head(ArrayOps.scala:108)
        at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:120)
```
For this PMML:

```xml
  <DerivedField name="assertions" dataType="COPD_CAT1_Rule1a1b_Visit_Asserts" optype="categorical">
    <Apply function="GetMsgContainerElseNew">
      <FieldRef field="gCtx"/>
      <Constant dataType="typename">COPD_CAT1_Rule1a1b_Visit_Asserts</Constant>
      <Constant dataType="string">system.COPD_CAT1_Rule1a1b_Visit_Asserts</Constant>
      <FieldRef field="msg.empi"/>
    </Apply>
  </DerivedField>
```

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
