### ISSUE TITLE
Running metadata test harness with cassandra fails to load snappy library

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#23]
I've set my config file to use "Database"     : "cassandra" prior to running the test harness to try to add metadata to cassandra and the below errors occur. @ligaDATA/platform 

INFO [main] - Opening datastore
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:317)
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:219)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:44)
	at com.datastax.driver.core.FrameCompressor$SnappyCompressor.<init>(FrameCompressor.java:55)
	at com.datastax.driver.core.FrameCompressor$SnappyCompressor.<clinit>(FrameCompressor.java:41)
	at com.datastax.driver.core.ProtocolOptions$Compression.<clinit>(ProtocolOptions.java:35)
	at com.datastax.driver.core.Cluster$Builder.<init>(Cluster.java:500)
	at com.datastax.driver.core.Cluster.builder(Cluster.java:156)
	at com.ligadata.keyvaluestore.cassandra.KeyValueCassandra.<init>(KeyValueCassandra.scala:56)
	at com.ligadata.keyvaluestore.KeyValueManager$.Get(KeyValueManager.scala:22)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetDataStoreHandle(MetadataAPIImpl.scala:1023)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1037)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:3858)
	at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:1567)
	at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)
Caused by: java.lang.UnsatisfiedLinkError: no snappyjava in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.xerial.snappy.SnappyNativeLoader.loadLibrary(SnappyNativeLoader.java:52)
	... 19 more
 WARN [main] - Error loading Snappy library (org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] null). Snappy compression will not be available for the protocol.
 WARN [main] - Cannot find LZ4 class, you should make sure the LZ4 library is in the classpath if you intend to use it. LZ4 compression will not be available for the protocol.
 INFO [main] - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)

This stack trace occurs several times in a row:

ERROR [main] - Error parsing schema options for table system.IndexInfo: Cluster.getMetadata().getKeyspace("system").getTable("IndexInfo").getOptions() will return null
java.lang.IllegalArgumentException: populate_io_cache_on_flush is not a column defined in this metadata
	at com.datastax.driver.core.ColumnDefinitions.getAllIdx(ColumnDefinitions.java:273)
	at com.datastax.driver.core.ColumnDefinitions.getFirstIdx(ColumnDefinitions.java:279)
	at com.datastax.driver.core.ArrayBackedRow.isNull(ArrayBackedRow.java:56)
	at com.datastax.driver.core.TableMetadata$Options.<init>(TableMetadata.java:529)
	at com.datastax.driver.core.TableMetadata.build(TableMetadata.java:119)
	at com.datastax.driver.core.Metadata.buildTableMetadata(Metadata.java:150)
	at com.datastax.driver.core.Metadata.rebuildSchema(Metadata.java:94)
	at com.datastax.driver.core.ControlConnection.refreshSchema(ControlConnection.java:294)
	at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:231)
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:171)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1104)
	at com.datastax.driver.core.Cluster.init(Cluster.java:121)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:198)
	at com.ligadata.keyvaluestore.cassandra.KeyValueCassandra.<init>(KeyValueCassandra.scala:63)
	at com.ligadata.keyvaluestore.KeyValueManager$.Get(KeyValueManager.scala:22)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetDataStoreHandle(MetadataAPIImpl.scala:1023)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1037)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:3858)
	at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:1567)
	at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)

**Comment by ligadata-william** [comment]
I'm closing this for now. We need to update our cassandra libs per #1041 and I don't believe we'll see this issue in later versions.
