### ISSUE TITLE
Failed to download the Jar of the object(pmml.dateblock.100's dep jar pmmludfs_2.10-1.0.jar):

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#289]
Repro:

Start Zookeeper
Run ApplicationMetadataAPI.sh

Expected:
No error

Actual:

TRACE [main] - KeyNotFound Exception: Error => Key Not found
ERROR [main] - Failed to download the Jar of the object(pmml.dateblock.100's dep jar pmmludfs_2.10-1.0.jar): Failed to verify whether a download is required for the jar pmmludfs_2.10-1.0.jar of the object(pmml.dateblock.100): Key Not found
ERROR [main] - Transaction is incomplete with the object functiondef.pmml.dateblock(string,any),we may not have notified engine, attempt to do it now...
com.ligadata.Serialize.UnsupportedObjectException: zkSerializeObjectToJson doesn't support the  objects of type objectType of com.ligadata.olep.metadata.FunctionDef yet.
        at com.ligadata.Serialize.JsonSerializer$.zkSerializeObjectToJson(JsonSerializer.scala:815)
        at com.ligadata.Serialize.JsonSerializer$$anonfun$zkSerializeObjectListToJson$1.apply(JsonSerializer.scala:1335)
        at com.ligadata.Serialize.JsonSerializer$$anonfun$zkSerializeObjectListToJson$1.apply(JsonSerializer.scala:1335)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at com.ligadata.Serialize.JsonSerializer$.zkSerializeObjectListToJson(JsonSerializer.scala:1335)
        at com.ligadata.Serialize.JsonSerializer$.zkSerializeObjectListToJson(JsonSerializer.scala:1342)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.ZooKeeperMessage(MetadataAPIImpl.scala:465)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.NotifyEngine(MetadataAPIImpl.scala:482)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:3652)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5305)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:2062)
        at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)
com.ligadata.MetadataAPI.InternalErrorException: Failed to notify a zookeeper message from the objectList Failed to generate a zookeeper message from the objList zkSerializeObjectToJson doesn't support the  objects of type objectType of com.ligadata.olep.metadata.FunctionDef yet.
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.NotifyEngine(MetadataAPIImpl.scala:490)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:3652)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5305)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:2062)
        at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)

**Comment by ligadata-william** [comment]
This has been fixed for some time now. Closing due to age and lack of response.
