### ISSUE TITLE
UnsupportedObjectException:  com.ligadata.olep.metadata.FunctionDef

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#298]
Repro Steps:
Start Zookeeper
Start MetadataAPIService
cd ~/dev/Fatafat/trun
sbt
project MetadataAPIService
run --config /home/le/EngineCassConfigs/config/MetadataAPIConfig.properties

Expected;
Below Function def should be supported

Actual:
UnsupportedObjectException

ERROR [metadata-api-service-akka.actor.default-dispatcher-2] - Transaction is incomplete with the object functiondef.pmml.dateblock(string,any),we may not have notified engine, attempt to do it now...
com.ligadata.Serialize.UnsupportedObjectException: zkSerializeObjectToJson doesn't support the  objects of type objectType of com.ligadata.olep.metadata.FunctionDef yet.
        at com.ligadata.Serialize.JsonSerializer$.zkSerializeObjectToJson(JsonSerializer.scala:815)
        at com.ligadata.Serialize.JsonSerializer$$anonfun$zkSerializeObjectListToJson$1.apply(JsonSerializer.scala:1335)
        at com.ligadata.Serialize.JsonSerializer$$anonfun$zkSerializeObjectListToJson$1.apply(JsonSerializer.scala:1335)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at com.ligadata.Serialize.JsonSerializer$.zkSerializeObjectListToJson(JsonSerializer.scala:1335)
        at com.ligadata.Serialize.JsonSerializer$.zkSerializeObjectListToJson(JsonSerializer.scala:1342)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.ZooKeeperMessage(MetadataAPIImpl.scala:465)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.NotifyEngine(MetadataAPIImpl.scala:482)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:3652)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5305)
        at com.ligadata.metadataapiservice.APIInit$.Init(APIInit.scala:53)
        at com.ligadata.metadataapiservice.MetadataAPIService$class.$init$(MetadataAPIService.scala:22)
        at com.ligadata.metadataapiservice.MetadataAPIServiceActor.<init>(MetadataAPIService.scala:13)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:379)
        at akka.util.Reflect$.instantiate(Reflect.scala:45)
        at akka.actor.NoArgsReflectConstructor.produce(Props.scala:358)
        at akka.actor.Props.newActor(Props.scala:249)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ligadata-william** [comment]
Fixed for months. Closing.
