### ISSUE TITLE
MetadataAPI.InternalErrorException: Failed to notify a zookeeper

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#299]
Repro Steps;
Start Zookeeper
Start MetadataAPIService 

cd ~/dev/Fatafat/trun
sbt
project MetadataAPIService
run --config /home/le/EngineCassConfigs/config/MetadataAPIConfig.properties

Expected:
Notify a zookeeper all messages successfully

Actual 
com.ligadata.MetadataAPI.InternalErrorException: Failed to notify a zookeeper message from the objectList

com.ligadata.MetadataAPI.InternalErrorException: Failed to notify a zookeeper message from the objectList Failed to generate a zookeeper message from the objList zkSerializeObjectToJson doesn't support the  objects of type objectType of com.ligadata.olep.metadata.FunctionDef yet.
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.NotifyEngine(MetadataAPIImpl.scala:490)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:3652)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5305)
        at com.ligadata.metadataapiservice.APIInit$.Init(APIInit.scala:53)
        at com.ligadata.metadataapiservice.MetadataAPIService$class.$init$(MetadataAPIService.scala:22)
        at com.ligadata.metadataapiservice.MetadataAPIServiceActor.<init>(MetadataAPIService.scala:13)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:379)
        at akka.util.Reflect$.instantiate(Reflect.scala:45)
        at akka.actor.NoArgsReflectConstructor.produce(Props.scala:358)
        at akka.actor.Props.newActor(Props.scala:249)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
TRACE [metadata-api-service-akka.actor.default-dispatcher-2] - Initialize Leader Latch

**Comment by ligadata-william** [comment]
Fixed several months ago. Closing.
