### ISSUE TITLE
MetadataAPIService unable to connect to cassandra

### ISSUE THREAD

**Issue by edifecs-pankaj** [LigaData/Kamanja#490]
1. MetadataAPIService was running initially
2. Stopped service.
3. Tried to restart it as  :  sbt "project MetadataAPIService" "run"

Getting error in the end as :

DEBUG [run-main-0] - [Control connection] Successfully connected to localhost/127.0.0.1:9042
 INFO [run-main-0] - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
 INFO [Cassandra Java Driver worker-0] - New Cassandra host localhost/127.0.0.1:9042 added
com.ligadata.keyvaluestore.ConnectionFailedException: Unable to connect to cassandra at localhost:null
        at com.ligadata.keyvaluestore.cassandra.KeyValueCassandra.<init>(KeyValueCassandra.scala:92)
        at com.ligadata.keyvaluestore.KeyValueManager$.Get(KeyValueManager.scala:23)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetDataStoreHandle(MetadataAPIImpl.scala:1671)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1684)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5671)
        at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:104)
        at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:153)
        at com.ligadata.metadataapiservice.APIService.main(APIService.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sbt.Run.invokeMain(Run.scala:67)
        at sbt.Run.run0(Run.scala:61)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:85)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:745)
DEBUG [Cassandra Java Driver worker-0] - [Control connection] Refreshing node list and token map
com.ligadata.MetadataAPI.CreateStoreFailedException: Unable to connect to cassandra at localhost:null
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetDataStoreHandle(MetadataAPIImpl.scala:1675)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1684)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5671)
        at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:104)
        at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:153)
        at com.ligadata.metadataapiservice.APIService.main(APIService.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sbt.Run.invokeMain(Run.scala:67)
        at sbt.Run.run0(Run.scala:61)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)DEBUG [Cassandra Java Driver worker-0] - [Control connection] Refreshing node list and token map
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:85)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:745)
com.ligadata.MetadataAPI.CreateStoreFailedException: Unable to connect to cassandra at localhost:null
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1708)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5671)
        at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:104)
        at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:153)
        at com.ligadata.metadataapiservice.APIService.main(APIService.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sbt.Run.invokeMain(Run.scala:67)
        at sbt.Run.run0(Run.scala:61)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:85)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:745)
DEBUG [run-main-0-SendThread(localhost:2181)] - Got ping response for sessionid: 0x14db3ad837d0004 after 1ms

MetadataAPIConfig.properties is as : 
=============================

nodeId=1
MetadataSchemaNam=metadata
MetadataStoreType=cassandra
MetadataLocation=localhost
ROOT_DIR=/home/le/dev/OnLEPInstall
GIT_ROOT=/home/le/dev/OnLEPInstall
JAR_TARGET_DIR=/home/le/dev/OnLEPInstall/lib/application
SCALA_HOME=/usr
JAVA_HOME=/usr
MANIFEST_PATH=/home/le/dev/OnLEPInstall/input/application1/metadata/model/manifest.mf
CLASSPATH=/home/le/dev/OnLEPInstall/lib/system/metadata_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/basefunctions_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/messagedef_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/methodextractor_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmlcompiler_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/fatafatbase_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/bootstrap_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/joda-time-2.3.jar:/home/le/dev/OnLEPInstall/lib/system/joda-convert-1.6.jar:/home/le/dev/OnLEPInstall/lib/system/basetypes_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmludfs_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmlruntime_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-native_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-core_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-ast_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-databind-2.3.1.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-annotations-2.3.0.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-jackson_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-core-2.3.1.jar:/home/le/dev/OnLEPInstall/lib/system/log4j-1.2.17.jar
NOTIFY_ENGINE=YES
ZNODE_PATH=/ligadata/metadata
ZOOKEEPER_CONNECT_STRING=localhost:2181
COMPILER_WORK_DIR=/home/le/dev/OnLEPInstall/workingdir
SERVICE_PORT=8081
SERVICE_HOST=10.30.50.104
MODEL_FILES_DIR=/home/le/dev/OnLEPInstall/input/application1/metadata/model
TYPE_FILES_DIR=/home/le/dev/OnLEPInstall/input/application1/metadata/type
FUNCTION_FILES_DIR=/home/le/dev/OnLEPInstall/input/application1/metadata/function
CONCEPT_FILES_DIR=/home/le/dev/OnLEPInstall/input/application1/metadata/concept
MESSAGE_FILES_DIR=/home/le/dev/OnLEPInstall/input/application1/metadata/message
CONTAINER_FILES_DIR=/home/le/dev/OnLEPInstall/input/application1/metadata/container
CONFIG_FILES_DIR=/home/le/dev/OnLEPInstall/input/application1/metadata/config
MODEL_EXEC_LOG=false
JarPaths=/home/le/dev/OnLEPInstall/lib/system,/home/le/dev/OnLEPInstall/lib/application
SECURITY_IMPL_JAR=/home/le/dev/OnLEPInstall/lib/system/simpleapacheshiroadapter_2.10-1.0.jar
SECURITY_IMPL_CLASS=com.ligadata.Security.SimpleApacheShiroAdapter
AUDIT_IMPL_JAR=/home/le/dev/OnLEPInstall/lib/system/auditadapters_2.10-1.0.jar
AUDIT_IMPL_CLASS=com.ligadata.audit.adapters.AuditCassandraAdapter
DO_AUDIT=NO
DO_AUTH=NO
SSL_CERTIFICATE=/home/le/dev/OnLEPInstall/config/keystore.jks

**Comment by ligadata-william** [comment]
This hass been fixed for some time. Closing.
