### ISSUE TITLE
ClusterMetadata.sh run is not working 

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#571]
Repro steps:
Pre-req:
Install ligadata v1.0.05 

Start zk, kafka and cassandra
Run ./ClusterMetadata.sh

Expected:
MetadataAPI Menu

Actual:
Exception in thread "main" com.ligadata.Serialize.KryoSerializationException: Failed to DeSerialize the object:java.lang.IndexOutOfBoundsException: Index: 105, Size: 4
Serialization trace:

le@le-demo2:~/EngineCassConfigs/bin$ ./ClusterMetadata.sh
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main-SendThread(localhost:2181)] - Connected to an old server; r-o mode will be unavailable
 WARN [main-SendThread(localhost:2181)] - Connected to an old server; r-o mode will be unavailable
 WARN [main] - Cannot find LZ4 class, you should make sure the LZ4 library is in the classpath if you intend to use it. LZ4 compression will not be available for the protocol.
Exception in thread "main" com.ligadata.Serialize.KryoSerializationException: Failed to DeSerialize the object:java.lang.IndexOutOfBoundsException: Index: 105, Size: 4
Serialization trace:
delimiterString (com.ligadata.fatafat.metadata.AdapterInfo)
        at com.ligadata.Serialize.KryoSerializer.DeserializeObjectFromByteArray(KryoSerializer.scala:65)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllConfigObjectsIntoCache$2.apply(MetadataAPIImpl.scala:4289)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllConfigObjectsIntoCache$2.apply(MetadataAPIImpl.scala:4276)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllConfigObjectsIntoCache(MetadataAPIImpl.scala:4276)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:4316)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:6128)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:2413)
        at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)
le@le-demo2:~/EngineCassConfigs/bin$

**************************************************ClusterCfg config**************************************
NODE_ID=1
MetadataSchemaName=metadata
MetadataStoreType=cassandra
MetadataLocation=le-demo2
ROOT_DIR=/home/le/dev/OnLEPInstall
GIT_ROOT=/home/le/dev/OnLEPInstall
JAR_TARGET_DIR=/home/le/dev/OnLEPInstall/lib/application
SCALA_HOME=/usr
JAVA_HOME=/usr
MANIFEST_PATH=/home/le/dev/OnLEPInstall/config/manifest.mf
CLASSPATH=/home/le/dev/OnLEPInstall/lib/system/metadata_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/basefunctions_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/messagedef_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/methodextractor_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmlcompiler_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/fatafatbase_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/bootstrap_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/joda-time-2.3.jar:/home/le/dev/OnLEPInstall/lib/system/joda-convert-1.6.jar:/home/le/dev/OnLEPInstall/lib/system/basetypes_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmludfs_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmlruntime_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-native_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-core_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-ast_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-databind-2.3.1.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-annotations-2.3.0.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-jackson_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-core-2.3.1.jar:/home/le/dev/OnLEPInstall/lib/system/log4j-1.2.17.jar
NOTIFY_ENGINE=YES
ZNODE_PATH=/ligadata
API_LEADER_SELECTION_ZK_NODE=/ligadata/metadata
ZOOKEEPER_CONNECT_STRING=localhost:2181
COMPILER_WORK_DIR=/home/le/dev/OnLEPInstall/workingdir
SERVICE_HOST=10.30.50.72
SERVICE_PORT=8081
MODEL_FILES_DIR=/home/le/EngineCassConfigs/config
TYPE_FILES_DIR=/home/le/EngineCassConfigs/config
FUNCTION_FILES_DIR=/home/le/EngineCassConfigs/config
CONCEPT_FILES_DIR=/home/le/EngineCassConfigs/config
MESSAGE_FILES_DIR=/home/le/EngineCassConfigs/config
CONTAINER_FILES_DIR=/home/le/EngineCassConfigs/config
CONFIG_FILES_DIR=/home/le/EngineCassConfigs/config
MODEL_EXEC_LOG=true
JarPaths=/home/le/dev/OnLEPInstall/lib/system,/home/le/dev/OnLEPInstall/lib/application
SECURITY_IMPL_JAR=/home/le/dev/OnLEPInstall/lib/system/simpleapacheshiroadapter_2.10-1.0.jar
SECURITY_IMPL_CLASS=com.ligadata.Security.SimpleApacheShiroAdapter
AUDIT_IMPL_JAR=/home/le/dev/OnLEPInstall/lib/system/auditadapters_2.10-1.0.jar
AUDIT_IMPL_CLASS=com.ligadata.audit.adapters.AuditCassandraAdapter
DO_AUDIT=NO
DO_AUTH=NO
SSL_CERTIFICATE=/home/le/dev/OnLEPInstall/config/keystore.jks

**Comment by ligadata-william** [comment]
This is no longer valid as the script doesn't exist. Closing.
