### ISSUE TITLE
Start MetadataAPIService error 

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#582]
Precondition:
Install new release v1.0.5

Repro-steps

Start zk, kafka, cassandra and the engine
Start metadataAPIService

Expected:
No error 

Actual 
ERROR [metadata-api-service-akka.actor.default-dispatcher-4-EventThread] - Background exception was not retry-able or retry gave up

DEBUG [metadata-api-service-akka.actor.default-dispatcher-4-SendThread(10.30.50.25:2181)] - Reading reply sessionid:0x14edb6eb1d20044, packet:: clientPath:/ligadata/metadata/metadataleader/_c_b8a6c0ca-41de-4e27-8600-501e559e65f7-latch- serverPath:/ligadata/metadata/metadataleader/_c_b8a6c0ca-41de-4e27-8600-501e559e65f7-latch- finished:false header:: 2,1  replyHeader:: 2,178266,0  request:: '/ligadata/metadata/metadataleader/_c_b8a6c0ca-41de-4e27-8600-501e559e65f7-latch-,#31,v{s{31,s{'world,'anyone}}},3  response:: '/ligadata/metadata/metadataleader/_c_b8a6c0ca-41de-4e27-8600-501e559e65f7-latch-0000000002
DEBUG [metadata-api-service-akka.actor.default-dispatcher-4-SendThread(10.30.50.25:2181)] - Reading reply sessionid:0x14edb6eb1d20044, packet:: clientPath:null serverPath:null finished:false header:: 3,-11  replyHeader:: 3,178267,0  request:: null response:: null
DEBUG [metadata-api-service-akka.actor.default-dispatcher-4-SendThread(10.30.50.25:2181)] - An exception was thrown while closing send thread for session 0x14edb6eb1d20044 : Unable to read additional data from server sessionid 0x14edb6eb1d20044, likely server has closed socket
DEBUG [run-main-0] - Disconnecting client for session: 0x14edb6eb1d20044
 INFO [run-main-0] - Session: 0x14edb6eb1d20044 closed
ERROR [metadata-api-service-akka.actor.default-dispatcher-4-EventThread] - Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: instance must be started before calling this method
        at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:344)
        at org.apache.curator.framework.recipes.leader.LeaderLatch.setNode(LeaderLatch.java:658)
        at org.apache.curator.framework.recipes.leader.LeaderLatch.access$300(LeaderLatch.java:62)
        at org.apache.curator.framework.recipes.leader.LeaderLatch$4.processResult(LeaderLatch.java:487)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:715)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:502)
        at org.apache.curator.framework.imps.CreateBuilderImpl.sendBackgroundResponse(CreateBuilderImpl.java:538)
        at org.apache.curator.framework.imps.CreateBuilderImpl.access$700(CreateBuilderImpl.java:44)
        at org.apache.curator.framework.imps.CreateBuilderImpl$6.processResult(CreateBuilderImpl.java:497)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:599)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
 INFO [metadata-api-service-akka.actor.default-dispatcher-4-EventThread] - EventThread shut down

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
