### ISSUE TITLE
Deploy model/messages through rest api service failed

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#590]
Pre-request
Install v1.0.5 release

Start zk, kafka, cassandra and engine
Start Engine
Start MetadataAPIService
Deploy rule from Le-Studio through rest call 

Expected:
Model and Messages deployed successfully 

Actual:
ERROR [run-main-0] - Failed to download the Jar of the object(pmml.dateblock.000000000000000100's dep jar pmmludfs_2.10-1.0.jar). Message:Failed to verify whether a download is required for the jar pmmludfs_2.10-1.0.jar of the 

ERROR [run-main-0] - Failed to download the Jar of the object(pmml.dateblock.000000000000000100's dep jar pmmludfs_2.10-1.0.jar). Message:Failed to verify whether a download is required for the jar pmmludfs_2.10-1.0.jar of the object(pmml.dateblock.000000000000000100): Key Not found Reason:null
com.ligadata.MetadataAPI.InternalErrorException: Failed to verify whether a download is required for the jar pmmludfs_2.10-1.0.jar of the object(pmml.dateblock.000000000000000100): Key Not found
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.IsDownloadNeeded(MetadataAPIImpl.scala:1383)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1439)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1435)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.DownloadJarFromDB(MetadataAPIImpl.scala:1435)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$2.apply(MetadataAPIImpl.scala:4342)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$2.apply(MetadataAPIImpl.scala:4336)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:4336)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:6128)
        at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:104)
        at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:153)
        at com.ligadata.metadataapiservice.APIService.main(APIService.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sbt.Run.invokeMain(Run.scala:67)
        at sbt.Run.run0(Run.scala:61)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:85)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
