### ISSUE TITLE
Start Engine failed to download jar scala-compiler-2.10.0.jar

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#594]
Pre-request
Install v1.0.5 release

Start zk, kafka, cassandra
Add metadata
Add messages (successfully added messages)
Add model 
Start Engine

Expected:
Successfully upload all jars

Actual:
Message:Failed to verify whether a download is r                                    equired for the jar scala-compiler-2.10.0.jar of the object(pmml.anyblock.000000000000000100): Key Not found Reason:null
com.ligadata.MetadataAPI.InternalErrorException: Failed to verify whether a download is required for the jar scala-compiler-2.10.0.jar of the object(pmml.anyblock.000000000000                                    000100)

DEBUG [main] - Get the object from store, key => pmmludfs_2.10-1.0.jar
DEBUG [main] - A jar file already exists, and it's size (349543)  matches with the size of the existing Jar (pmmludfs_2.10-1.0.jar,349543) of the object(pmml.anyblock.00000000                                    0000000100), no need to download.
DEBUG [main] - Get the object from store, key => json4s-native_2.10-3.2.9.jar
DEBUG [main] - A jar file already exists, and it's size (68748)  matches with the size of the existing Jar (json4s-native_2.10-3.2.9.jar,68748) of the object(pmml.anyblock.000                                    000000000000100), no need to download.
DEBUG [main] - Get the object from store, key => pmmlruntime_2.10-1.0.jar
DEBUG [main] - A jar file already exists, and it's size (211028)  matches with the size of the existing Jar (pmmlruntime_2.10-1.0.jar,211028) of the object(pmml.anyblock.00000                                    0000000000100), no need to download.
DEBUG [main] - Get the object from store, key => scala-compiler-2.10.0.jar
DEBUG [main] - KeyNotFound Exception: Error => Key Not found
ERROR [main] - Failed to download the Jar of the object(pmml.anyblock.000000000000000100's dep jar scala-compiler-2.10.0.jar). Message:Failed to verify whether a download is r                                    equired for the jar scala-compiler-2.10.0.jar of the object(pmml.anyblock.000000000000000100): Key Not found Reason:null
com.ligadata.MetadataAPI.InternalErrorException: Failed to verify whether a download is required for the jar scala-compiler-2.10.0.jar of the object(pmml.anyblock.000000000000                                    000100): Key Not found
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.IsDownloadNeeded(MetadataAPIImpl.scala:1383)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1439)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$DownloadJarFromDB$2.apply(MetadataAPIImpl.scala:1435)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.DownloadJarFromDB(MetadataAPIImpl.scala:1435)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$2.apply(MetadataAPIImpl.scala:4342)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$LoadAllObjectsIntoCache$2.apply(MetadataAPIImpl.scala:4336)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:4336)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:6128)
        at com.ligadata.FatafatManager.FatafatMetadata$.InitBootstrap(FatafatMetadata.scala:520)
        at com.ligadata.FatafatManager.FatafatManager.initialize(FatafatManager.scala:310)
        at com.ligadata.FatafatManager.FatafatManager.run(FatafatManager.scala:424)
        at com.ligadata.FatafatManager.OleService$.main(FatafatManager.scala:523)
        at com.ligadata.FatafatManager.OleService.main(FatafatManager.scala)
DEBUG [main] - Get the object from store, key => basetypes_2.10-0.1.0.jar

**Comment by ligadata-william** [comment]
Closing as invalid. Only 3 "fat" jars will be used as library dependencies now and they are packaged with Kamanja.
