### ISSUE TITLE
Failed to compile container if it has field of type "System.tupleofint2"

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#610]
this is my container :

{
   "Container":{
      "NameSpace":"System",
      "Name":"POC3Container",
      "Version":"1.00",
      "Description":"",
      "Fixed":"true",
      "Elements":[
         {
            "Field":{
               "NameSpace":"System",
               "Name":"user_id",
               "Type":"System.string"
            }
         },
                 {
            "Field":{
               "NameSpace":"System",
               "Name":"c0",
               "Type":"System.tupleofint2"
            }
         }
      ],
      "PartitionKey":[
         "user_id"
      ]
   }
}

message error is :

DEBUG [main] - Call Message Compiler ....
java.lang.NullPointerException
        at com.ligadata.messagedef.BaseTypesHandler.handleBaseTypes(BaseTypesHandler.scala:51)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:223)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:137)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.messagedef.MessageFldsExtractor.classStr(MessageFldsExtractor.scala:137)
        at com.ligadata.messagedef.MessageDefImpl.createClassStr(MessageDefImpl.scala:297)
        at com.ligadata.messagedef.MessageDefImpl.createFixedMsgClass(MessageDefImpl.scala:235)
        at com.ligadata.messagedef.MessageDefImpl.processMsgDef(MessageDefImpl.scala:204)
        at com.ligadata.MetadataAPI.CompilerProxy.compileMessageDef(CompilerProxy.scala:225)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2595)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2694)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1117)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1104)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.AddContainer(TestMetadataAPI.scala:1104)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$14.apply$mcV$sp(TestMetadataAPI.scala:2460)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.StartTest(TestMetadataAPI.scala:2557)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:2640)
        at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)
java.lang.NullPointerException
        at com.ligadata.messagedef.BaseTypesHandler.handleBaseTypes(BaseTypesHandler.scala:51)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:223)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:137)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.messagedef.MessageFldsExtractor.classStr(MessageFldsExtractor.scala:137)
        at com.ligadata.messagedef.MessageDefImpl.createClassStr(MessageDefImpl.scala:297)
        at com.ligadata.messagedef.MessageDefImpl.createFixedMsgClass(MessageDefImpl.scala:235)
        at com.ligadata.messagedef.MessageDefImpl.processMsgDef(MessageDefImpl.scala:204)
        at com.ligadata.MetadataAPI.CompilerProxy.compileMessageDef(CompilerProxy.scala:225)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2595)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2694)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1117)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1104)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.AddContainer(TestMetadataAPI.scala:1104)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$14.apply$mcV$sp(TestMetadataAPI.scala:2460)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.StartTest(TestMetadataAPI.scala:2557)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:2640)
        at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)
java.lang.NullPointerException
        at com.ligadata.messagedef.BaseTypesHandler.handleBaseTypes(BaseTypesHandler.scala:51)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:223)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:137)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.messagedef.MessageFldsExtractor.classStr(MessageFldsExtractor.scala:137)
        at com.ligadata.messagedef.MessageDefImpl.createClassStr(MessageDefImpl.scala:297)
        at com.ligadata.messagedef.MessageDefImpl.createFixedMsgClass(MessageDefImpl.scala:235)
        at com.ligadata.messagedef.MessageDefImpl.processMsgDef(MessageDefImpl.scala:204)
        at com.ligadata.MetadataAPI.CompilerProxy.compileMessageDef(CompilerProxy.scala:225)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2595)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2694)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1117)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1104)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.AddContainer(TestMetadataAPI.scala:1104)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$14.apply$mcV$sp(TestMetadataAPI.scala:2460)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.StartTest(TestMetadataAPI.scala:2557)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:2640)
        at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)
java.lang.NullPointerException
        at com.ligadata.messagedef.BaseTypesHandler.handleBaseTypes(BaseTypesHandler.scala:51)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:223)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:137)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.messagedef.MessageFldsExtractor.classStr(MessageFldsExtractor.scala:137)
        at com.ligadata.messagedef.MessageDefImpl.createClassStr(MessageDefImpl.scala:297)
        at com.ligadata.messagedef.MessageDefImpl.createFixedMsgClass(MessageDefImpl.scala:235)
        at com.ligadata.messagedef.MessageDefImpl.processMsgDef(MessageDefImpl.scala:204)
        at com.ligadata.MetadataAPI.CompilerProxy.compileMessageDef(CompilerProxy.scala:225)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2595)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2694)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1117)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1104)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.AddContainer(TestMetadataAPI.scala:1104)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$14.apply$mcV$sp(TestMetadataAPI.scala:2460)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.StartTest(TestMetadataAPI.scala:2557)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:2640)
        at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)
java.lang.NullPointerException
        at com.ligadata.messagedef.BaseTypesHandler.handleBaseTypes(BaseTypesHandler.scala:51)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:223)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:137)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.messagedef.MessageFldsExtractor.classStr(MessageFldsExtractor.scala:137)
        at com.ligadata.messagedef.MessageDefImpl.createClassStr(MessageDefImpl.scala:297)
        at com.ligadata.messagedef.MessageDefImpl.createFixedMsgClass(MessageDefImpl.scala:235)
        at com.ligadata.messagedef.MessageDefImpl.processMsgDef(MessageDefImpl.scala:204)
        at com.ligadata.MetadataAPI.CompilerProxy.compileMessageDef(CompilerProxy.scala:225)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2595)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2694)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1117)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1104)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.AddContainer(TestMetadataAPI.scala:1104)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$14.apply$mcV$sp(TestMetadataAPI.scala:2460)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.StartTest(TestMetadataAPI.scala:2557)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:2640)
        at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)
DEBUG [main] - Failed to compile the message definition java.lang.NullPointerException
java.lang.NullPointerException
        at com.ligadata.messagedef.BaseTypesHandler.handleBaseTypes(BaseTypesHandler.scala:51)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:223)
        at com.ligadata.messagedef.MessageFldsExtractor$$anonfun$classStr$4.apply(MessageFldsExtractor.scala:137)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.messagedef.MessageFldsExtractor.classStr(MessageFldsExtractor.scala:137)
        at com.ligadata.messagedef.MessageDefImpl.createClassStr(MessageDefImpl.scala:297)
        at com.ligadata.messagedef.MessageDefImpl.createFixedMsgClass(MessageDefImpl.scala:235)
        at com.ligadata.messagedef.MessageDefImpl.processMsgDef(MessageDefImpl.scala:204)
        at com.ligadata.MetadataAPI.CompilerProxy.compileMessageDef(CompilerProxy.scala:225)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2595)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2694)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1117)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$AddContainer$5.apply(TestMetadataAPI.scala:1104)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.AddContainer(TestMetadataAPI.scala:1104)
        at com.ligadata.MetadataAPI.TestMetadataAPI$$anonfun$14.apply$mcV$sp(TestMetadataAPI.scala:2460)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.StartTest(TestMetadataAPI.scala:2557)
        at com.ligadata.MetadataAPI.TestMetadataAPI$.main(TestMetadataAPI.scala:2640)
        at com.ligadata.MetadataAPI.TestMetadataAPI.main(TestMetadataAPI.scala)

Thanks,
Ahmed

**Comment by ligadata-william** [comment]
Is tuple support in messages still desired @ligadata-ahmad?

**Comment by ligadata-pokuri** [comment]
Hi william,

We are not supporting tuples any more from 1.4.0.

**Comment by ligadata-william** [comment]
Closing.

**Comment by ligadata-rich** [comment]
As a post script, the removal of the tuple means that the kpmml version of the copd model is broken.   It needs to be restated.

**Comment by ligadata-pokuri** [comment]
We need to use containers or something like that instead of tuples. That way implementation language is not barrier for UDFs creation and usage

 

Regards,

Sreenivasulu Pokuri

Principal Software Engineer

E: pokuri@ligadata.com  M: 425.233.0960

LD
