### ISSUE TITLE
BasicHeartBeat has unhandled exception when body is empty

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#619]
Using command curl -k -X POST https://localhost:8081/api/heartbeat causes the following exception to occur on the MetadataAPIService and causes the client to hang until timeout.

```
[ERROR] [08/11/2015 19:21:42.681] [metadata-api-service-akka.actor.default-dispatcher-19] [akka://metadata-api-service/user/metadata-api-service/$i] No content to map due to end-of-input
 at [Source: java.io.StringReader@b60c0b3; line: 1, column: 1]
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.StringReader@b60c0b3; line: 1, column: 1]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3036)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2978)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2098)
    at org.json4s.jackson.JsonMethods$class.parse(JsonMethods.scala:19)
    at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:44)
    at com.ligadata.MetadataAPI.MetadataAPIImpl$.getHealthCheck(MetadataAPIImpl.scala:166)
    at com.ligadata.metadataapiservice.GetHeartbeatService.process(GetHeartbeatService.scala:42)
    at com.ligadata.metadataapiservice.GetHeartbeatService$$anonfun$receive$1.applyOrElse(GetHeartbeatService.scala:32)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at com.ligadata.metadataapiservice.GetHeartbeatService.aroundReceive(GetHeartbeatService.scala:22)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ligadata-haitham** [comment]
this is the pull request : https://github.com/LigaData/Kamanja/pull/1193 

This handles the unhandled exception when body is empty issue.
this does NOT handle "As an addition to this, there are multiple heartbeats for an engine node."

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
