### ISSUE TITLE
brew install issues

### ISSUE THREAD

**Issue by ligadata-arun** [LigaData/Kamanja#695]
After installing kamanja via brew I tried to add message. I got UnsatisfiedLinkError and ConnectionFailedException. Command and error stack trace below.

kamanja /usr/local/opt/kamanja/input/SampleApplications/metadata/config/MetadataAPIConfig.properties add message /usr/local/opt/kamanja/input/SampleApplications/metadata/message/beneficiary_Medical.json
 WARN [main] - SERVICE_HOST remains unset
 WARN [main] - DO_AUTH remains unset
 WARN [main] - AUDIT_IMPL_JAR remains unset
 WARN [main] - SECURITY_IMPL_JAR remains unset
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - AUDIT_IMPL_CLASS remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - DO_AUDIT remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main] - SSL_CERTIFICATE remains unset
 WARN [main] - SECURITY_IMPL_CLASS remains unset
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:317)
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:219)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:44)
	at com.datastax.driver.core.FrameCompressor$SnappyCompressor.<init>(FrameCompressor.java:55)
	at com.datastax.driver.core.FrameCompressor$SnappyCompressor.<clinit>(FrameCompressor.java:41)
	at com.datastax.driver.core.ProtocolOptions$Compression.<clinit>(ProtocolOptions.java:30)
	at com.datastax.driver.core.Cluster$Builder.<init>(Cluster.java:548)
	at com.datastax.driver.core.Cluster.builder(Cluster.java:185)
	at com.ligadata.keyvaluestore.cassandra.KeyValueCassandra.<init>(KeyValueCassandra.scala:57)
	at com.ligadata.keyvaluestore.KeyValueManager$.Get(KeyValueManager.scala:23)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetDataStoreHandle(MetadataAPIImpl.scala:1778)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1791)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:6255)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:46)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
Caused by: java.lang.UnsatisfiedLinkError: no snappyjava in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.xerial.snappy.SnappyNativeLoader.loadLibrary(SnappyNativeLoader.java:52)
	... 19 more
 WARN [main] - Error loading Snappy library (org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] null). Snappy compression will not be available for the protocol.
 WARN [main] - Cannot find LZ4 class, you should make sure the LZ4 library is in the classpath if you intend to use it. LZ4 compression will not be available for the protocol.
com.ligadata.Exceptions.ConnectionFailedException: Unable to connect to cassandra at localhost:All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
	at com.ligadata.keyvaluestore.cassandra.KeyValueCassandra.<init>(KeyValueCassandra.scala:92)
	at com.ligadata.keyvaluestore.KeyValueManager$.Get(KeyValueManager.scala:23)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetDataStoreHandle(MetadataAPIImpl.scala:1778)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1791)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:6255)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:46)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
com.ligadata.Exceptions.CreateStoreFailedException: Unable to connect to cassandra at localhost:All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetDataStoreHandle(MetadataAPIImpl.scala:1782)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1791)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:6255)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:46)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
Exception in thread "main" com.ligadata.Exceptions.CreateStoreFailedException: Unable to connect to cassandra at localhost:All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:1821)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:6255)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:46)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)

**Comment by ligadata-dhaval** [comment]
Outdated
