### ISSUE TITLE
REST API heartbeat can't get by node id

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#741]
When I perform the following curl command:
```
curl -k -X POST https://localhost:8081/api/heartbeat -d []
```
I receive the following:
```
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "GetHeartbeat",
    "Result Data" : "[{\"Name\":\"1\",\"UniqueId\":252,\"LastSeen\":\"2015-09-10 12:46:35\",\"StartTime\":\"2015-09-10 12:25:39\",\"Components\":[],\"Metrics\":[]}]",
    "Result Description" : "Heartbeats fetched successfully"
  }
```
which is expected behavior.

However, when I run
```
curl -k -X POST https://localhost:8081/api/heartbeat -d ["1"]
```
The client hangs and the service throws the following exception:
```
java.lang.ClassCastException: scala.math.BigInt cannot be cast to java.lang.String
	at com.ligadata.MetadataAPI.MonitorAPIImpl$$anonfun$getHeartbeatInfo$2.apply(MonitorAPIImpl.scala:75)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at com.ligadata.MetadataAPI.MonitorAPIImpl$.getHeartbeatInfo(MonitorAPIImpl.scala:75)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.getHealthCheck(MetadataAPIImpl.scala:150)
	at com.ligadata.metadataapiservice.GetHeartbeatService.process(GetHeartbeatService.scala:44)
	at com.ligadata.metadataapiservice.GetHeartbeatService$$anonfun$receive$1.applyOrElse(GetHeartbeatService.scala:32)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.ligadata.metadataapiservice.GetHeartbeatService.aroundReceive(GetHeartbeatService.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
Similarly, removing the quotes and running the command as such
```
curl -k -X POST https://localhost:8081/api/heartbeat -d [1]
```
results in the same exception.

**Comment by ligadata-dan** [comment]
@ligadata-william 

I actually just found out that for CURL you actually have to excape DOUBLE QUOTES...  so the query you need to issue is 

curl -k -X POST https://localhost:8081/api/heartbeat -d [\"1\"]

I will add some exception processing to this code tough, to make sure we don't shut down the Service.  I will submit a pull request with the defensive code.

**Comment by donald-ligadata** [comment]
If you want the double quotes passed as literals, they need to be escaped. 

I taught shell programing for 10 years or so, so if you have a shell script that is causing you grief, it might save some time to have me look at it.

 

Donald

**Comment by ligadata-william** [comment]
Why is the user passing in a json string at all? Isn't the argument simply a string that is the nodeId? Should we even require quotes to be surrounding it in the first place?

Ideal usage of this (at least through curl) would be:
```
curl -X GET https://localhost:8081/api/heartbeat?nodeId=<nodeId>
```
or
```
curl -X GET https://localhost:8081/api/heartbeat -d <nodeId>
```
without any need for quotes at all and avoiding the usage of json completely.

Is there some constraint we suffer which forces us to do it this way?

**Comment by donald-ligadata** [comment]
The question mark is a special character to the shell, so, yes, you need the string in quotes.

**Comment by donald-ligadata** [comment]
Also [ and ] are special characters so if you intend to pass them to curl (which you do) quote the whole thing.  What you can do is this ‘stuff”stuff”’ – the single quotes quote the double quotes so you don’t need the backslash.

**Comment by ligadata-william** [comment]
In bash, you would surround the entire url in quotes, thereby eliminating
the parsing of those special characters. This is common practice in curl to
avoid such issues.

**Comment by ligadata-dan** [comment]
https://github.com/ligaDATA/Kamanja/pull/802

**Comment by ligadata-william** [comment]
Verified this is fixed. Closing.
