### ISSUE TITLE
NullPointerException is printed as a DEBUG statement in MetadataAPIImpl

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#786]
While attempting to add a message to sql server, Ii failed to upload jars to the server. When switching the logging to debug mode, I found a NullPointerException being printed as a DEBUG statement.
```
DEBUG [main] - Update the jarfile (size => 103996) of the object: system_Beneficiary_1000000_1443812907936.jar
DEBUG [main] - General Exception: Error => null
StackTrace:java.lang.NullPointerException
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetObject(MetadataAPIImpl.scala:577)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$UploadJarsToDB$1.apply(MetadataAPIImpl.scala:1257)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$$anonfun$UploadJarsToDB$1.apply(MetadataAPIImpl.scala:1249)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UploadJarsToDB(MetadataAPIImpl.scala:1249)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddMessageDef(MetadataAPIImpl.scala:1949)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2072)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2152)
	at com.ligadata.MetadataAPI.Utility.MessageService$$anonfun$addMessage$1.apply(MessageService.scala:57)
	at com.ligadata.MetadataAPI.Utility.MessageService$$anonfun$addMessage$1.apply(MessageService.scala:56)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.ligadata.MetadataAPI.Utility.MessageService$.addMessage(MessageService.scala:56)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:122)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:101)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
```

**Comment by ligadata-ramana** [comment]
William,
This error happened in our early stage of code changes in MetadataAPI to use SqlServerAdapter.
Pokuri corrected it a while ago. We nolonger have a code path that can lead to this scenario.
You can close this.

**Comment by ligadata-william** [comment]
I've verified this is no longer appearing. Closing.
