### ISSUE TITLE
Telecom application produces ERRORs when messages are pushed

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#789]
Several errors are raised when pushing messages for the Telecom sample application. The model needs to be updated for the new interfaces. See below for errors:
```
ERROR [pool-7-thread-4] - Model Failed => SubscriberUsageAlert. Reason: null. Message: null
ERROR [pool-7-thread-4] - StackTrace:java.lang.NullPointerException
	at com.ligadata.KvBase.KeyWithBucketIdAndPrimaryKeyCompHelper$$anonfun$CompareBucketKey$1.apply$mcVI$sp(KvBase.scala:75)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at com.ligadata.KvBase.KeyWithBucketIdAndPrimaryKeyCompHelper$.CompareBucketKey(KvBase.scala:74)
	at com.ligadata.KvBase.BucketKeyComp.compare(KvBase.scala:134)
	at com.ligadata.KvBase.BucketKeyComp.compare(KvBase.scala:131)
	at java.util.TreeMap.compare(TreeMap.java:1188)
	at java.util.TreeMap$NavigableSubMap.<init>(TreeMap.java:1260)
	at java.util.TreeMap$AscendingSubMap.<init>(TreeMap.java:1699)
	at java.util.TreeMap.subMap(TreeMap.java:877)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$TxnContextCommonFunctions$.getRecent(SimpleEnvContextImpl.scala:103)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$TransactionContext.getRecent(SimpleEnvContextImpl.scala:436)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.getLocalRecent(SimpleEnvContextImpl.scala:1460)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.getRecent(SimpleEnvContextImpl.scala:1507)
	at com.ligadata.KamanjaBase.RDDObject.getRecent(RddTraits.scala:737)
	at com.ligadata.KamanjaBase.RDDObject.getRecentOrNew(RddTraits.scala:751)
	at com.ligadata.KamanjaBase.JavaRDDObjectLike$class.getRecentOrNew(RddTraits.scala:1123)
	at com.ligadata.KamanjaBase.AbstractJavaRDDObjectLike.getRecentOrNew(RddTraits.scala:1063)
	at com.ligadata.kamanja.financial.V1.SubscriberUsageAlert.execute(SubscriberUsageAlert.java:62)
	at com.ligadata.KamanjaManager.LearningEngine$$anonfun$RunAllModels$1.apply(LearningEngine.scala:60)
	at com.ligadata.KamanjaManager.LearningEngine$$anonfun$RunAllModels$1.apply(LearningEngine.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.ligadata.KamanjaManager.LearningEngine.RunAllModels(LearningEngine.scala:51)
	at com.ligadata.KamanjaManager.LearningEngine.execute(LearningEngine.scala:132)
	at com.ligadata.KamanjaManager.ExecContextImpl$$anonfun$execute$1.apply(ExecContext.scala:68)
	at com.ligadata.KamanjaManager.ExecContextImpl$$anonfun$execute$1.apply(ExecContext.scala:66)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:66)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(KafkaSimpleConsumer.scala:249)
	at scala.util.control.Breaks.breakable(Breaks.scala:37)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:225)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:221)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:32)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at kafka.message.MessageSet.foreach(MessageSet.scala:67)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1.run(KafkaSimpleConsumer.scala:221)
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060)
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
	at java.lang.Thread.run(Thread.java:745)
```
```
ERROR [pool-7-thread-4] - Table System.AccountInfo Key null Not found for timerange: (-9223372036854775808,9223372036854775807). Message:null, Cause:null
StackTrace:java.lang.NullPointerException
	at com.ligadata.KvBase.LoadKeyComp$$anonfun$compare$1.apply$mcVI$sp(KvBase.scala:221)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at com.ligadata.KvBase.LoadKeyComp.compare(KvBase.scala:220)
	at com.ligadata.KvBase.LoadKeyComp.compare(KvBase.scala:197)
	at java.util.TreeMap.compare(TreeMap.java:1188)
	at java.util.TreeMap.put(TreeMap.java:531)
	at java.util.TreeSet.add(TreeSet.java:255)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$$anonfun$LoadDataIfNeeded$1.apply(SimpleEnvContextImpl.scala:905)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$$anonfun$LoadDataIfNeeded$1.apply(SimpleEnvContextImpl.scala:888)
	at scala.collection.immutable.Range.foreach(Range.scala:141)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.LoadDataIfNeeded(SimpleEnvContextImpl.scala:888)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.getLocalRecent(SimpleEnvContextImpl.scala:1456)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.getRecent(SimpleEnvContextImpl.scala:1507)
	at com.ligadata.KamanjaBase.RDDObject.getRecent(RddTraits.scala:737)
	at com.ligadata.KamanjaBase.RDDObject.getRecentOrNew(RddTraits.scala:751)
	at com.ligadata.KamanjaBase.JavaRDDObjectLike$class.getRecentOrNew(RddTraits.scala:1123)
	at com.ligadata.KamanjaBase.AbstractJavaRDDObjectLike.getRecentOrNew(RddTraits.scala:1063)
	at com.ligadata.kamanja.financial.V1.SubscriberUsageAlert.execute(SubscriberUsageAlert.java:62)
	at com.ligadata.KamanjaManager.LearningEngine$$anonfun$RunAllModels$1.apply(LearningEngine.scala:60)
	at com.ligadata.KamanjaManager.LearningEngine$$anonfun$RunAllModels$1.apply(LearningEngine.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.ligadata.KamanjaManager.LearningEngine.RunAllModels(LearningEngine.scala:51)
	at com.ligadata.KamanjaManager.LearningEngine.execute(LearningEngine.scala:132)
	at com.ligadata.KamanjaManager.ExecContextImpl$$anonfun$execute$1.apply(ExecContext.scala:68)
	at com.ligadata.KamanjaManager.ExecContextImpl$$anonfun$execute$1.apply(ExecContext.scala:66)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:66)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(KafkaSimpleConsumer.scala:249)
	at scala.util.control.Breaks.breakable(Breaks.scala:37)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:225)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:221)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:32)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at kafka.message.MessageSet.foreach(MessageSet.scala:67)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1.run(KafkaSimpleConsumer.scala:221)
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060)
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ligadata-pokuri** [comment]
William,

Can you check this in 1.4.0. once it is stable and our 1.4.0. features testing is done. As far as I know 1.3.x does not have this issue.

**Comment by ligadata-william** [comment]
Blocked by issue #1108

**Comment by ligadata-pokuri** [comment]
William, can you verify this once on 1.4.0. release.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
