### ISSUE TITLE
Metadata tables fail to be created on cassandra if they're more than 48 characters long

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#823]
When the engine attempted to created a table for the messages it was processing, it failed to upload them to cassandra because the name was too long.
```
ERROR [pool-7-thread-1] - Stacktrace:com.datastax.driver.core.exceptions.InvalidQueryException: Table names shouldn't be more than 48 characters long (got "com_ligadata_kamanja_timepartition_timepartitionmsg")
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:35)
	at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:259)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:175)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36)
	at com.ligadata.keyvaluestore.CassandraAdapter.liftedTree2$1(CassandraAdapter.scala:259)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CreateContainer(CassandraAdapter.scala:257)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CheckTableExists(CassandraAdapter.scala:233)
	at com.ligadata.keyvaluestore.CassandraAdapter.get(CassandraAdapter.scala:645)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$$anonfun$LoadDataIfNeeded$1.apply(SimpleEnvContextImpl.scala:902)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$$anonfun$LoadDataIfNeeded$1.apply(SimpleEnvContextImpl.scala:888)
	at scala.collection.immutable.Range.foreach(Range.scala:141)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.LoadDataIfNeeded(SimpleEnvContextImpl.scala:888)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.localSetObject(SimpleEnvContextImpl.scala:970)
	at com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$.setObject(SimpleEnvContextImpl.scala:1152)
	at com.ligadata.KamanjaManager.LearningEngine.execute(LearningEngine.scala:125)
	at com.ligadata.KamanjaManager.ExecContextImpl$$anonfun$execute$1.apply(ExecContext.scala:68)
	at com.ligadata.KamanjaManager.ExecContextImpl$$anonfun$execute$1.apply(ExecContext.scala:66)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:66)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(KafkaSimpleConsumer.scala:249)
	at scala.util.control.Breaks.breakable(Breaks.scala:37)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:225)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:221)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:32)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at kafka.message.MessageSet.foreach(MessageSet.scala:67)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1.run(KafkaSimpleConsumer.scala:221)
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060)
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ligadata-william** [comment]
I'm trying this on the Sprint8Features branch and I'm getting some odd results. When I add a message/container I see something like this:
```
ERROR [main] - Stacktrace:java.lang.StringIndexOutOfBoundsException: String index out of range: 48
	at java.lang.String.substring(String.java:1907)
	at com.ligadata.keyvaluestore.CassandraAdapter.toTableName(CassandraAdapter.scala:285)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CreateContainer(CassandraAdapter.scala:255)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CheckTableExists(CassandraAdapter.scala:233)
	at com.ligadata.keyvaluestore.CassandraAdapter$$anonfun$put$1.apply(CassandraAdapter.scala:325)
	at com.ligadata.keyvaluestore.CassandraAdapter$$anonfun$put$1.apply(CassandraAdapter.scala:323)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.ligadata.keyvaluestore.CassandraAdapter.put(CassandraAdapter.scala:323)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.SaveObjectList(MetadataAPIImpl.scala:633)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UploadJarsToDB(MetadataAPIImpl.scala:1290)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddMessageDef(MetadataAPIImpl.scala:1955)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2078)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2158)
	at com.ligadata.MetadataAPI.Utility.MessageService$.addMessage(MessageService.scala:73)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:122)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:101)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)

ERROR [main] - Stacktrace:java.lang.StringIndexOutOfBoundsException: String index out of range: 48
	at java.lang.String.substring(String.java:1907)
	at com.ligadata.keyvaluestore.CassandraAdapter.toTableName(CassandraAdapter.scala:285)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CreateContainer(CassandraAdapter.scala:255)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CheckTableExists(CassandraAdapter.scala:233)
	at com.ligadata.keyvaluestore.CassandraAdapter$$anonfun$put$1.apply(CassandraAdapter.scala:325)
	at com.ligadata.keyvaluestore.CassandraAdapter$$anonfun$put$1.apply(CassandraAdapter.scala:323)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.ligadata.keyvaluestore.CassandraAdapter.put(CassandraAdapter.scala:323)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.SaveObjectList(MetadataAPIImpl.scala:633)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.SaveObjectList(MetadataAPIImpl.scala:720)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddMessageDef(MetadataAPIImpl.scala:1958)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2078)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2158)
	at com.ligadata.MetadataAPI.Utility.MessageService$.addMessage(MessageService.scala:73)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:122)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:101)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)

 WARN [main] - Not Notifying the engine about this operation because The property NOTIFY_ENGINE is not set to YES
ERROR [main] - Stacktrace:java.lang.StringIndexOutOfBoundsException: String index out of range: 48
	at java.lang.String.substring(String.java:1907)
	at com.ligadata.keyvaluestore.CassandraAdapter.toTableName(CassandraAdapter.scala:285)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CreateContainer(CassandraAdapter.scala:255)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CheckTableExists(CassandraAdapter.scala:233)
	at com.ligadata.keyvaluestore.CassandraAdapter.put(CassandraAdapter.scala:296)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.SaveObject(MetadataAPIImpl.scala:602)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.PutTranId(MetadataAPIImpl.scala:905)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.NotifyEngine(MetadataAPIImpl.scala:836)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddMessageDef(MetadataAPIImpl.scala:1960)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainerOrMessage(MetadataAPIImpl.scala:2078)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.AddContainer(MetadataAPIImpl.scala:2158)
	at com.ligadata.MetadataAPI.Utility.MessageService$.addMessage(MessageService.scala:73)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:122)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:101)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)

Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.kamanja.timepartition.timepartitionmsg.000000000001000016"
  }
}
```
When I attempt to add a scala model using that message, I see:
```
Adding the next model in the queue.
ERROR [main] - COMPILER_PROXY: Unable to find at least one message in the Metadata for this model
ERROR [main] - COMPILER_PROXY: unable to determine model metadata information during AddModel. ERROR metadataapi.timepartition
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Error : Model Compilation Failed, see compliation errors in the log"
  }
}
```

The key message here is "Unable to find at least one message in the Metadata for this model". I looked in cassandra and found the types for timepartitionmsg don't exist in the database. An odd bit of behavior is I try to add the message again and I get the same exact output as when I originally try to add the message, including the API Result indicating that I added the message successfully, which is strange since it should indicate that the message already exists.

Investigating further but I think the StringIndexOutOfBoundsException is causing issues without indicating the the APIResults that there's an issue. It also looks like the metadata can't be fetched properly.

I'm also getting the exception when uploading the model compile config
```
ERROR [main] - Stacktrace:java.lang.StringIndexOutOfBoundsException: String index out of range: 48
	at java.lang.String.substring(String.java:1907)
	at com.ligadata.keyvaluestore.CassandraAdapter.toTableName(CassandraAdapter.scala:285)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CreateContainer(CassandraAdapter.scala:255)
	at com.ligadata.keyvaluestore.CassandraAdapter.com$ligadata$keyvaluestore$CassandraAdapter$$CheckTableExists(CassandraAdapter.scala:233)
	at com.ligadata.keyvaluestore.CassandraAdapter.put(CassandraAdapter.scala:296)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.SaveObject(MetadataAPIImpl.scala:602)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.PutTranId(MetadataAPIImpl.scala:905)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.NotifyEngine(MetadataAPIImpl.scala:836)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.UploadModelsConfig(MetadataAPIImpl.scala:4865)
	at com.ligadata.MetadataAPI.Utility.ConfigService$.uploadCompileConfig(ConfigService.scala:112)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:289)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:101)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)

Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "UploadModelsConfig",
    "Result Data" : null,
    "Result Description" : "Upload of model config successful"
  }
}
```

**Comment by ligadata-william** [comment]
I changed private def toTableName in CassandraAdapter.scala from
```
private def toTableName(containerName: String): String = {
    // we need to check for other restrictions as well
    // such as length of the table, special characters etc
    //containerName.replace('.','_')
    // Cassandra has a limit of 48 characters for table name, so take the first 48 characters only
    // Even though we don't allow duplicate containers within the same namespace,
    // Taking first 48 characters may result in  duplicate table names
    // So I am reversing the long string to ensure unique name
    // Need to be documented, at the least.
    containerName.toLowerCase.replace('.', '_').replace('-', '_').reverse.substring(0, 48)
  }
```
to this:
```
private def toTableName(containerName: String): String = {
    // we need to check for other restrictions as well
    // such as length of the table, special characters etc
    //containerName.replace('.','_')
    // Cassandra has a limit of 48 characters for table name, so take the first 48 characters only
    // Even though we don't allow duplicate containers within the same namespace,
    // Taking first 48 characters may result in  duplicate table names
    // So I am reversing the long string to ensure unique name
    // Need to be documented, at the least.
    if(containerName.length < 48)
      containerName.toLowerCase.replace('.', '_').replace('-', '_').reverse.substring(0, containerName.length)
    else
      containerName.toLowerCase.replace('.', '_').replace('-', '_').reverse.substring(0, 48)
  }
```
and that seems to fix the StringIndexOutOfBoundsException. The current code assumes a length of 48 or more and throws an exception on any table name that is less.

**Comment by ligadata-william** [comment]
Including this change introduces additional issues. Now when I start the engine, it can't find any cluster configuration because all the table names have been reversed. Apparently, this operation is being performed on more than just containers, it's being performed on the schema names we provide in configuration, making future queries fail for those schema names because they don't exist as we'd expect.

**Comment by ligadata-william** [comment]
After thinking about things, I realize I re-assembled MetadataAPI after making the storage changes, but not the engine. I will re-assemble the engine fat jar and try again to see if it works.

**Comment by ligadata-william** [comment]
After assembling KamanjaManager, I'm still unable to retrieve cluster configuration.

**Comment by ligadata-krishna** [comment]
Why don't we error out and asking user to limit container name to 48 chars or less instead of manipulating length. You always have some issue even with reversing the string. The other option is to cut off the final name to 40 chars and append hash on entire name at end as hex string. The later solution is better, but it would be hard to predict the container name from original name if names overlap first 40 characters. Another option is to maintain map of full name to mapped name and expose some mechanism to get short name from full name and vice versa.

**Comment by ligadata-william** [comment]
The issue with asking the user to limit the message/container name to 48 chars or less is that namespace is currently included as part of some table names, so they may be forced to limit the use of namespaces.

The hex would make things even worse for people who want to query the database directly, especially if they have several messages and containers within the same namespace. It would increase the burden on our end to create DB access tools for users.

The map is a decent compromise, but I think it still makes things difficult for the user when they want to query cassandra. Where would this map be maintained, would it be another table? Then users are going to want to be able to quickly lookup based on this map in a database that doesn't do well with joins.

I need to do some research on cassandra to see if a viable solution can be found using what they currently support.

**Comment by ligadata-william** [comment]
This issue is fixed. Closing.
