### ISSUE TITLE
hbase tables not placed in the schema specified in configuration

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#826]
When first adding metadata to hbase, I get errors such as this:
```
 WARN [main] - Encountered problems when prefetch hbase:meta table:
org.apache.hadoop.hbase.TableNotFoundException: Cannot find row in hbase:meta for table: config_objects, row=config_objects,,99999999999999
	at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:146)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.prefetchRegionCache(HConnectionManager.java:1159)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:1223)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1111)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1068)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getRegionLocation(HConnectionManager.java:909)
	at org.apache.hadoop.hbase.client.RegionServerCallable.prepare(RegionServerCallable.java:72)
	at org.apache.hadoop.hbase.client.ScannerCallable.prepare(ScannerCallable.java:125)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:113)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:90)
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:282)
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:187)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:182)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:109)
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:738)
	at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:503)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllConfigObjectsIntoCache(MetadataAPIImpl.scala:3840)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:3914)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5769)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:97)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
 WARN [main] - Encountered problems when prefetch hbase:meta table:
org.apache.hadoop.hbase.TableNotFoundException: Cannot find row in hbase:meta for table: config_objects, row=config_objects,,99999999999999
	at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:146)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.prefetchRegionCache(HConnectionManager.java:1159)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:1223)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1111)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1068)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getRegionLocation(HConnectionManager.java:909)
	at org.apache.hadoop.hbase.client.RegionServerCallable.prepare(RegionServerCallable.java:72)
	at org.apache.hadoop.hbase.client.ScannerCallable.prepare(ScannerCallable.java:125)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:113)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:90)
	at org.apache.hadoop.hbase.client.ClientScanner.close(ClientScanner.java:449)
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:288)
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:187)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:182)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:109)
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:738)
	at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:503)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllConfigObjectsIntoCache(MetadataAPIImpl.scala:3840)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:3914)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5769)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:97)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
 WARN [main] - scanner failed to close. Exception follows: org.apache.hadoop.hbase.TableNotFoundException: config_objects
ERROR [main] - Stacktrace:org.apache.hadoop.hbase.TableNotFoundException: config_objects
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:1242)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1111)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1068)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getRegionLocation(HConnectionManager.java:909)
	at org.apache.hadoop.hbase.client.RegionServerCallable.prepare(RegionServerCallable.java:72)
	at org.apache.hadoop.hbase.client.ScannerCallable.prepare(ScannerCallable.java:125)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:113)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:90)
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:282)
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:187)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:182)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:109)
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:738)
	at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:503)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllConfigObjectsIntoCache(MetadataAPIImpl.scala:3840)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:3914)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5769)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:97)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
```

This doesn't appear to cause a failure, however, when I open hbase shell and run the command 'list' to see the list of tables on hbase, I see that instead of tables such as metadata:table_name, I'm simply seeing table_name. This will make it impossible for organizations to logically separate data into different schemas.

**Comment by ligadata-william** [comment]
The stack traces seen before were introduced by running:
```
kamanja upload cluster config $KAMANJA_HOME/config/ClusterConfig.json
```
on the branch Sprint8Features.

**Comment by ligadata-william** [comment]
Verified and closing.
