### ISSUE TITLE
There is no error shown by MetadataAPI when failing to connect to Cassandra

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#827]
When running MetadataAPI configured to connect to cassandra, MetadataAPI failed to connect because cassandra was not running, but there was no ERROR message presented. I changed logging to DEBUG and found this:
```
DEBUG [New I/O boss #9] - Connection[localhost/127.0.0.1:9042-1, inFlight=0, closed=false] connection error
java.net.ConnectException: Connection refused: localhost/127.0.0.1:9042
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
The ConnectionException is logged in DEBUG mode instead of ERROR as it should be.

**Comment by ligadata-william** [comment]
Verified and closing.
