### ISSUE TITLE
Couldn't figure out the following error when starting MetadataAPIService until DEBUG is turned on

### ISSUE THREAD

**Issue by ligadata-ramana** [ligaDATA/Kamanja#868]
DEBUG [metadata-api-service-akka.actor.default-dispatcher-2] - Initialize Leader Latch
DEBUG [main] - Stacktrace:java.io.IOException: Could not open /media/home2/installKamanja/config/keystore.jks as a file, class path resource, or URL.
	at org.apache.camel.util.jsse.JsseParameters.resolveResource(JsseParameters.java:166)
	at org.apache.camel.util.jsse.KeyStoreParameters.createKeyStore(KeyStoreParameters.java:171)
	at org.apache.camel.util.jsse.KeyManagersParameters.createKeyManagers(KeyManagersParameters.java:106)
	at org.apache.camel.util.jsse.SSLContextParameters.createSSLContext(SSLContextParameters.java:234)
	at com.ligadata.metadataapiservice.LigadataSSLConfiguration$class.sslContext(LigadataSSLConfiguration.scala:47)
	at com.ligadata.metadataapiservice.APIService.sslContext(APIService.scala:36)
	at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:154)
	at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:182)
	at com.ligadata.metadataapiservice.APIService.main(APIService.scala)

**Comment by ligadata-ashish** [comment]
@ligadata-dan Please fix
