### ISSUE TITLE
When running command "dump all cluster cfgs" if no model configs have been uploaded to hbase and exception is thrown

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#876]
After uploading cluster configuration to a clean hbase, if no model configurations have been uploaded, then running the command "kamanja dump all cluster cfgs" displays an ERROR:
```
ERROR [main] - Stacktrace:org.apache.hadoop.hbase.TableNotFoundException: Table 'metadata:model_config_objects' was not found, got: metadata:config_objects.
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1225)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1109)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:293)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:147)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:56)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:299)
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:278)
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:140)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:135)
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:845)
	at com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:505)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllModelConfigsIntoChache(MetadataAPIImpl.scala:3938)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:3963)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:5810)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:98)
	at scala.com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
```

**Comment by ligadata-william** [comment]
In general, I'm noticing several errors in hbase. Any time a table isn't found it is displayed as an ERROR instead of silently creating the non-existent table.

**Comment by ligadata-ramana** [comment]
It is the same issue as #877 . Please merge the changes from the branch "StorageExceptions"

**Comment by ligadata-william** [comment]
This is fixed.
