### ISSUE TITLE
kamanja get message <messageName> results in error

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#910]
I ran the command
```
kamanja get message system.irismsg.000000000001000001
```
and received the following error
```
ERROR [main] - Node Undefined not found in metadata
java.lang.NumberFormatException: For input string: "JSON"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:276)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:30)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetMessageDefFromCache(MetadataAPIImpl.scala:4781)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetMessageDef(MetadataAPIImpl.scala:6013)
	at com.ligadata.MetadataAPI.Utility.MessageService$.getMessage(MessageService.scala:200)
	at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:193)
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:144)
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
```

After the exception appears, I get a menu to select a message
```
Pick the message to be presented from the following list:
[1] system.irismsg.000000000001000001

Enter your choice:
```
After selecting the message, the following appears:
```
Result: [Ljava.lang.StackTraceElement;@28f9fedd
```

This is on branch Sprint8FeaturesWithJpmml

**Comment by ligadata-pokuri** [comment]
Hi william,

Can you try with properties file? like kamanja MetadataApiConfig.properties get message system.irismsg.000000000001000001

**Comment by ligadata-william** [comment]
Same result.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
