### ISSUE TITLE
running kamanja with two strings that combine into an invalid command causes a MatchError exception

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#916]
Examples to reproduce include:
```
kamanja get a
kamanja add b
kamanja blah blah
etc...
```
which results in the error:
```
Exception in thread "main" scala.MatchError: a (of class java.lang.String)
	at com.ligadata.MetadataAPI.StartMetadataAPI$.AltRoute(StartMetadataAPI.scala:442)
	at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:154)
	at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala)
```

Additionally, using more than three or more strings that result in an invalid command such as
```
kamanja a b c
kamanja this is not a valid command
```
ends up displaying an error:
```
We have a problem: `(' expected but `a' found at: 1.8
```
followed by the standard error
```
Invalid command action! action=thisisnotavalidcommandUsage:
  kamanja <action> <optional input>
 e.g. kamanja add message $HOME/msg.json
```

**Comment by ligadata-dan** [comment]
@ligadata-william  

FYI, Rich took this one

**Comment by ligadata-william** [comment]
Verified as fixed. closing.
