### ISSUE TITLE
Starting MetadataAPIService results in exception and hang

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#920]
When starting the MetadataAPIService, the following error occurs:
```
20:53:06.953 [main] ERROR com.ligadata.MetadataAPI.MetadataAPIGlobalLogger$ - Failed to connect to Datastore. Reason:java.lang.ClassNotFoundException: org.apache.commons.collections.map.UnmodifiableMap. Message:org/apache/commons/collections/map/UnmodifiableMap
Cause:
java.lang.NoClassDefFoundError: org/apache/commons/collections/map/UnmodifiableMap
	at org.apache.hadoop.conf.Configuration$DeprecationContext.<init>(Configuration.java:409)
	at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:448)
	at com.ligadata.keyvaluestore.HBaseAdapter.<init>(HBaseAdapter.scala:167)
	at com.ligadata.keyvaluestore.HBaseAdapter$.CreateStorageAdapter(HBaseAdapter.scala:1509)
	at com.ligadata.keyvaluestore.KeyValueManager$.Get(KeyValueManager.scala:66)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetDataStoreHandle(MetadataAPIImpl.scala:2015)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:2033)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:7858)
	at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:132)
	at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:182)
	at com.ligadata.metadataapiservice.APIService.main(APIService.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.map.UnmodifiableMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```
after which the service hangs indefinitely until manually killed.

**Comment by ligadata-pokuri** [comment]
Fixed in Pull request https://github.com/ligaDATA/Kamanja/pull/921. Please verify and let us know

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
