### ISSUE TITLE
Unable to get message from MetadataAPIService

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#922]
After adding a message, I ran the following curl command to get that message from the MetadataAPIService
```
curl -k https://localhost:8081/api/message/com.ligadata.kamanja.samples.messages.msg1.000000000001000000
```
which results in the following error appearing on the MetadataAPIService
```
[ERROR] [01/26/2016 21:36:56.383] [metadata-api-service-akka.actor.default-dispatcher-4] [akka://metadata-api-service/user/metadata-api-service/$b] For input string: "JSON"
java.lang.NumberFormatException: For input string: "JSON"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:276)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:30)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetMessageDefFromCache(MetadataAPIImpl.scala:4795)
	at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetMessageDef(MetadataAPIImpl.scala:6027)
	at com.ligadata.metadataapiservice.GetObjectsService.GetObjectDef(GetObjectsService.scala:91)
	at com.ligadata.metadataapiservice.GetObjectsService$$anonfun$process$1$$anonfun$apply$mcV$sp$1.apply(GetObjectsService.scala:134)
	at com.ligadata.metadataapiservice.GetObjectsService$$anonfun$process$1$$anonfun$apply$mcV$sp$1.apply(GetObjectsService.scala:124)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.ligadata.metadataapiservice.GetObjectsService$$anonfun$process$1.apply$mcV$sp(GetObjectsService.scala:124)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at com.ligadata.metadataapiservice.GetObjectsService.process(GetObjectsService.scala:123)
	at com.ligadata.metadataapiservice.GetObjectsService$$anonfun$receive$1.applyOrElse(GetObjectsService.scala:55)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.ligadata.metadataapiservice.GetObjectsService.aroundReceive(GetObjectsService.scala:38)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

This unhandled exception causes the client to hang until timeout.

**Comment by ligadata-dan** [comment]
https://github.com/ligaDATA/Kamanja/pull/928

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
