### ISSUE TITLE
Exception when starting MetadataAPIServuce Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Preconditions

### ISSUE THREAD

**Issue by ligadata-ahmad** [ligaDATA/Kamanja#926]
I am getting exception when running this command  

I have  Scala version 2.11.7 (OpenJDK 64-Bit Server VM, Java 1.7.0_91)
I will try upgrade to java 8 then  package and run it again. 

java -Dlog4j.configurationFile=file:../config/log4j2.xml -jar ./MetadataAPIService-1.0 --config ../config/MetadataAPIConfig.properties

 WARN [main] - DATABASE_SCHEMA remains unset
 WARN [main] - DATABASE_LOCATION remains unset
 WARN [main] - DATABASE_HOST remains unset
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main] - DATABASE remains unset
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Preconditions
        at org.apache.curator.ensemble.fixed.FixedEnsembleProvider.<init>(FixedEnsembleProvider.java:39)
        at org.apache.curator.framework.CuratorFrameworkFactory$Builder.connectString(CuratorFrameworkFactory.java:193)
        at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:94)
        at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:79)
        at com.ligadata.ZooKeeper.CreateClient$.createSimple(CreateClient.scala:102)
        at com.ligadata.ZooKeeper.CreateClient$.CreateNodeIfNotExists(CreateClient.scala:34)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.initZkListeners(MetadataAPIImpl.scala:7894)
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:7855)
        at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:132)
        at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:182)
        at com.ligadata.metadataapiservice.APIService.main(APIService.scala)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Preconditions
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 11 more

**Comment by ligadata-pokuri** [comment]
Unable to repro in the following conditions

Case 1:
Built with Sbt 0.13.7, Java 1.8.0_05, Scala 2.11.7
Ran with Java 1.8.0_05

Case 2:
Built with Sbt 0.13.7, Java 1.8.0_05, Scala 2.11.7
Ran with Java 1.7.0_79

Case 3:
Built with Sbt 0.13.7, Java 1.7.0_79, Scala 2.11.7
Ran with Java 1.7.0_79

**Comment by ligadata-saleh** [comment]
Ahmad make sure thatvuare using oracle jdk not open jdk , also did you complie the kamanja source under java 8 or 7 clean ur ivy2 folder for sbt to install the correct jars , searching on the net this may be cuz old kafka and zookeeper jars . 

Thanks 
Saleh

**Comment by ligadata-ahmad** [comment]
The Issue is fixed when using sbt 0.13.7 instead of  sbt 0.13.9

**Comment by ligadata-pokuri** [comment]
Alison, can you please document this for now. They have to use sbt 0.13.7 for now. We will validate a bit more with  the builds built with sbt 0.13.8/0.13.9 later and change the documentation at that time
