### ISSUE TITLE
MigrateManager should check to see if tables are enabled and give clear message if disabled

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#927]
I ran MigrateManager and one of the tables was disabled, which caused an exception. This should be checked prior to attempting operations and either enable the table or present a message indicating that table needs to be enabled.

ERROR:
```
ERROR [main] - Failed to rename the table kamanja:transaction_id:org.apache.hadoop.hbase.TableNotEnabledException: kamanja:transaction_id
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.prepareDisable(DisableTableProcedure.java:302)
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.executeFromState(DisableTableProcedure.java:132)
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.executeFromState(DisableTableProcedure.java:55)
	at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:107)
	at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:400)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:869)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:673)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:626)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$200(ProcedureExecutor.java:70)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$1.run(ProcedureExecutor.java:413)

ERROR [main] - Failed to Migrate
com.ligadata.Exceptions.StorageDDLException: Failed to execute create/drop operations on Database
	at com.ligadata.keyvaluestore.HBaseAdapter.CreateDDLException(HBaseAdapter.scala:84) ~[?:?]
	at com.ligadata.keyvaluestore.HBaseAdapter.renameTable(HBaseAdapter.scala:1292) ~[?:?]
	at com.ligadata.keyvaluestore.HBaseAdapter.copyTable(HBaseAdapter.scala:1382) ~[?:?]
	at com.ligadata.keyvaluestore.HBaseAdapter.copyTable(HBaseAdapter.scala:1386) ~[?:?]
	at com.ligadata.Migrate.MigrateTo_V_1_3$$anonfun$backupMetadataTables$2.apply(MigrateTo.scala:254) ~[?:?]
	at com.ligadata.Migrate.MigrateTo_V_1_3$$anonfun$backupMetadataTables$2.apply(MigrateTo.scala:253) ~[?:?]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[?:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[?:?]
	at com.ligadata.Migrate.MigrateTo_V_1_3.backupMetadataTables(MigrateTo.scala:253) ~[?:?]
	at com.ligadata.Migrate.Migrate.run(Migrate.java:448) [MigrateManager-1.0:1.0]
	at com.ligadata.Migrate.Migrate.main(Migrate.java:548) [MigrateManager-1.0:1.0]
Caused by: org.apache.hadoop.hbase.TableNotEnabledException: org.apache.hadoop.hbase.TableNotEnabledException: kamanja:transaction_id
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.prepareDisable(DisableTableProcedure.java:302)
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.executeFromState(DisableTableProcedure.java:132)
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.executeFromState(DisableTableProcedure.java:55)
	at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:107)
	at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:400)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:869)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:673)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:626)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$200(ProcedureExecutor.java:70)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$1.run(ProcedureExecutor.java:413)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_65]
	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106) ~[?:?]
	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:95) ~[?:?]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:226) ~[?:?]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:240) ~[?:?]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:140) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3601) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin.disableTableAsync(HBaseAdmin.java:975) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin.disableTable(HBaseAdmin.java:1008) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin.disableTable(HBaseAdmin.java:1043) ~[?:?]
	at com.ligadata.keyvaluestore.HBaseAdapter.renameTable(HBaseAdapter.scala:1285) ~[?:?]
	... 9 more
Caused by: org.apache.hadoop.hbase.ipc.RemoteWithExtrasException: org.apache.hadoop.hbase.TableNotEnabledException: kamanja:transaction_id
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.prepareDisable(DisableTableProcedure.java:302)
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.executeFromState(DisableTableProcedure.java:132)
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.executeFromState(DisableTableProcedure.java:55)
	at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:107)
	at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:400)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:869)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:673)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:626)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$200(ProcedureExecutor.java:70)
	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$1.run(ProcedureExecutor.java:413)

	at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1254) ~[?:?]
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:216) ~[?:?]
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:300) ~[?:?]
	at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$BlockingStub.disableTable(MasterProtos.java:44764) ~[?:?]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation$4.disableTable(ConnectionManager.java:1797) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin$9.call(HBaseAdmin.java:980) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin$9.call(HBaseAdmin.java:975) ~[?:?]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3601) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin.disableTableAsync(HBaseAdmin.java:975) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin.disableTable(HBaseAdmin.java:1008) ~[?:?]
	at org.apache.hadoop.hbase.client.HBaseAdmin.disableTable(HBaseAdmin.java:1043) ~[?:?]
	at com.ligadata.keyvaluestore.HBaseAdapter.renameTable(HBaseAdapter.scala:1285) ~[?:?]
	... 9 more
```

Workaround:
Run HBase shell
run command for whichever table was named in the error:
```
enable 'namespace:table_name'
```
Run MigrateManager again

**Comment by ligadata-pokuri** [comment]
Removed snapshot functionality now. So, we are using different approach to backup tables. Fixed in https://github.com/ligaDATA/Kamanja/pull/935

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
