### ISSUE TITLE
Using clusterInstallerDriver-1.0, when specifying --logDir as a non-existent folder ugly exception appears

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#968]
If we specify a directory that doesn't exist, we get a FileNotFoundException like such:
```
Exception in thread "main" java.io.FileNotFoundException: /tmp/clusterInstallLogs/InstallDriver.2016-02-19_16:17:36.488.log (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at com.ligadata.clusterInstaller.InstallDriverLog.<init>(InstallDriver.scala:67)
	at com.ligadata.clusterInstaller.InstallDriver$.main(InstallDriver.scala:252)
	at com.ligadata.clusterInstaller.InstallDriver.main(InstallDriver.scala)
```

Rather than throw this exception, we need to check that the directory given exists and either attempt to create this directory or state a simple message such as:
```
Directory '/tmp/clusterInstallLogs' does not exist. Please create this directory and try again.
```

**Comment by ligadata-pokuri** [comment]
William,
This is fixed in latest version
Can you check this with latest Installer.

**Comment by ligadata-pokuri** [comment]
@ligadata-saleh can you verify this?

**Comment by ligadata-saleh** [comment]
verfied
