### ISSUE TITLE
ClusterInstallerDriver hangs when unable to connect to zookeeper

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#988]
During cluster installation, during the GetComponent calls, the driver hangs when it fails to connect to zookeeper rather than retrying.

**Comment by ligadata-william** [comment]
Here are the last couple of lines:
```
DEBUG [main] - getComponentsVersion cmd used: List(bash, -c, /private/tmp/Kamanja/KamanjaInstall-1.3.3_2.11/bin/GetComponentsVersions.sh  --componentVersionJarAbsolutePath /private/tmp/Kamanja/KamanjaInstall-1.3.3_2.11/bin/GetComponent-1.0 --componentVersionJarFileName GetComponent-1.0 --remoteNodeIp 10.100.0.56 --resultsFileAbsolutePath /tmp/componentResultsFile10.100.0.56.txt --resultFileName componentResultsFile10.100.0.56.txt --rootDirPath /tmp/Kamanja/Kamanja-1.3.3_2.11 --pathOutputFileName __path_output_1_285120623_1678115320_183818195_255358643 --ignoreGetComponentsInfo false --jsonArg '[{ "component" : "zookeeper", "hostslist" : "localhost:2181" },{ "component" : "kafka", "hostslist" : "10.1.10.28:9092,10.1.10.28:9093,10.1.10.28:9094" },{"StoreType":"hbase","SchemaName":"kamanja","Location":"10.1.10.28"},{ "component" : "scala", "hostslist" : "localhost" },{ "component" : "java", "hostslist" : "localhost" }]')
java.io.IOException: Zookeeper not connected. Current state is:CONNECTING
	at com.ligadata.kamanja.CheckerComponent.ZookeeperHelper.ZConnect(ZookeeperHelper.java:65)
	at com.ligadata.kamanja.CheckerComponent.ZookeeperHelper.askZookeeper(ZookeeperHelper.java:183)
	at com.ligadata.kamanja.CheckerComponent.Checker.CheckComponent(Checker.java:47)
	at com.ligadata.kamanja.CheckerComponent.Checker.CheckServices(Checker.java:167)
	at com.ligadata.kamanja.CheckerComponent.Checker.main(Checker.java:244)
```

**Comment by ligadata-ashish** [comment]
@ligadata-pokuri Please take a look. Seems a bad user experience for the customer
