### ISSUE TITLE
MetadataAPIService-1.0  is not running on Kamanja 1.3.3 

### ISSUE THREAD

**Issue by ligadata-saleh** [ligaDATA/Kamanja#991]
after running the service am receiving the below exception , reading about the problem and looking in the MetadataAPIService sbt file we are excluding the scala-reflet and the scala-compiler from the jar from reason . 

java.lang.NoClassDefFoundError: scala/reflect/runtime/package$
        at com.ligadata.Utils.KamanjaLoaderInfo.<init>(ClassLoaderInfo.scala:125) ~[MetadataAPIService-1.0:1.0]
        at com.ligadata.keyvaluestore.KeyValueManager$.<init>(KeyValueManager.scala:33) ~[MetadataAPIService-1.0:1.0]
        at com.ligadata.keyvaluestore.KeyValueManager$.<clinit>(KeyValueManager.scala) ~[MetadataAPIService-1.0:1.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.GetDataStoreHandle(MetadataAPIImpl.scala:1985) ~[MetadataAPIService-1.0:1.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.OpenDbStore(MetadataAPIImpl.scala:2002) [MetadataAPIService-1.0:1.0]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:7780) [MetadataAPIService-1.0:1.0]
        at com.ligadata.metadataapiservice.APIService.com$ligadata$metadataapiservice$APIService$$StartService(APIService.scala:141) [MetadataAPIService-1.0:1.0]
        at com.ligadata.metadataapiservice.APIService$.main(APIService.scala:192) [MetadataAPIService-1.0:1.0]
        at com.ligadata.metadataapiservice.APIService.main(APIService.scala) [MetadataAPIService-1.0:1.0]
Caused by: java.lang.ClassNotFoundException: scala.reflect.runtime.package$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_73]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_73]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
        ... 9 more

**Comment by ligadata-pokuri** [comment]
Hi Saleh,
Can you check whether your package & scala version you are using matches or different?

**Comment by ligadata-pokuri** [comment]
Hi Saleh,

Can you try this?

Replace KAMANJA_HOME with your install dir

KAMANJA_HOME=/data/Kamanja/Kamanja-1.3.3_2.11

java -Dlog4j.configurationFile=file:$KAMANJA_HOME/config/log4j2.xml -cp $KAMANJA_HOME/lib/system/scala-compiler-2.11.7.jar:$KAMANJA_HOME/lib/system/scala-reflect-2.11.7.jar:$KAMANJA_HOME/bin/MetadataAPIService-1.0 com.ligadata.metadataapiservice.APIService --config $KAMANJA_HOME/config/MetadataAPIConfig.properties
